### ISSUE TITLE
Retorno de XML nas funcoes / ToolsNFePHP

### ISSUE THREAD

**Issue by meio** [nfephp-org/nfephp#172]
ola,
hoje a classe tools não me atende no sentido dos xmls de envio e retorno,
no meu caso eu gravo em banco o xml de envio para a receita não só da NFe, mas dos eventos, inutilização, enfim de todos os serviços, então venho através deste sugerir para que na variável aRetorno dos métodos seja incluído um novo valor que é referente ao xml de envio para SEFAZ, assim é possível pegar na chamada do método esses dados para que seja gravado em banco.

 O que vocês acham?

**Comment by robmachado** [comment]
Já realizado na branch DEVELOP
