### ISSUE TITLE
incluir na classe Tools NFeDistribuicaoDFe

### ISSUE THREAD

**Issue by robmachado** [nfephp-org/nfephp#214]
Método getDistDFe() 

A Nota Técnica 2014/002 v.1.01 incluiu um novo serviço para acesso aos documentos fiscais pelos atores e o sistema atual para download das NFe método getListNFe() irá parar de funcionar em fevereiro de 2015.

**Comment by robmachado** [comment]
Incluída a função 

   /**
     * getDistDFe
     * Serviço destinado à distribuição de informações resumidas e documentos 
     * fiscais eletrônicos de interesse de um ator, seja este pessoa 
     * física ou jurídica.
     * 
     * Este serviço é oferecido apenas no AN - Ambiente Nacional
     * Web Service de Consulta da Relação de Documentos Destinados
     * este método irá substituir o método getListNFe
     * 
     * @param string $fonte Pode ser "AN" ou em alguns casos "RS"
     * @param string $tpAmb 
     * @param integer $ultNSU se $numNSU for zero serão retornados os 50 docs a patrir desse numero
     * @param integer $numNSU se $numNSU for diferente de zero será retornado apenas esse NSU
     * @param array $resp array onde é retornado os dados da mensagem
     * @param boolean $descompactar se true extrai os dados zipados 
     * @return mixed boolean ou string retorna o xml da SEFAZ
     * @throws nfephpException
     */
    public function getDistDFe(
        $fonte = 'AN',
        $tpAmb = '2',
        $ultNSU = 0,
        $numNSU = 0,
        &$resp = array(),
        $descompactar = false
    )

**Comment by tonicospinelli** [comment]
PR #295

**Comment by robmachado** [comment]
Fernando;

Qual unidade da federação ???

Roberto

**Comment by fmertins** [comment]
Oi, RS.
