### ISSUE TITLE
 Averbação Eletrônica CTe NFe

### ISSUE THREAD

**Issue by cacio** [nfephp-org/nfephp#223]
Questão de Averbação Eletrônica CTe NFe alguem ja chegou a elaborar uma integração com AT&M e seu webservice ?

**Comment by proflibajunior** [comment]
Bom dia, alguém tem esta documentação para fornecer? Pode ser enviado para junior@anhambi.com.br

**Comment by rafaelbeecker** [comment]
bom dia @proflibajunior, eu encaminhei a documentação para seu e-mail
