### ISSUE TITLE
Numero de lote no evento de cancelamento!

### ISSUE THREAD

**Issue by EdilsonAlvesDeOliveira** [nfephp-org/nfephp#232]
Percebi  que o método cancelEvent do NFePHP está gerando um numero de forma automática para o campo "Lote", porem no manual diz que esse campo deve ser um sequencial auto-incrementado, parece ser mais prudente colocar um novo parâmetro no método de cancelamento.

**Comment by robmachado** [comment]
Conforme definido pelo próprio manual:
"Lote é um  número seqüencial autoincremental único para identificação do
Lote. A responsabilidade de gerar e controlar é exclusiva do autor
do evento. O Web Service não faz qualquer uso deste
identificador."

O mecanismo usado para gerar o numero de Lote é microtime então não haverá repetição desse numero (por um bom tempo alguns milhões de anos)  e como não é usado para nada não tem o menor sentido usa-lo.
