### ISSUE TITLE
Erro 215 - Formato do xml invalido

### ISSUE THREAD

**Issue by Soufraz** [nfephp-org/nfephp#247]
Olá pessoal,
Estou testando o nfephp e ao executar o arquivo /nfephp/exemplos/NFe/testaNFeEnvio.php, recebo o seguinte erro:

```
houve erro !! 215 - Rejeicao: Falha no schema XML - The element 'NFe' in namespace 'http://www.portalfiscal.inf.br/nfe' has incomplete content. List of possible elements expected: 'Signature' in namespace 'http://www.w3.org/2000/09/xmldsig#'. 
```
Já utilizei um verificador de xml e ele me diz que a assinatura está incorreta e os valores total diferem da formula utilizada nos calculos dos valores unitarios.
Existe alguma nova versão de um xml com formato valido para testar a biblioteca?
Obrigado..

**Comment by pcesarmendes** [comment]
Já descobri o problema.

O número de série da nota não pode ter zeros à esquerda, como é exigido
para a emissão da nota. Se você enviar como 001 da o maldito Xml inválido.

Pedi um tempão até chegar a solução para esse erro absurdo na validação
pelo SEFAZ SP.

Obrigado

Paulo Mendes
Em 30/12/2014 10:45, "Roberto L. Machado" <notifications@github.com>
escreveu:

**Comment by demartinezraul** [comment]
Utilizando serviço NFeDistribuicaoDFe para download de NFe,
xml padrão de ENVIO ao sefaz.

<?xml version="1.0" encoding="UTF-8"?>
<soap12:Envelope xmlns:soap12="http://www.w3.org/2003/05/soap-envelope" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
    <soap12:Header>
        <nfeCabecMsg xmlns="http://www.portalfiscal.inf.br/nfe/wsdl/NFeDistribuicaoDFe">
            <cUF>91</cUF>
            <versaoDados>1.00</versaoDados>
        </nfeCabecMsg>
    </soap12:Header>
    <soap12:Body>
        <nfeDistDFeInteresse xmlns="http://www.portalfiscal.inf.br/nfe/wsdl/NFeDistribuicaoDFe">
            <nfeDadosMsg>
                <distDFeInt xmlns="http://www.portalfiscal.inf.br/nfe" versao="1.00">
                    <tpAmb>1</tpAmb>
                    <cUFAutor>35</cUFAutor>
                    <CNPJ>CNPJ DA EMPRESA</CNPJ>
                    <distNSU>
                        <ultNSU>000000000000000</ultNSU>
                    </distNSU>
                </distDFeInt>
            </nfeDadosMsg>
        </nfeDistDFeInteresse>
    </soap12:Body>
</soap12:Envelope>
