### ISSUE TITLE
Refatoração de Código

### ISSUE THREAD

**Issue by marcusbalbi** [nfephp-org/nfephp#262]
Bom dia @robmachado , comecei a acompanhar o projeto no início deste ano, Tive alguns contratempos na instalação da Biblioteca em um Projeto da empresa que eu Trabalhava, com isso resolvi por conta própria copiar esta Biblioteca e fazer uma refatoração para que ficasse um pouco mais claro o funcionamento dela para a equipe de Desenvolvimento. Como este Projeto é Open Source criei um Projeto na minha conta chamado nfephp2 , Como vi que a Biblioteca vai passar por uma refatoração, gostaria de deixar aqui a minha refatoração para Analise e também dizer que posso também contribuir de alguma forma para o Projeto! 

Forte Abraço!

Link da Biblioteca : https://github.com/marcusbalbi/nfephp2

**Comment by walkeralencar** [comment]
Olá nfephp-org/nfephp,
Uma mensagem de walkeralencar foi deixada no IQ Elite para você. 
Clique aqui a.iqelite.com/j/S4mBgL/aez/?hg=ZY2yPpWXI9 para ler a sua mensagem 


A Equipe do IQ Elite



---------------------------------------------------------------------------
Esta mensagem foi enviada para reply@reply.github.com. Se não quiser continuar recebendo estes emails de IQ Elite, clique por favor neste link: a.iqelite.com/common/unsubscribe/?code=1bcec12e&email=reply@reply.github.com.&hg=ZY2yPpWXI9 IQ Elite é um serviço com sede principal em: C/ Gran De Gràcia 15, 2a 1a, 08012 Barcelona, Espanha.
---------------------------------------------------------------------------

**Comment by walkeralencar** [comment]
Olá nfephp-org/nfephp,
Uma mensagem de walkeralencar foi deixada no IQ Elite para você. 
Clique aqui a.iqelite.com/j/S4mBgL/2sc/?hg=t56S1Bxd4Y para ler a sua mensagem 


A Equipe do IQ Elite



---------------------------------------------------------------------------
Esta mensagem foi enviada para reply@reply.github.com. Se não quiser continuar recebendo estes emails de IQ Elite, clique por favor neste link: a.iqelite.com/common/unsubscribe/?code=44539927&email=reply@reply.github.com.&hg=t56S1Bxd4Y IQ Elite é um serviço com sede principal em: C/ Gran De Gràcia 15, 2a 1a, 08012 Barcelona, Espanha.
---------------------------------------------------------------------------

**Comment by walkeralencar** [comment]
Olá nfephp-org/nfephp,
Uma mensagem de walkeralencar foi deixada no IQ Elite para você. 
Clique aqui a.iqelite.com/j/S4mBgL/hf4/?hg=ZY2yPpWXI9 para ler a sua mensagem 


A Equipe do IQ Elite



---------------------------------------------------------------------------
Esta mensagem foi enviada para reply@reply.github.com. Se não quiser continuar recebendo estes emails de IQ Elite, clique por favor neste link: a.iqelite.com/common/unsubscribe/?code=193dab49&email=reply@reply.github.com.&hg=ZY2yPpWXI9 IQ Elite é um serviço com sede principal em: C/ Gran De Gràcia 15, 2a 1a, 08012 Barcelona, Espanha.
---------------------------------------------------------------------------

**Comment by walkeralencar** [comment]
Olá nfephp-org/nfephp,
Uma mensagem de walkeralencar foi deixada no IQ Elite para você. 
Clique aqui a.iqelite.com/j/S4mBgL/3t0/?hg=BamJE5f20T para ler a sua mensagem 


A Equipe do IQ Elite



---------------------------------------------------------------------------
Esta mensagem foi enviada para reply@reply.github.com. Se não quiser continuar recebendo estes emails de IQ Elite, clique por favor neste link: a.iqelite.com/common/unsubscribe/?code=5eae43f9&email=reply@reply.github.com.&hg=BamJE5f20T IQ Elite é um serviço com sede principal em: C/ Gran De Gràcia 15, 2a 1a, 08012 Barcelona, Espanha.
---------------------------------------------------------------------------

**Comment by walkeralencar** [comment]
Olá nfephp-org/nfephp,
Uma mensagem de walkeralencar foi deixada no IQ Elite para você. 
Clique aqui a.iqelite.com/j/S4mBgL/edq/?hg=JYyGavdIul para ler a sua mensagem 


A Equipe do IQ Elite



---------------------------------------------------------------------------
Esta mensagem foi enviada para reply@reply.github.com. Se não quiser continuar recebendo estes emails de IQ Elite, clique por favor neste link: a.iqelite.com/common/unsubscribe/?code=db4b7735&email=reply@reply.github.com.&hg=JYyGavdIul IQ Elite é um serviço com sede principal em: C/ Gran De Gràcia 15, 2a 1a, 08012 Barcelona, Espanha.
---------------------------------------------------------------------------

**Comment by walkeralencar** [comment]
Olá nfephp-org/nfephp,
Uma mensagem de walkeralencar foi deixada no IQ Elite para você. 
Clique aqui a.iqelite.com/j/S4mBgL/o4m/?hg=JYyGavdIul para ler a sua mensagem 


A Equipe do IQ Elite



---------------------------------------------------------------------------
Esta mensagem foi enviada para reply@reply.github.com. Se não quiser continuar recebendo estes emails de IQ Elite, clique por favor neste link: a.iqelite.com/common/unsubscribe/?code=23cad3f6&email=reply@reply.github.com.&hg=JYyGavdIul IQ Elite é um serviço com sede principal em: C/ Gran De Gràcia 15, 2a 1a, 08012 Barcelona, Espanha.
---------------------------------------------------------------------------

**Comment by walkeralencar** [comment]
Olá nfephp-org/nfephp,
Uma mensagem de walkeralencar foi deixada no IQ Elite para você. 
Clique aqui a.iqelite.com/j/S4mBgL/b2j/?hg=SAMZnyUK6d para ler a sua mensagem 


A Equipe do IQ Elite



---------------------------------------------------------------------------
Esta mensagem foi enviada para reply@reply.github.com. Se não quiser continuar recebendo estes emails de IQ Elite, clique por favor neste link: a.iqelite.com/common/unsubscribe/?code=e276ce4e&email=reply@reply.github.com.&hg=SAMZnyUK6d IQ Elite é um serviço com sede principal em: C/ Gran De Gràcia 15, 2a 1a, 08012 Barcelona, Espanha.
---------------------------------------------------------------------------

**Comment by walkeralencar** [comment]
Olá,

Walker de Alencar  começou a usar IQ Elite. Ele escreveu-lhe uma mensagem. 

Para ler a mensagem antes de expirar, basta clicar neste link: a.iqelite.com/entry/new_message/343a9f6efc620a9f6c604b7aa1fc2d3fda9e1f544b80bfb/320c612f7502e515151825160bd91a8905f587b8266906d668aa9a8588260c483b0c5cb7cb6585f75bd67a8906ecb5867a890587b90829060b7cb51515151515151585851897b67c5c4669060a8587b91b7c45160cb589091cb58c320c612f75044d3e22edb35af44b80bfb/?hg=b87uHidGTj

Leia a sua mensagem antes que expire!            

Atenciosamente, 
 Equipe IQ Elite



---------------------------------------------------------------------------
Esta mensagem foi enviada para reply@reply.github.com. Se não quiser continuar recebendo estes emails de IQ Elite, clique por favor neste link: a.iqelite.com/common/unsubscribe/?code=23cad3f6&email=reply@reply.github.com.&hg=b87uHidGTj IQ Elite é um serviço com sede principal em: C/ Gran De Gràcia 15, 2a 1a, 08012 Barcelona, Espanha.
---------------------------------------------------------------------------

**Comment by walkeralencar** [comment]
Olá,

Walker de Alencar  começou a usar IQ Elite. Ele escreveu-lhe uma mensagem. 

Para ler a mensagem antes de expirar, basta clicar neste link: a.iqelite.com/entry/new_message/343a9f6efc620a9f6c604b7aa1fc2d3fda9e1f544b80bfb/320c612f7502e515151825160bd90667459b7b0a9b6897b52bea9c46652cb91b66d52ccbd52b65174586ebebebd6ea88983c47491a85f9060b7cb515151515151515858518ab7cb59b0af9060a8587b91b7c45160cb589091cb58c320c612f75044d3e22edb35af44b80bfb/?hg=nEvjWM14Is

Leia a sua mensagem antes que expire!            

Atenciosamente, 
 Equipe IQ Elite



---------------------------------------------------------------------------
Esta mensagem foi enviada para reply@reply.github.com. Se não quiser continuar recebendo estes emails de IQ Elite, clique por favor neste link: a.iqelite.com/common/unsubscribe/?code=db4b7735&email=reply@reply.github.com.&hg=nEvjWM14Is IQ Elite é um serviço com sede principal em: C/ Gran De Gràcia 15, 2a 1a, 08012 Barcelona, Espanha.
---------------------------------------------------------------------------

**Comment by walkeralencar** [comment]
Olá,

Walker de Alencar  começou a usar IQ Elite. Ele escreveu-lhe uma mensagem. 

Para ler a mensagem antes de expirar, basta clicar neste link: a.iqelite.com/entry/new_message/343a9f6efc620a9f6c604b7aa1fc2d3fda9e1f544b80bfb/320c612f7502e515151825160bd9067bd7cc5af75cb67b0b675b667c5b65f51516d7b905f7cbd7491a8747b7ccb826d91b67cb7b659c49060b7cb51515151515151585851907482898ab69060a8587b91b7c45160cb589091cb58c320c612f75044d3e22edb35af44b80bfb/?hg=pWstGijTxn

Leia a sua mensagem antes que expire!            

Atenciosamente, 
 Equipe IQ Elite



---------------------------------------------------------------------------
Esta mensagem foi enviada para reply@reply.github.com. Se não quiser continuar recebendo estes emails de IQ Elite, clique por favor neste link: a.iqelite.com/common/unsubscribe/?code=1bcec12e&email=reply@reply.github.com.&hg=pWstGijTxn IQ Elite é um serviço com sede principal em: C/ Gran De Gràcia 15, 2a 1a, 08012 Barcelona, Espanha.
---------------------------------------------------------------------------

**Comment by tonicospinelli** [comment]
@walkeralencar acho que você cadastrou um email errado nessa parada :stuck_out_tongue:

**Comment by walkeralencar** [comment]
Cara esse IQLite já me matou de raiva... achei que era uma coisa, quando aceitei ele pegar meus contatos, o fela mandou msgs pra todos meus contatos sem minha autorização.

**Comment by walkeralencar** [comment]
Olá,

O seu amigo(a) Walker de Alencar enviou-lhe uma mensagem há 36h dias, e que ainda não foi lida.

Dentro de 24 horas a mensagem será apagada.

Se você tem curiosidade em saber o que Walker de Alencar escreveu, clique aqui: a.iqelite.com/entry/new_message/343a9f6efc620a9f6c604b7aa1fc2d3fda9e1f544b80bfb/320c612f7502e515151825160bd91a8905f587b8266906d668aa9a8588260c483b0c5cb7cb6585f75bd67a8906ecb5867a890587b90829060b7cb51515151515151585851897b67c5c4669060a8587b91b7c45160cb589091cb58c320c612f75044d3e22edb35af44b80bfb/?hg=7YvnsoELSW            

Atenciosamente, 
 Equipe IQ Elite



---------------------------------------------------------------------------
Esta mensagem foi enviada para reply@reply.github.com. Se não quiser continuar recebendo estes emails de IQ Elite, clique por favor neste link: a.iqelite.com/common/unsubscribe/?code=23cad3f6&email=reply@reply.github.com.&hg=7YvnsoELSW IQ Elite é um serviço com sede principal em: C/ Gran De Gràcia 15, 2a 1a, 08012 Barcelona, Espanha.
---------------------------------------------------------------------------

**Comment by walkeralencar** [comment]
Olá,

O seu amigo(a) Walker de Alencar enviou-lhe uma mensagem há 36h dias, e que ainda não foi lida.

Dentro de 24 horas a mensagem será apagada.

Se você tem curiosidade em saber o que Walker de Alencar escreveu, clique aqui: a.iqelite.com/entry/new_message/343a9f6efc620a9f6c604b7aa1fc2d3fda9e1f544b80bfb/320c612f7502e515151825160bd90667459b7b0a9b6897b52bea9c46652cb91b66d52ccbd52b65174586ebebebd6ea88983c47491a85f9060b7cb515151515151515858518ab7cb59b0af9060a8587b91b7c45160cb589091cb58c320c612f75044d3e22edb35af44b80bfb/?hg=i37O14Kk0Y            

Atenciosamente, 
 Equipe IQ Elite



---------------------------------------------------------------------------
Esta mensagem foi enviada para reply@reply.github.com. Se não quiser continuar recebendo estes emails de IQ Elite, clique por favor neste link: a.iqelite.com/common/unsubscribe/?code=db4b7735&email=reply@reply.github.com.&hg=i37O14Kk0Y IQ Elite é um serviço com sede principal em: C/ Gran De Gràcia 15, 2a 1a, 08012 Barcelona, Espanha.
---------------------------------------------------------------------------

**Comment by walkeralencar** [comment]
Olá,

O seu amigo(a) Walker de Alencar enviou-lhe uma mensagem há 36h dias, e que ainda não foi lida.

Dentro de 24 horas a mensagem será apagada.

Se você tem curiosidade em saber o que Walker de Alencar escreveu, clique aqui: a.iqelite.com/entry/new_message/343a9f6efc620a9f6c604b7aa1fc2d3fda9e1f544b80bfb/320c612f7502e515151825160bd9067bd7cc5af75cb67b0b675b667c5b65f51516d7b905f7cbd7491a8747b7ccb826d91b67cb7b659c49060b7cb51515151515151585851907482898ab69060a8587b91b7c45160cb589091cb58c320c612f75044d3e22edb35af44b80bfb/?hg=an0qC1Dsp5            

Atenciosamente, 
 Equipe IQ Elite



---------------------------------------------------------------------------
Esta mensagem foi enviada para reply@reply.github.com. Se não quiser continuar recebendo estes emails de IQ Elite, clique por favor neste link: a.iqelite.com/common/unsubscribe/?code=1bcec12e&email=reply@reply.github.com.&hg=an0qC1Dsp5 IQ Elite é um serviço com sede principal em: C/ Gran De Gràcia 15, 2a 1a, 08012 Barcelona, Espanha.
---------------------------------------------------------------------------

**Comment by walkeralencar** [comment]
Olá,

Tem uma mensagem não lida do(a) seu/sua amigo(a) à sua espera. 

Clique aqui para ler agora a sua mensagem: a.iqelite.com/j/S4mBgL/2sc/?hg=9ScGwpHY1b
            

Atenciosamente, 
 Equipe IQ Elite



---------------------------------------------------------------------------
Esta mensagem foi enviada para reply@reply.github.com. Se não quiser continuar recebendo estes emails de IQ Elite, clique por favor neste link: a.iqelite.com/common/unsubscribe/?code=44539927&email=reply@reply.github.com.&hg=9ScGwpHY1b IQ Elite é um serviço com sede principal em: C/ Gran De Gràcia 15, 2a 1a, 08012 Barcelona, Espanha.
---------------------------------------------------------------------------

**Comment by walkeralencar** [comment]
Olá,

Tem uma mensagem não lida do(a) seu/sua amigo(a) à sua espera. 

Clique aqui para ler agora a sua mensagem: a.iqelite.com/j/S4mBgL/hf4/?hg=Ty4zK6CYSj
            

Atenciosamente, 
 Equipe IQ Elite



---------------------------------------------------------------------------
Esta mensagem foi enviada para reply@reply.github.com. Se não quiser continuar recebendo estes emails de IQ Elite, clique por favor neste link: a.iqelite.com/common/unsubscribe/?code=193dab49&email=reply@reply.github.com.&hg=Ty4zK6CYSj IQ Elite é um serviço com sede principal em: C/ Gran De Gràcia 15, 2a 1a, 08012 Barcelona, Espanha.
---------------------------------------------------------------------------

**Comment by walkeralencar** [comment]
Olá,

Tem uma mensagem não lida do(a) seu/sua amigo(a) à sua espera. 

Clique aqui para ler agora a sua mensagem: a.iqelite.com/j/S4mBgL/3t0/?hg=AdxNH6LV28
            

Atenciosamente, 
 Equipe IQ Elite



---------------------------------------------------------------------------
Esta mensagem foi enviada para reply@reply.github.com. Se não quiser continuar recebendo estes emails de IQ Elite, clique por favor neste link: a.iqelite.com/common/unsubscribe/?code=5eae43f9&email=reply@reply.github.com.&hg=AdxNH6LV28 IQ Elite é um serviço com sede principal em: C/ Gran De Gràcia 15, 2a 1a, 08012 Barcelona, Espanha.
---------------------------------------------------------------------------

**Comment by walkeralencar** [comment]
Olá,

Tem uma mensagem não lida do(a) seu/sua amigo(a) à sua espera. 

Clique aqui para ler agora a sua mensagem: a.iqelite.com/j/S4mBgL/b2j/?hg=nLSGP9m2d6
            

Atenciosamente, 
 Equipe IQ Elite



---------------------------------------------------------------------------
Esta mensagem foi enviada para reply@reply.github.com. Se não quiser continuar recebendo estes emails de IQ Elite, clique por favor neste link: a.iqelite.com/common/unsubscribe/?code=e276ce4e&email=reply@reply.github.com.&hg=nLSGP9m2d6 IQ Elite é um serviço com sede principal em: C/ Gran De Gràcia 15, 2a 1a, 08012 Barcelona, Espanha.
---------------------------------------------------------------------------
