### ISSUE TITLE
Função __cleanCerts() não disponível

### ISSUE THREAD

**Issue by taq** [nfephp-org/nfephp#277]
Olá.

Antes de mais nada, parabéns e obrigado pela iniciativa do projeto. Estou tentando utilizar o exemplo da NFsE disponilizado [aqui](https://github.com/nfephp-org/nfephp/blob/master/exemplos/NFSe/exemplosNFSe.php).

Antes de utilizar, tentei fazer o download da [última versão estável](https://github.com/nfephp-org/nfephp/downloads), conforme especificado na página inicial, mas não encontrei nada, então clonei oo repositório (**sem** utilizar a *develop*, conforme indicado, peguei o da *master*, que teoricamente é a de produção, certo?), e após configurar (e instalar o `NuSOAP`, etc), na hora que vou rodar o exemplo, recebo a seguinte mensagem:

```
PHP Fatal error:  Call to undefined method NFSePHPGinfes::__cleanCerts() in 
/var/www/html/fenix/lib/nfephp/libs/NFSe/NFSePHPGinfes.class.php on line 1218
```

Fui dar uma investigada, e esse método `__cleanCerts` é definido como protegido na classe [MDFeNFePHP](https://github.com/nfephp-org/nfephp/blob/master/libs/MDFe/MDFeNFePHP.class.php), porém, ela não está presente na classe [NFSePHPGinfes](https://github.com/nfephp-org/nfephp/blob/master/libs/NFSe/NFSePHPGinfes.class.php), como demonstrado na mensagem de erro, e também não está em nenhuma das que ela herda, que são [ToolsNFePHP](https://github.com/nfephp-org/nfephp/blob/master/libs/NFe/ToolsNFePHP.class.php) e [CommonNFePHP](https://github.com/nfephp-org/nfephp/blob/master/libs/Common/CommonNFePHP.class.php). Assim, não estou entendendo como alguém pode estar rodando esse código sem receber esse erro.

Alguém pode dar uma luz?

Obrigado.

**Comment by taq** [comment]
Detalhe: eu dei uma olhada também na branch *develop*, mas também está do mesmo jeito.

**Comment by robmachado** [comment]
Eustáquio;

Os aplicativos NFSe que estão ai não são funcionais, eles tem erros e
muitas falhas de estrutura, são apenas contribuições de colaboradores e não
existe nenhum "responsável" ativo cuidando dessas classes.

Servem apenas como referencia

Roberto

**Comment by taq** [comment]
Ué, mas quer dizer que aquele exemplo lá o cara colocou de "alegre", não roda, foi só escrito e nunca na vida rodou? E essas classes que estão no projeto foram feitas sem teste nem nada, como no caso desse método que não está disponível na classe? :-(

Desculpe, mas fiquei confuso aqui, tem alguma parte do projeto que está funcionando ou realmente estão só como "códigos de intenção"?

Obrigado!

**Comment by robmachado** [comment]
Vamos lá ....

O que funciona e o que os colaboradores REAIS e eu usamos e compartinhamos.

NFe
NFCe
CTe
MDFe

A parte de NFSe, eu não uso, não existe niguêm no grupo querendo colaborar
com isso e pior NÃO EXISTE um padrão !!!! portanto essas coisas estão ai
por que sempre tem alguém perguntando COMO ISSO ??? COMO AQUILO ??? com as
notas das prefeituras e para um programador experiente mesmo esses
rascunhos são de alguma ajuda.

Lembre-se que isso não é um código pago, todo o trabalho é feito em horas
vagas, ou seja deixo de descansar nos fins de semana para colaborar, mas
não tenho como (nem meios, nem tempo e nem uma autorização para testar NFSe)

Na NFSe são mais de 20 modelos diferentes com mais de uma centena de
variações, então ninguém quer por a mão nisso.

Roberto

**Comment by taq** [comment]
Obrigado pela resposta!

Então vou ficar na mão mesmo com o NFsE. :-( Mas putz, pensei que pelo menos o cara tivesse rodado o código dele, já que está ali publicado. Podia por uma nota de "não funcional" ali e deixar mais claro na documentação sobre isso.

Sobre o lance de não ser pago, etc, esquenta não que faz uns 20 anos que trabalho e colaboro com Software Livre e tenho uma idéia de como funciona. ;-)

Se eu conseguir evoluir alguma coisa sobre NFsE eu coloco alguma novidade aí pela web. A minha linguagem de preferência é Ruby, e tenho visto algumas *gems* que a galera está utilizando (não vi rodando, ainda) para NFsE. Em PHP ia ficar bom porque o cliente que estou tem o software nessa linguagem, mas vamo que vamo.

**Comment by robmachado** [comment]
Eu e o Fabio Ananias talvez consigamos fazer alguns testes sexta-feira se
quiser se juntar a nós
Como é inicio de ano tenho algum tempo mais livre

Roberto

**Comment by taq** [comment]
Da NFsE? O certo seria dar uma revisada ali, botar uns testes unitários ... pra pelo menos deixar funcional mesmo antes de preocupar com os padrões etc ...

**Comment by robmachado** [comment]
A ideia seria pegar um caso especifico e montar um classe funcional para
esse caso especifico. Quanto a testes funcionais para isso é necessário o
certificado A1 de um emissor autorizado (o que eu não tenho para
prefeituras somente lido com industrias).

Teste unitários (phpunit) podem fazer testes apenas com "simulacros" (moks)
e unca poderão fazer testes reais via SOAP

Roberto

**Comment by taq** [comment]
Menciono os testes para pelo menos esses tipos de erros que eu peguei aqui, uma classe acessando um método que não está disponível/existe para ela, antes de chegar na questão de padrões, certificados, etc.

**Comment by robmachado** [comment]
Na refatoração da classe para a versão 4.0 isso esta sendo separado veja em
https://github.com/nfephp-org/nfephp/tree/develop/libs/Common

Estão sendo montadas sub classes para uso do certificado que todas as
outras classes poderão usar, dentre outras

Roberto

**Comment by taq** [comment]
Ah, legal!

**Comment by robmachado** [comment]
Eustáquio;

Junte-se ao grupo NFePHP do google e possivelmente faremos um hangout na
sexta para tratar esse assunto

Roberto

**Comment by mariopacio** [comment]
robmachado, troque __cleanCerts() por pCleanCerts() que dá certo.
Abs.

**Comment by taq** [comment]
Obrigado pela dica, @mariopacio , mas pela urgência do cliente, eu desisti de usar o projeto. Abraço!
