### ISSUE TITLE
duvida no processo de envio da nfe processo "autoriza"

### ISSUE THREAD

**Issue by kemuelcabral** [nfephp-org/nfephp#280]
bom dia

estou tendo problema no retorno do xml, recebendo mensagem "erro 225 rejeicao falha no schema xml do lote"

o arquivo xml em si, nao apresenta erros, pois ja validei no emissor do sefaz de sao paulo e validei no site do sefaz do rs tambem.
acredito que esteja acontecendo algum erro na montagem do lote para envio pelo processo "autoriza". sera que vcs podem me ajudar?

ats

kemuel cabral

**Comment by robmachado** [comment]
*Use o grupo para pedir auxilio e não o GitHub !!!*

Eu uso o sistema e não tenho erros então pode ser algo ai ... mas com essa
informação não é possível avaliar.

Antes de perguntar verifique o soapDebug e faça um debug em seu ambiente de
teste com xdebug

Roberto

**Comment by kemuelcabral** [comment]
bom dia
so para me ajudar, nao estou tendo problemas com o xml, ele valina normalmente no aplicativo do sefaz e no site do sefaz do RS.
o debugo do soap tambem esta normal.

o problema é quando consulto a nfe(situacao) aparece a mensagem rejeitao 225 falha no xml do lote

alguma ideia.

obrigado

**Comment by guicalabria** [comment]
Se você postar o XML de envio facilitará o trabalho.

Em 13 de janeiro de 2015 11:15, kemuelcabral <notifications@github.com>
escreveu:

**Comment by kemuelcabral** [comment]
ola

segue abaixo

obrigado

<?xml version="1.0" encoding="utf-8"?>
<NFe xmlns="http://www.portalfiscal.inf.br/nfe"><infNFe Id="NFe35150106085437000151550010000003441495350431" versao="3.10"><ide><cUF>35</cUF><cNF>49535043</cNF><natOp>Venda</natOp><indPag>1</indPag><mod>55</mod><serie>1</serie><nNF>344</nNF><dhEmi>2015-01-12T03:01:38-02:00</dhEmi><dhSaiEnt>2015-01-12T03:01:38-02:00</dhSaiEnt><tpNF>1</tpNF><idDest>1</idDest><cMunFG>3507506</cMunFG><tpImp>1</tpImp><tpEmis>1</tpEmis><cDV>1</cDV><tpAmb>1</tpAmb><finNFe>1</finNFe><indFinal>1</indFinal><indPres>1</indPres><procEmi>0</procEmi><verProc>3.10.29</verProc></ide><emit><CNPJ>06085437000151</CNPJ><xNome>Malaspina Comercio De Moveis E Utensilios Ltda Me</xNome><xFant>Malaspina Comercio De Moveis E Utensilios Ltda Me</xFant><enderEmit><xLgr>AV LEONARDO VILLAS BOAS</xLgr><nro>2262</nro><xCpl>nao informado</xCpl><xBairro>VILA NOVA BOTUCATU</xBairro><cMun>3507506</cMun><xMun>Botucatu</xMun><UF>SP</UF><CEP>18608227</CEP><cPais>1058</cPais><xPais>BRASIL</xPais><fone>1433541568</fone></enderEmit><IE>224094052111</IE><IM>28860</IM><CNAE>4754701</CNAE><CRT>1</CRT></emit><dest><CPF>07801993837</CPF><xNome>KEMUEL DE GOUVEA CABRAL</xNome><enderDest><xLgr>RUA TERCILIA BERNARDI CRUZ</xLgr><nro>711</nro><xBairro>RES BERNARDI</xBairro><cMun>3525300</cMun><xMun>Jau</xMun><UF>SP</UF><CEP>17210838</CEP><cPais>1058</cPais><xPais>BRASIL</xPais><fone>1434164048</fone></enderDest><indIEDest>9</indIEDest><email>nao informado</email></dest><det nItem="1"><prod><cProd>9</cProd><cEAN/><xProd>TESTE CABRAL</xProd><NCM>02074100</NCM><CFOP>5102</CFOP><uCom>Peca</uCom><qCom>1.0000</qCom><vUnCom>1.0000</vUnCom><vProd>1.00</vProd><cEANTrib/><uTrib>Peca</uTrib><qTrib>1.0000</qTrib><vUnTrib>1.0000</vUnTrib><indTot>1</indTot></prod><imposto><ICMS><ICMSSN102><orig>0</orig><CSOSN>102</CSOSN></ICMSSN102></ICMS><PIS><PISNT><CST>08</CST></PISNT></PIS><COFINS><COFINSNT><CST>08</CST></COFINSNT></COFINS></imposto></det><total><ICMSTot><vBC>0.00</vBC><vICMS>0.00</vICMS><vICMSDeson>0.00</vICMSDeson><vBCST>0.00</vBCST><vST>0.00</vST><vProd>1.00</vProd><vFrete>0.00</vFrete><vSeg>0.00</vSeg><vDesc>0.00</vDesc><vII>0.00</vII><vIPI>0.00</vIPI><vPIS>0.00</vPIS><vCOFINS>0.00</vCOFINS><vOutro>0.00</vOutro><vNF>1.00</vNF></ICMSTot></total><transp><modFrete>9</modFrete></transp><cobr><fat><nFat>09011584414</nFat><vOrig>1.00</vOrig><vLiq>1.00</vLiq></fat><dup><nDup>09011584414-1</nDup><dVenc>2015-01-09</dVenc><vDup>1.00</vDup></dup></cobr><infAdic><infCpl>[EMPRESA OPTANTE PELO SIMPLES NACIONAL][No. do pedido : 09011584414][Vlr. aprox. tributos conf. IBPT :R$ 0.37][DESCONTOS CONCEDIDOS: R$ 0.00]</infCpl></infAdic></infNFe><Signature xmlns="http://www.w3.org/2000/09/xmldsig#"><SignedInfo><CanonicalizationMethod Algorithm="http://www.w3.org/TR/2001/REC-xml-c14n-20010315"/><SignatureMethod Algorithm="http://www.w3.org/2000/09/xmldsig#rsa-sha1"/><Reference URI="#NFe35150106085437000151550010000003441495350431"><Transforms><Transform Algorithm="http://www.w3.org/2000/09/xmldsig#enveloped-signature"/><Transform Algorithm="http://www.w3.org/TR/2001/REC-xml-c14n-20010315"/></Transforms><DigestMethod Algorithm="http://www.w3.org/2000/09/xmldsig#sha1"/><DigestValue>8ornDbNlnIBTIDxT+iJvgC2Enj4=</DigestValue></Reference></SignedInfo><SignatureValue>hnI72VN15VjJUaQ0fCgo0mtgooJ1tFa5ag5UdznDNIz5/a/cUTR26JQ6WbbW8ojWCxceUZBnD2ENhIBsUwY9sFSlMDYHP4me1v0bhHnLQJAugC0hOtnycJ2PJR+wJKLLvZ0aulcoPb/B8xwkfjIFntCuiXeHvj+QVfT8FNI5XbyPBLlM8U4dxZtLVN1aeur/W1IWVfR+AqrY9nyRQsWoO1hi9+d6MIm5VbMqa0o1W3AuPzgx472FqD2bu4Ke+oCxVdZVS1zGtGMEE+buFIyHNCNfeInvQf2yt7uMJOHDaBvhUkbjamqnjK6zPFA4IZrdmXsRacEw5/x7n5yuwbUmQA==</SignatureValue><KeyInfo><X509Data><X509Certificate>MIIIezCCBmOgAwIBAgIQA+wgovI0E/ZmIJzQ8NDWADANBgkqhkiG9w0BAQsFADB4MQswCQYDVQQGEwJCUjETMBEGA1UEChMKSUNQLUJyYXNpbDE2MDQGA1UECxMtU2VjcmV0YXJpYSBkYSBSZWNlaXRhIEZlZGVyYWwgZG8gQnJhc2lsIC0gUkZCMRwwGgYDVQQDExNBQyBDZXJ0aXNpZ24gUkZCIEc0MB4XDTE0MTEyNDAwMDAwMFoXDTE1MTEyMzIzNTk1OVowggEVMQswCQYDVQQGEwJCUjETMBEGA1UEChQKSUNQLUJyYXNpbDELMAkGA1UECBMCU1AxETAPBgNVBAcUCGJvdHVjYXR1MTYwNAYDVQQLFC1TZWNyZXRhcmlhIGRhIFJlY2VpdGEgRmVkZXJhbCBkbyBCcmFzaWwgLSBSRkIxFjAUBgNVBAsUDVJGQiBlLUNOUEogQTExNjA0BgNVBAsULUF1dGVudGljYWRvIHBvciBBdXRvcmlkYWRlIGRlIFJlZ2lzdHJvIENOQiBTUDFJMEcGA1UEAxNATUFMQVNQSU5BIENPTUVSQ0lPIERFIE1PVkVJUyBFIFVURU5TSUxJT1MgTFREQSBNRTowNjA4NTQzNzAwMDE1MTCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBANI24sBY7V64QW/mqoQaHuCxJ6HMro8wUllAVKwjMO2YZ6OlUSCnitiVQ+nCIuhUpFnf+3TYz2J024Ua+q0Z4bV0L93xAhRPf/SnXHteuAz27dBagLSjEtWKghD7w1LmLNS++vKyKCDDUH1o84Tpdat6rAcHIYYocDi7QmBtQxmjsZNnVdvgQBpl8SA0IPwPLn1jNi8P25l4rfH5WDK5wpyRoT3elIwguo+eX7J0DNogrQ53Ke0CJZY5esFQG2eNMl3FvfVdUOpuMVwgzhD1CsP4Sc6GwtoDIEvGoB81V511Xi1V0GfMBAUdFDWtJ7FHyZbqiycWBAjNVEzZebuW4IkCAwEAAaOCA2AwggNcMIHFBgNVHREEgb0wgbqgPQYFYEwBAwSgNAQyMTMxMDE5ODIzMDI0OTY3Mzg5NDAwMDAwMDAwMDAwMDAwMDAwMDMzNDYzMzUzc3NwU1CgIQYFYEwBAwKgGAQWUkFGQUVMIFRJQUdPIE1BTEFTUElOQaAZBgVgTAEDA6AQBA4wNjA4NTQzNzAwMDE1MaAXBgVgTAEDB6AOBAwwMDAwMDAwMDAwMDCBImtlbXVlbGVkYWdtYXJAa2VtdWVsZWRhZ21hci5jb20uYnIwCQYDVR0TBAIwADAfBgNVHSMEGDAWgBQukerWbeWyWYLcOIUpdjQWVjzQPjAOBgNVHQ8BAf8EBAMCBeAwfwYDVR0gBHgwdjB0BgZgTAECAQwwajBoBggrBgEFBQcCARZcaHR0cDovL2ljcC1icmFzaWwuY2VydGlzaWduLmNvbS5ici9yZXBvc2l0b3Jpby9kcGMvQUNfQ2VydGlzaWduX1JGQi9EUENfQUNfQ2VydGlzaWduX1JGQi5wZGYwggEWBgNVHR8EggENMIIBCTBXoFWgU4ZRaHR0cDovL2ljcC1icmFzaWwuY2VydGlzaWduLmNvbS5ici9yZXBvc2l0b3Jpby9sY3IvQUNDZXJ0aXNpZ25SRkJHNC9MYXRlc3RDUkwuY3JsMFagVKBShlBodHRwOi8vaWNwLWJyYXNpbC5vdXRyYWxjci5jb20uYnIvcmVwb3NpdG9yaW8vbGNyL0FDQ2VydGlzaWduUkZCRzQvTGF0ZXN0Q1JMLmNybDBWoFSgUoZQaHR0cDovL3JlcG9zaXRvcmlvLmljcGJyYXNpbC5nb3YuYnIvbGNyL0NlcnRpc2lnbi9BQ0NlcnRpc2lnblJGQkc0L0xhdGVzdENSTC5jcmwwHQYDVR0lBBYwFAYIKwYBBQUHAwIGCCsGAQUFBwMEMIGbBggrBgEFBQcBAQSBjjCBizBfBggrBgEFBQcwAoZTaHR0cDovL2ljcC1icmFzaWwuY2VydGlzaWduLmNvbS5ici9yZXBvc2l0b3Jpby9jZXJ0aWZpY2Fkb3MvQUNfQ2VydGlzaWduX1JGQl9HNC5wN2MwKAYIKwYBBQUHMAGGHGh0dHA6Ly9vY3NwLmNlcnRpc2lnbi5jb20uYnIwDQYJKoZIhvcNAQELBQADggIBABZ7vCHDi2CMQmbtuGmn4EVSP5MjNarJLxb0SCmof/oIk0VnT3wIDAzlAxxjT+OPIp7oTPW7z82esqTaDQ/vO4+jab8HzMXHRxTlUMVP7vbysEIlnKKHTSCqRBlzK4c7Yz1wa+qIanmTg0IcdjnFRFseCQkyp+TvjLMMDGyh7mw60vE6EPDj9+L2MAQbLy7WNeXaHVQBYOfME/ejka6L0Hu5MWE23+O0ZCmlSEzhRRMrEJzeF69M5+GfZHeMTBHcrWrogFeA91A/O0WmnlIFBJDXXDvRUUGQyEnhgVmklvoZ9ceNcgw33NhOTb2veN5ZKsfcjzC01zCguL4Z2GFMz0FjIHg1Zq7MkHS0DpsQfmFBLTtxmV8Zk66JtacznNLZXEcDXNQU/WqntkuSM27O8BtbhCu0BqhbCHcGehWc/7TgqeeDRIMubtydiWRvuvNxUMc53aO2kIIwKaIsV8o7Vx4DYeNSQ0Hdn+0wjWP4VMilS9Y0dXZmY4MhzSnTg8/pLzE0//pQJroGpNXUWuW3HA+xfgCIy1QW9zjXRKicKpH1fYaozrq/vai0GUng+WKj5lbCRy0EHeKwYqn8ziMSl7z/NU353nhLBGW9vHBN2bpNQgtETA/1u49vCBEClnJKm1deyv1eK6D0nyuz6U/N5nVaLsU2SttR2OIiPnIECzhk</X509Certificate></X509Data></KeyInfo></Signature></NFe>

**Comment by kemuelcabral** [comment]
nao tem um email que eu possa te enviar o xml?

no aguardo

**Comment by kemuelcabral** [comment]
ola

segue anexo

**Comment by guicalabria** [comment]
Acesse:

https://groups.google.com/forum/#!forum/nfephp

envie por lá.

2015-01-13 11:38 GMT-02:00 kemuelcabral <notifications@github.com>:

**Comment by kemuelcabral** [comment]
ok ja enviei

obrigado
