### ISSUE TITLE
NFSeSP :: Implantação do novo layout da NFS-e a partir de 23/02/2015

### ISSUE THREAD

**Issue by tonicospinelli** [nfephp-org/nfephp#282]
@robmachado sabe se alguém está trabalhando em cima dessa [Notícia](http://nfpaulistana.prefeitura.sp.gov.br/artigo.asp?conteudo=Noticia01)?

**Comment by robmachado** [comment]
Não, tenho ajudado alguns colaboradores com NFSe mas não tem ninguém se
oferecendo para dar manutenção.

NFSe está orfão !!!

Roberto

**Comment by tonicospinelli** [comment]
:worried: 
Estou fazendo testes para entender o que a classe faz e em seguida veja essas novas atualizações

**Comment by robmachado** [comment]
@tonicospinelli  Qualquer melhoria deve ser feita em "Develop" preferencialmente e usando PSR-2, namespace, etc . Essas classes bem como todas as outras devem usar as classes novas para a comunicação SOAP, de preferencia Common/Soap/CurlSoap.php, é provável que seja necessário a montagem de métodos específicos nesses casos de NFSe pois existem diferenças no mecanismo de comunicação e na construção do "envelope", praticamente todas  os modelos de NFSe tem alguma diferença entre si (e são mais de 20 modelos) além que outras diferenças devido a especificidades de cada prefeitura (é medonho).

**Comment by tonicospinelli** [comment]
@robmachado pode deixar seguirei essa linha, mas por hora, farei para SP

**Comment by LUCASNDIAS** [comment]
@tonicospinelli como você vai fazer pra diferenciar os schemes de cada local? Estou fazendo pra BH e eles alteraram algumas coisas pra ficar mais próximo dos arquivos da Sefaz de MG, assim, não posso usar a que já está lá na pasta. Até padronizar, coloquei o arquivo xsd na pasta schemes/nfse/nfsebh.xsd. Pelo que já vi, a criação do XML da classe NFSePHP está bem próxima do que a PBH determina, tive que remover alguns elementos e adicionar outros pra ficar de acordo com o manual, mas está funcionando. A assinatura está apenas com algumas variáveis com nomes errados e não há declaração de diversas variáveis (já arrumei). Tive que atualizar bastante a validação. Estou agora testando o envio e, assim que tiver tudo certo e nos padrões, solicito pra add em develop!

**Comment by tonicospinelli** [comment]
@LUCASDIAS bacana cara, só tome cuidado para extender a classe NFSeSP e não fazer as alterações diretamente nela, até mesmo porque ela já pode estar funcionando para outras pessoas. Interessante seria criar uma class NFSeBH, como foi feito para SP :+1:

**Comment by LUCASNDIAS** [comment]
@tonicospinelli realmente, como eu achei que não estava funcional fiz alterações direto na NFSePHP. Não pensei que alguém estivesse usando. Vou acabar de testar e depois faço a extensão em NFSeBH e volto a outra pro original! 

Blz, vou manter este padrão. Obrigado!

**Comment by tonicospinelli** [comment]
:+1: beleza @LUCASNDIAS ficamos no aguardo
