### ISSUE TITLE
Não gera segunda página 

### ISSUE THREAD

**Issue by raphaelduartepinheiro** [nfephp-org/nfephp#285]
Quando a descrição do produto/serviço + informações adicionais dos dois primeiros itens na impressão paisagem são grandes demais, a rotina pItensDANFE não está conseguindo "lembrar" que precisa continuar do item onde parou na primeira página por falta de espaço, e desenhar a segunda página. 

Consegui simular com esse xml: http://pastebin.com/Cp3Uw82L

Eu ajustei a classe DanfeNFePHP.class.php, na função pItensDANFE, passando o $totPag como referência, e mais algumas modificações. Precisa só rodar o teste, e daí eu dou o pull-request.

**Comment by robmachado** [comment]
Alguém fez alterações (algum contribuidor) para seu caso especifico então
causou essas falhas.

Para corrigir acredito que precisa mudar pouco, vou fazer um "UPLOAD" em
develop dessa classe com as alterações a primeira parte do erro se deve as
margens configuradas em 10 mm onde poderiam ser 1 ou 2 apenas, o restante o
próprio drive de impressão ajusta na hora de imprimir.
Outros "problemas" estão no alinhamento dos campos TOP, LEFT e RIGHT mas
isso é mais questão de estética.

Roberto

**Comment by fmertins** [comment]
Olá, pode ter sido eu, mas lembro de ter realizado testes sobre "uma página VS duas páginas VS várias páginas" e era para estar tudo certo, mas não tenho certeza agora se testei com as informações adicionais, talvez testei apenas com a descrição.

A nossa classe do Danfe tem vááários números mágicos e é bem difícil e cansativo fazer melhorias dependendo do que precisar ser refatorado, principalmente se for layout :-/

Assim que conseguir tento ajudar, vou dar uma olhada no XML de exemplo, valeu!

**Comment by robmachado** [comment]
Fernando;

Eu subi uma classe ajustada. Quanto aos "números mágicos" sim tem algumas "mandracarias" eheheh 
mas isso em parte a devido a SEFAZ estabelecer formatos diferentes entre a primeira e as paginas posteriores. Mas o problema principal é que a classe necessita de uma refatoração, com redução da complexidade, atendimento a padrões. Como estou envolvido em fazer isso para a parte de certificados e comunicação não mexi ainda nisso.
Mas umas das primeiras coisas a fazer é passar a usar TCPDF no lugar do FPDF e com o uso do composer então a classe TCPDF estará na pasta vendor.
Será necessário reescrever boa parte dessa classe para tentar corrigir alguns desses problemas.

**Comment by robmachado** [comment]
@raphaelduartepinheiro Outra coisa é que nas informações complementares dos itens você está pondo uma novela 
Saida tributada pelo ICMS. Saida Tributada pelo IPI. Resolucao do Senado Federal no 13/12, Numero da FCI C8960F2E-F9CC-428E-93B5-7E2ACDBE26EF.
Quanto ao numero do FCI a classe já coloca isso sozinha

**Comment by fmertins** [comment]
@robmachado 
Maravilha, concordo plenamente! :-)
Também estou na correria, obrigado, abraços!

**Comment by robmachado** [comment]
@raphaelduartepinheiro Verifique como ficou agora !! já atualizei em master e develop

**Comment by raphaelduartepinheiro** [comment]
Aparentemente não. A modificação que fiz foi essa que acabei de citar. Dessa maneira funcionou aqui, mas não sei em quais erros mais pode implicar. Os testes estão cobrindo muitos casos? Já pensou em adicionar esse XML que passei nas fixtures de teste?
Valeu!

**Comment by tonicospinelli** [comment]
@robmachado de acordo com @raphaelduartepinheiro isso não funcionou como o esperado.

@raphaelduartepinheiro ainda não temos testes para Danfe, se quiser iniciar com a sua fixture, fique a vontade, pois o projeto é grande e nem todos dispõem de tempo hábil para fazer a cobertura. Tanto é que ainda a cobertura de código é baixa e precisamos de ajuda, agradeço se puder colaborar conosco.

Agora, @robmachado vi que é apenas mudança de margens, porém esse commit 360c5cf ainda faz sentido existir? 

Caso não faça sentido existir na codebase, para situações deste tipo, peço que *não* seja feito commits diretamente no `master`/`develop` isso pode fazer com que entre bugs sem pegarmos via pull request ou adicionar coisas que não resolvam o problema por completo.

Como o git é suficientemente flexível, podemos adotar o seguinte:
* Fork do projeto
* novo branch
* commit das alterações
* push do novo branch para seu fork
* quem precisa da alteração clona seu repo ou adiciona no remote `git remote add tonicospinelli git@github.com:tonicospinelli/nfephp.git``
* testa
* tudo OK, PR para nfephp-org/nfephp
* rola code review
* tudo OK, faremos merge

**Comment by raphaelduartepinheiro** [comment]
Beleza. Eu fiz a alteração da referência, removendo a necessidade de parâmetro no pItensDANFE e pCabecalhoDANFE. Subi a fixture também. Sobre o teste, farei em breve. As alterações agora estão na branch develop. Vamos pro PR.

**Comment by tonicospinelli** [comment]
opa... maravilha!!! vi o código... :+1:
