### ISSUE TITLE
getNFe :: Download NFe independente de confirmação pelo destinatario

### ISSUE THREAD

**Issue by roquebrasilia** [nfephp-org/nfephp#301]
@robmachado antes de mais nada esta de parabéns pela comunidade. Nota dez pela organização.

Estou realizando o procedimento de fazer download da NF-e e gerar o DANFE em pdf. 
O exemplo de realizar a criação do pdf apartir do xml já esta ok. Segui o exemplo do link http://www.brunoafonso.net/codigo-php-para-gerar-a-danfe/ .

Dei uma lida no documento "Nota Técnica 2012/002  - Manifestação do Destinatário" onde explica que e necessário a manifestação do destinatário para que possa ser realizado o download da NF-e através do método. getNFe.

Fiz o uso do método para as seguintes DANFE:

1) 53130501644731000132550150000279581948293930 retornou a msg =>  632 - Rejeicao: Solicitacao fora de prazo, a NF-e nao esta mais disponivel para download 

2) 53150101644731000132550150000548861643534573 retornou a msg => 633 - Rejeicao: NF-e indisponivel para download devido a ausencia de Manifestacao do Destinatario

Sendo assim como é que o site https://www.danfeonline.com.br/ consegue gerar as estas mesmas  DANFE em pdf???

Existe outra maneira de fazer o download da DANFE independente da situação da manifestação??? 

G Download da NF-e para uma determinada Chave de Acesso informada,
     * para as NF-e confirmadas pelo destinatário. As NFe baixadas serão salvas
     * na pasta de recebidas

**Comment by robmachado** [comment]
Rafael;

Isso foi muitas vezes discutido aqui até a exaustão ..... e esse assunto
sempre retorna. Mas vou te dar algumas AFIRMAÇÕES :

1 - Quem tem que mandar o xml para o destinatário é o emitente e isso via
email (tá na LEI);

2 - A SEFAZ não disponibiliza o download por nenhum webservice após 15 DIAS;

3 - O sistema atual (que permite baixar as notas manifestadas dentro desse
prazo)  irá ser DESLIGADO, devido ao mau uso;

4 - Um novo sistema entrou em operação que é o DistDFe mas também tem
restrições (veja a documentação);

5 - O webdanfe não monta o danfe com um xml da NF, veja que é necessário um
captcha. Ele usa a página da receita para burcar algumas informações e não
a NFe completa. Pega os dados suficientes para montar a DANFE;

6 - A DANFE não tem valor nenhum, não serve para nada, é inútil, sua função
 acaba com a entrega da mercadoria

7 - Eu não sei como o pegar os dados da pagina da receita !!!

Assunto encerrado !

Roberto
