### ISSUE TITLE
MDFe :: Novo serviço mdfeConsNaoEnc - 01/02/2015

### ISSUE THREAD

**Issue by psaraiva** [nfephp-org/nfephp#306]
Olá senhores.

Verifiquei o master e não encontrei ocorrência do serviço "mdfeConsNaoEnc" da nota técnica 2015/001 que entra em vigor no primeiro dia do próximo mês. Alguém está trabalhando (colaborando) nesse novo serviço.

Obrigado.

**Se não tiver ninguém, posso começar a desenvolver e ao concluir solicito "pull request".

**Comment by robmachado** [comment]
Pedro;

Acredito que não tenha ninguem mexendo nisso agora ... mas se for faze-lo
tenho 3 recomendações :

1 - na branch master apenas inclua o método e faça o mínimo de alterações
possível, mesmo que o código dê náuseas (como dá para mim);
2 - na branch develop é necessário a refatoração do código inteiro para
PSR-2, namespaces, php 5.6, usar classes comuns, etc., ai será necessário
um papo comigo.
3 - em qualquer dos casos abra um ISSUE para essa tarefa e de designe como
responsável, assim quem estiver fazendo ou necessitando disso poderá
acha-lo.

No demais, já agradeço sua ajuda
Abraço
Roberto

**Comment by psaraiva** [comment]
Beleza.

Vou desenvolver esse serviço e aplico os ajustes necessários conforme recomendado. Então apresento a solução.

Obrigado Roberto.
