### ISSUE TITLE
TODO: nfe v3.10 - branch master

### ISSUE THREAD

**Issue by rspadim** [nfephp-org/nfephp#307]
- daeventonfe -> todas funcoes com ->__ precisam ser alteradas
- imprtacao txt -> precisa atualizar (pullrequest a caminho)

precisa verificar os outros arquivos que geram pdf se nao esqueceram de alterar as funcoes ->__

**Comment by rspadim** [comment]
# grep "\->__" *
ConvertNFePHPOpc.class.php:            $ret=$this->__montaChaveXML($dom);
ConvertNFePHPOpc.class.php:        $cDV    = $ide->getElementsByTagName('cDV')->item(0)->nodeValue  = $this->__calculaDV($tempChave);
DaCancnfeNFePHP.class.php:              $this->__adicionaLogoPeloCnpj($this->aEnd['CNPJ']);
DaCancnfeNFePHP.class.php:              $this->__adicionaLogoPeloCnpj($this->aEnd['CPF']);
DaCancnfeNFePHP.class.php:        $y = $this->__headerCCe($x,$y,$pag,$situacao_externa);
DaCancnfeNFePHP.class.php:        $y = $this->__bodyCCe($x,$y+15);
DaCancnfeNFePHP.class.php:        $y = $this->__footerCCe($x,$y+$this->hPrint-20);
DaCancnfeNFePHP.class.php:        $this->__textBox($x,$y,$w,$h);
DaCancnfeNFePHP.class.php:        $this->__textBox($x,$y,$w,5,$texto,$aFont,'T','C',0,'');
DaCancnfeNFePHP.class.php:        $this->__textBox($x1,$y1,$tw,8,$texto,$aFont,'T','C',0,'');
DaCancnfeNFePHP.class.php:        $CEP = $this->__format($CEP,"#####-###");
DaCancnfeNFePHP.class.php:      $this->__textBox($x1,$y1-2,$tw,8,$texto,$aFont,'T','C',0,'');
DaCancnfeNFePHP.class.php:        $this->__textBox($x,$y,$w2,$h);
DaCancnfeNFePHP.class.php:        $this->__textBox($x,$y+2,$w2,8,'RepresentaÃ§Ã£o GrÃ¡fica de ProtCancNfe',$aFont,'T','C',0,'');
DaCancnfeNFePHP.class.php:        $this->__textBox($x,$y+7,$w2,8,'(Protocolo Cancelamento de NFe)',$aFont,'T','C',0,'');
DaCancnfeNFePHP.class.php:        #$this->__textBox($x,$y+15,$w2,8,$texto,$aFont,'T','L',0,'');
DaCancnfeNFePHP.class.php:        $tsHora = $this->__convertTime($this->dhEvento);
DaCancnfeNFePHP.class.php:        $this->__textBox($x,$y+20,$w2,8,$texto,$aFont,'T','L',0,'');
DaCancnfeNFePHP.class.php:        $tsHora = $this->__convertTime($this->dhRegEvento);
DaCancnfeNFePHP.class.php:        $this->__textBox($x,$y+25,$w2,8,$texto,$aFont,'T','L',0,'');
DaCancnfeNFePHP.class.php:        $this->__textBox($x,$y1,$maxW,33);
DaCancnfeNFePHP.class.php:        $this->__textBox($x+5,$y1,$maxW-5,20,$texto,$aFont,'T','L',0,'',false);
DaCancnfeNFePHP.class.php:        $numNF = $this->__format($numNF,"###.###.###");
DaCancnfeNFePHP.class.php:        $this->__textBox($x+2,$y+11,$w2,8,$texto,$aFont,'T','L',0,'');
DaCancnfeNFePHP.class.php:        $texto = $this->__format( $this->chNFe, $this->formatoChave );
DaCancnfeNFePHP.class.php:        $this->__textBox($x,$y1,$w-2,$h,$texto,$aFont,'T','C',0,'');
DaCancnfeNFePHP.class.php:            $this->__textBox($x,$y,$w,$h,$texto,$aFont,'C','C',0,'');
DaCancnfeNFePHP.class.php:            $this->__textBox($x,$y+14,$w,$h,$texto,$aFont,'C','C',0,'');
DaCancnfeNFePHP.class.php:        $this->__textBox($x,$y,$maxW,5,$texto,$aFont,'T','L',0,'',false);
DaCancnfeNFePHP.class.php:        $this->__textBox($x,$y,$maxW,210);
DaCancnfeNFePHP.class.php:        $this->__textBox($x+2,$y+2,$maxW-2,150,$texto,$aFont,'T','L',0,'',false);
DaCancnfeNFePHP.class.php:        $this->__textBox($x,$y,$w,20,$texto,$aFont,'T','C',0,'',false);
DaCancnfeNFePHP.class.php:        $this->__textBox($x,$y,$w,4,$texto,$aFont,'T','L',0,'');
DaCancnfeNFePHP.class.php:        $this->__textBox($x,$y,$w,4,$texto,$aFont,'T','R',0,'http://www.nfephp.org');

**Comment by robmachado** [comment]
Roberto;

Vamos deixar apenas funcional em "master", mas essas classes serão completamente refatoradas em develop. Estou agora refatorando as classes Tools (NFe, CTe, MDFe) com uma estrutura básica única para os três documentos fiscais. E vou necessitar de ajuda para fazer o mesmo com as classes Make (NFe já foi feita, mas MDFe e CTe falta fazer) e para as classes de impressão dos documentos.

**Comment by lucasvaccaro** [comment]
Corrigi essa questão dos "__" nas classes DaCancnfeNFePHP e DaEventoNFePHP na branch master
