### ISSUE TITLE
Atualizar FPDF 1.6 para 1.7

### ISSUE THREAD

**Issue by guicalabria** [nfephp-org/nfephp#361]
Existe alguma restrição para utilizar o FPDF 1.6 e não o FPDF 1.7?

**Comment by robmachado** [comment]
Que eu saiba não ... mas na nova versão sendo refatorada o FPDF será substituido pelo TCPDF

**Comment by guicalabria** [comment]
Ok!

**Comment by tonicospinelli** [comment]
@robmachado qual o motivo de usar o TCPDF? Acho que deveriamos dar preferência para projetos que usem o composer!!

**Comment by robmachado** [comment]
Mas o TCPDF está no composer !!

https://packagist.org/packages/tecnick.com/tcpdf

2015-02-18 10:54 GMT-02:00 Antonio Oertel Spinelli <notifications@github.com
>:

> @robmachado <https://github.com/robmachado> qual o motivo de usar o
> TCPDF? Acho que deveriamos dar preferência para projetos que usem o
> composer!!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/nfephp-org/nfephp/issues/361#issuecomment-74859144>.
>



-- 
Roberto

*Nisi utile est quod facimus stulta est gloriae* (Julius Phaedous)

**Comment by tonicospinelli** [comment]
Tudo bem! Por outro lado, ela não tem testes, não segue padrões de código, entre outros detalhes.

Acho que usá-la pode deixar a geração de PDF mais lenta e sem um padrão.

Pergunto novamente, por que não Zend PDF?

**Comment by tonicospinelli** [comment]
Ainda mais agora que estamos refatorando a biblioteca para melhorar o código, acho que poderíamos usar bibliotecas melhores testadas e usadas pelo mundo todo :wink:

**Comment by robmachado** [comment]
Bom particularmente eu tenho muita dificuldade com Zend, por isso não me
disponho a fazer isso mas se você estiver disposto sou a favor. Mas alguem
tem que começar a refatoração (que nesse caso é refazer) usando o Zend

Em 18 de fevereiro de 2015 11:05, Antonio Oertel Spinelli <
notifications@github.com> escreveu:

> Ainda mais agora que estamos refatorando a biblioteca para melhorar o
> código, acho que poderíamos usar bibliotecas melhores testadas e usadas
> pelo mundo todo [image: :wink:]
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/nfephp-org/nfephp/issues/361#issuecomment-74860533>.
>



-- 
Roberto

*Nisi utile est quod facimus stulta est gloriae* (Julius Phaedous)

**Comment by tonicospinelli** [comment]
Beleza, eu faço! vou criar a issue

**Comment by robmachado** [comment]
OK !! tendo alguma coisa já estruturada eu posso analisar, entender e
ajudar, se possível.

**Comment by aguimaraes** [comment]
Tonico, você é o cara, obrigado.

**Comment by fmertins** [comment]
Bom dia, vou tentar ajudar um pouco com Zend, abraços.
