### ISSUE TITLE
Usar Zend\Pdf para gerar a DANFE

### ISSUE THREAD

**Issue by tonicospinelli** [nfephp-org/nfephp#366]
Conforme conversados na issue #361 vamos trocar a biblioteca que gera o PDF para a da Zend, isso nos permitirá uma melhor implementação e também poderemos controlar melhor futuras atualizações

**Comment by rspadim** [comment]
não esqueçam alguns detalhes importantes:
1) boa parte imprime varios danfes / cte / carta correção / etc, tudo junto e misturado em um unico PDF
2) cada NFC-e tem seu tamanho variavel (altura/largura), neste caso não vejo porque misturar uma CCe e uma NFC-e, mas de qualquer forma, é interessante ao menos, misturar varias NFC-e de uma unica vez, existem estabelecimentos que emitem os 'cupons' acumulados no final do dia (academias por exemplo) em vez de fazer um a um (um pouco "incorreto", mas fiscalmente aceito)

**Comment by robmachado** [comment]
Por mim .. qualquer ajuda será muiiitooo BEM VINDA.!! Fico no aguardo para
poder ajudar [?]

Em 18 de fevereiro de 2015 11:28, Antonio Oertel Spinelli <
notifications@github.com> escreveu:

> Conforme conversados na issue #361
> <https://github.com/nfephp-org/nfephp/issues/361> vamos trocar a
> biblioteca que gera o PDF para a da Zend, isso nos permitirá uma melhor
> implementação e também poderemos controlar melhor futuras atualizações
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/nfephp-org/nfephp/issues/366>.
>



-- 
Roberto

*Nisi utile est quod facimus stulta est gloriae* (Julius Phaedous)

**Comment by fmertins** [comment]
Voltando para o Tonico, não consegui vincular nós dois ao mesmo tempo :-(

**Comment by fmertins** [comment]
Penso eu aqui com meus neurônios, que provavelmente esta issue terá que ser quebrada em várias outras menores, pois este tópico/problema é muito grande.

Se entendi certo, estamos falando sobre reescrever a geração de documentos em PDF *do zero*, seria isto?

Valeu!

**Comment by robmachado** [comment]
Fernando;
Creio que sim pois o código atual está muito ruim e usa bibliotecas que nem
são muito bem mantidas.
Como o conceito hoje é passar a usar o COMPOSER e como o Antonio disse algo
que seja ativamente mantido em os padrões mais atuais e aceitos para
melhorar a estabilidade e reduzir os riscos de usar o código.

Então para usar o ZendPdf teria que literalmente reescrever !!

**Comment by tonicospinelli** [comment]
@rspadim acho que não é possível duas pessoas darem assign. O que podemos fazer é o seguinte, separar em mais issues, por exemplo, eu trabalho para montar um core e você para implementar a DANFE, ou qualquer coisa do tipo.
Primeiro, deixa eu preparar a estrutura das classes core que serão usadas em cada um dos documentos a serem gerados, levando em consideração o que mencionou logo acima. :wink: 

@robmachado é isso mesmo, vamos matar o que existe e criar classes novas usando a library da Zend.

**Comment by tonicospinelli** [comment]
@rspadim valeu pelo toque, mas a minha idéia é trabalhar de forma separada, cada documento terá seu namespace e isso não permitirá que se misturem em um pdf e depois podemos consolidá-los em outro documento usando uma outra classe

**Comment by robmachado** [comment]
@tonicospinelli É eu também acho que cada documento deve ter sua classe separada e depois pode ser feita uma FACADE de juntar tudo em uma unica chamada.

**Comment by rspadim** [comment]
desde que o usuario final (programador) consiga gerar um unico arquivo PDF sem precisar gravar arquivos ou ter acesso a pastas temporarias pra isto, ok
ja vi fazerem "mesclagem" de pdf mas precisa de varios arquivos salvos no disco, acho isso deselegante uma vez que precisa de uma segurança no disco a mais pra escrita/leitura, se for possivel fazer tudo via API e memória, 100% apoiado, hoje na nfephp passa a classe do 'gerador de pdf' pra fazer isso, enfim, aguardo sua estrutura para dar outros toques

**Comment by tonicospinelli** [comment]
@rspadim legal! Para já, posso adiantar que a idéia é separar tudo em blocos e cada bloco ter a sua própria classe para que seja acoplado ao documento :wink: 

Assim fica tudo separado e de fácil manutenção

**Comment by robmachado** [comment]
O ZEND PDF foi DESCONTINUADO !!! repensar essa estratégia e reavaliar o uso do TCPDF.
