### ISSUE TITLE
NFe 3.10 - Arquivo TXT

### ISSUE THREAD

**Issue by Fertusco** [nfephp-org/nfephp#380]
Prezados, bom dia.

Utilizo o projeto nfephp em produção há alguns anos sem problemas. Agora vamos ter que realizar as alterações para a emissão no novo layout 3.10.

O projeto já encontra-se estável para emissão das notas neste novo layout?
Alguém poderia disponibilizar um arquivo TXT já no padrão 3.10, pois não temos mais acesso ao ambiente de homologação para comparar as mudanças que serão necessárias na TXT?

Obrigado.

**Comment by robmachado** [comment]
vaja a ISSE 377 

https://github.com/nfephp-org/nfephp/issues/377

**Comment by Fertusco** [comment]
@robmachado se eu gerar a NFe utilizando diretamente a classe MakeNFePHP ao invés de converter o TXT, o processo está estável para a emissão em produção?

**Comment by robmachado** [comment]
https://github.com/nfephp-org/nfephp/issues/378

**Comment by Fertusco** [comment]
Vou tentar mexer na classe ConvertNFePHP este final de semana já que o prazo para adequação está curtíssimo e qualquer dúvida posto aqui.

**Comment by rspadim** [comment]
se vc tiver muiiiita pressa tem um ja pronto, só não está no padrão da nfephp

**Comment by meio** [comment]
Eu presto consultoria na implementação do da API no seu sistema, se tiver interesse...

**Comment by 6am** [comment]
@meio eu tenho interesse, pode me mandar email no bruno@6am.com.br?

**Comment by meio** [comment]
@Fertusco tem interesse?

@6am te enviei um email...

**Comment by Fertusco** [comment]
@meio Obrigado pela proposta, mas gosto de programar e contribuir com a comunidade OpenSource.

**Comment by Fertusco** [comment]
@rspadim não entendi o que quis dizer com não esta no padrão nfephp?

Olhei o código e já está com todas as modificações do layout 3.10. Não está funcionando juntamente com suíte do nfephp?

**Comment by rspadim** [comment]
não esta passando no pull request, pq o define() está diferente, de resto pode usar normal, só ajustar o começo do codigo

**Comment by rspadim** [comment]
@Fertusco  da uma olhada: https://github.com/nfephp-org/nfephp/pull/305

**Comment by Fertusco** [comment]
@rspadim muito bom. Vou começar a modificar meu sistema para gerar o TXT na versão 3.10 e irei usar sua classe de conversão.

Apenas um dúvida, mesmo enviado apenas 1 nota por vez o nfephp continua utilizando o webservice no modo assíncrono, com a geração do protocolo, certo?

**Comment by rspadim** [comment]
então, tem duas classes lá pra converter, uma nasceu pelo projeto nfephp a outra pela iniciativa de fazer um emissor aberto (mas ta parado), a diferença é a estrutura do programa, um ta mais voltado pra adicionar/remover campos em um array, e o outro é mecher linha a linha de programação, os dois funcionam...

quanto ao envio, se não me engano até o software da receita deixou de usar modo sincrono, melhor ir pelo assincrono (na minha opnião) e deixar um espaço pra exportar o TXT (vai que da alguma "merda grande" e só a receita consegue transmitir....)
