### ISSUE TITLE
Erro getElementsByTagName em DanfeNFePHP.class.php

### ISSUE THREAD

**Issue by Fertusco** [nfephp-org/nfephp#392]
Quando vai gerar o PDF é apresentando um erro na linha 3076 do arquivo DanfeNFePHP.class.php, pois como nenhuma nota foi referenciada, a variável ide estava vazia.

Para corrigir, apenas comentamos a linha 671 no mesmo arquivo já que não referenciamos nota durante a geração, mas fica registrado mais um bug.

**Comment by robmachado** [comment]
Já corrgido
