### ISSUE TITLE
Importar XML via webservice sefaz - getDistDFe()

### ISSUE THREAD

**Issue by fredroo** [nfephp-org/nfephp#403]
Tentei usar o método indicado para importar as notas do webservice do Sefaz e não obtive sucesso 
```
<?php

require_once('../libs/NFe/ToolsNFePHP.class.php');

$nfe = new ToolsNFePHP();

//busca as chaves das nfes emitidas para o CNPJ informado no install do nfephp
$resultado = $nfe->getDistDFe();

print_r($resultado);

?>
```
com o código acima nada é retornado

o método está ok? alguém consegue me auxiliar para que criemos um arquivo de exemplo

**Comment by robmachado** [comment]
Veja em
https://github.com/nfephp-org/nfephp/blob/master/exemplos/NFe/testaNFeGetDFe.php

E não se esqueça de manter os arquivos config/nfe_ws3_mod55.xml e
config/nfe_ws3_mod65.xml atualizados.

Roberto

**Comment by fredroo** [comment]
ok Roberto seguirei suas instruções

gostaria de falar com você no skype sobre certificado A3

tenho interesse até de pagar algum desenvolvedor para criar essa integração para sua API e disponibilizar por aqui.

**Comment by robmachado** [comment]
Não uso skype !!! somente pelo HangOut do Google.

Quanto a certificado A3 já adianto .... "ESQUEÇA" se quiser usar PHP.

Roberto

**Comment by fredroo** [comment]
ok Roberto entendido, obrigado então.
