### ISSUE TITLE
NFSE RS

### ISSUE THREAD

**Issue by cacio** [nfephp-org/nfephp#439]
Bom dia,
Estou lidando com uma classe NFSePHP.php nas libs mas não estou sabendo passar os dados para o xml no entanto estou passando os dados em um item array mas quando vou usar a função da classe me gera um erro de uma classe que não achei class.gNFeTools.php estou tentando mandar para www.abrasf.org.br, se alguém puder me ajudar como eu prossigo com essa classe eu agradeço.

**Comment by robmachado** [comment]
Pergunte no grupo e não como uma ISSUE !!!

Em 21 de março de 2015 11:21, Cacio <notifications@github.com> escreveu:

> Bom dia,
> Estou lidando com uma classe NFSePHP.php nas libs mas não estou sabendo
> passar os dados para o xml no entanto estou passando os dados em um item
> array mas quando vou usar a função da classe me gera um erro de uma classe
> que não achei class.gNFeTools.php estou tentando mandar para
> www.abrasf.org.br, se alguém puder me ajudar como eu prossigo com essa
> classe eu agradeço.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/nfephp-org/nfephp/issues/439>.
>



-- 
Roberto

*Nisi utile est quod facimus stulta est gloriae* (Julius Phaedous)
