### ISSUE TITLE
Falha de validação na tag: zTagCOFINSoutr(..) em MakeNFePHP.class.php

### ISSUE THREAD

**Issue by phplucasnunes** [nfephp-org/nfephp#441]
Segundo a documentação da sefaz,  se informo os campos vBC e pCOFINS não posso informar qBCProd e vAliqProd. Esta gerando erro de validação.
Solução:
 //Informar estes campos para calculo do COFINSem percentual
		if((int)$vBC>0) {
			$this->zAddChild($confinsoutr, "vBC", $vBC, false, "Valor da Base de Cálculo da COFINS");
			$this->zAddChild($confinsoutr, "pCOFINS", $pCOFINS, false, "Alíquota da COFINS (em percentual)");
		//Para calculo do COFINS em valor
		}else {
			$this->zAddChild($confinsoutr, "qBCProd", $qBCProd, false, "Quantidade Vendida");
			$this->zAddChild($confinsoutr, "vAliqProd", $vAliqProd, false, "Alíquota da COFINS (em reais)");
		}

**Comment by robmachado** [comment]
Lucas;

Isso não é necessário dentro da classe é só deixar os campos que não serão usados vazios que essas tags não serão criadas. e por isso que existe esse "false" no método

**Comment by meio** [comment]
@phplucasnunes como @robmachado  disse é so deixar em branco, pois a classe apenas monta, o ERP deve saber se vai passar os parametros ou não.

**Comment by robmachado** [comment]
Estou fechando essa ISSUE
