### ISSUE TITLE
Falha de validação na tag do PIS - função tagPIS(..) em makeNFePHP.class.php

### ISSUE THREAD

**Issue by phplucasnunes** [nfephp-org/nfephp#442]
solução:
//Para Calculo do PIS em percentual
                if((int)$vBC>0) {
					$this->zAddChild($pisItem, 'vBC', $vBC, false, "[item $nItem] Valor da Base de Cálculo do PIS");
					$this->zAddChild($pisItem, 'pPIS', $pPIS, false, "[item $nItem] Alíquota do PIS (em percentual)");
				//Para Calculo do PIS em valor
				}else {
					$this->zAddChild($pisItem, 'qBCProd', $qBCProd, false, "[item $nItem] Quantidade Vendida");
					$this->zAddChild($pisItem, 'vAliqProd', $vAliqProd, false, "[item $nItem] Alíquota do PIS (em reais)");
				}

**Comment by robmachado** [comment]
Lucas;

Isso não é necessário dentro da classe é só deixar os campos que não serão usados vazios que essas tags não serão criadas. e por isso que existe esse "false" no método

**Comment by meio** [comment]
@phplucasnunes como @robmachado  disse é so deixar em branco, pois a classe apenas monta, o ERP deve saber se vai passar os parametros ou não.

**Comment by robmachado** [comment]
estou fechando essa ISSUE
