### ISSUE TITLE
Salvar PDF da DANFe

### ISSUE THREAD

**Issue by meio** [nfephp-org/nfephp#449]
ola, houve a necessidade de salvar a DANFe em PDF em determinada pasta, porem ao indicar a pasta que o pdf sera saldo, a classe não esta salvando neste lugar, ela salva na raiz do projeto.
Não consegui identificar aonde ocorre o erro.

**Comment by robmachado** [comment]
você colocou o path real ?

**Comment by meio** [comment]
@robmachado sim, testei varios caminhos, tanto no windows e no linux, ele n salva aonde foi especificado

**Comment by robmachado** [comment]
Mandei para arquivo sem nenhum problema aqui ....

lembre-se que deve passar o path completo do arquivo e a opção deve ser "F"


2015-03-25 11:42 GMT-03:00 meio <notifications@github.com>:

> @robmachado <https://github.com/robmachado> sim, testei varios caminhos,
> tanto no windows e no linux, ele n salva aonde foi especificado
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/nfephp-org/nfephp/issues/449#issuecomment-86058000>.
>



-- 
Roberto

*Nisi utile est quod facimus stulta est gloriae* (Julius Phaedous)

**Comment by meio** [comment]
@robmachado foi exatamente o que foi feito, ate fiquei meio assim, testei de varios jeitos, nenhum deu certo, me cola aqui o seu exemplo...

**Comment by robmachado** [comment]
<?php
// Passe para este script o arquivo da NFe
// Ex.
testaDANFE.php?nfe=35100258716523000119550000000033453539003003-nfe.xml
error_reporting(E_ALL ^ E_NOTICE);
require_once('../../libs/NFe/DanfeNFePHP.class.php');

//$arq = $_GET['nfe'];
$arq =
'/var/www/nfephp3/exemplos/xml/24141026461699046504550010000297071000297075.xml';

if (is_file($arq)) {
    $docxml = file_get_contents($arq);
    $danfe = new DanfeNFePHP($docxml, 'P', 'A4', '../../images/logo.jpg',
'I', '');
    $id = $danfe->montaDANFE();
    $teste = $danfe->printDANFE("/var/www/nfe/$id.pdf", 'F');
}

Com esse comando foi grado na pasta indicada, que tem permissão de escrita
pelo www-data (só lembrete uso LINUX)

Em 25 de março de 2015 13:36, meio <notifications@github.com> escreveu:

> @robmachado <https://github.com/robmachado> foi exatamente o que foi
> feito, ate fiquei meio assim, testei de varios jeitos, nenhum deu certo, me
> cola aqui o seu exemplo...
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/nfephp-org/nfephp/issues/449#issuecomment-86108664>.
>



-- 
Roberto

*Nisi utile est quod facimus stulta est gloriae* (Julius Phaedous)

**Comment by robmachado** [comment]
Estou fechando essa ISSUE

**Comment by meio** [comment]
Vou testar depois novamente.
Obrigado.
