### ISSUE TITLE
Correcao bug classe ConvertNFePHP

### ISSUE THREAD

**Issue by fcaserio** [nfephp-org/nfephp#450]
Na linha 761 existe um bloco de criacao da tag NVE.

Porem a tag NVE nao consta mais na linha I do layout:
I|cProd|cEAN|xProd|NCM|EXTIPI|CFOP|uCom|qCom|vUnCom|vProd|cEANTrib|uTrib|qTrib|vUnTrib|vFrete|vSeg|vDesc|

A conversao do TXT estava gerando um XML invalido que nao homologava no software emissor da SEFAZ
Precisei desabilitar o bloco de publicacao NVE (que nao consta no layout) e acertar os indices da array $dados[] ate a linha 833

Apos essa modificacao os XMLs gerados foram importados com sucesso no software emissor da SEFAZ

                case "I":
                    //PRODUTO SERVICO [det]
                    //I|cProd|cEAN|xProd|NCM|EXTIPI|CFOP|uCom|qCom|vUnCom|vProd|cEANTrib|uTrib|qTrib|vUnTrib
                    //|vFrete|vSeg|vDesc|vOutro|indTot|xPed|nItemPed|nFCI|
                    $prod = $dom->createElement("prod");
                    $cProd = $dom->createElement("cProd", $dados[1]);
                    $prod->appendChild($cProd);
                    $cEAN = $dom->createElement("cEAN", $dados[2]);
                    $prod->appendChild($cEAN);
                    $xProd = $dom->createElement("xProd", $dados[3]);
                    $prod->appendChild($xProd);
                    $NCM = $dom->createElement("NCM", $dados[4]);
                    $prod->appendChild($NCM);
                    /* if (!empty($dados[5])) {
                        //Esperar estabilidade do Emissor de NF-e 3.10 para saber se poderemos manter compatibilidade com o modo de importação do mesmo.
                        // São aceitos [0-8] NVE, mas o emissor EXPORTA apenas 1. Atualmente (15/09/14) ainda não é possível testar a importação do TXT no emissor.
                        $NVE = $dom->createElement("NVE", $dados[5]);
                        $prod->appendChild($NVE);
                    } */
                    if (!empty($dados[5])) {
                        $EXTIPI = $dom->createElement("EXTIPI", $dados[5]);
                        $prod->appendChild($EXTIPI);
                    }
                    $CFOP = $dom->createElement("CFOP", $dados[6]);
                    $prod->appendChild($CFOP);
                    $uCom = $dom->createElement("uCom", $dados[7]);
                    $prod->appendChild($uCom);
                    $qCom = $dom->createElement("qCom", $dados[8]);
                    $prod->appendChild($qCom);
                    $vUnCom = $dom->createElement("vUnCom", $dados[9]);
                    $prod->appendChild($vUnCom);
                    $vProd = $dom->createElement("vProd", $dados[10]);
                    $prod->appendChild($vProd);
                    $cEANTrib = $dom->createElement("cEANTrib", $dados[11]);
                    $prod->appendChild($cEANTrib);
                    if (!empty($dados[12])) {
                        $uTrib = $dom->createElement("uTrib", $dados[12]);
                    } else {
                        $uTrib = $dom->createElement("uTrib", $dados[7]);
                    }
                    $prod->appendChild($uTrib);
                    if (!empty($dados[13])) {
                        $qTrib = $dom->createElement("qTrib", $dados[13]);
                    } else {
                        $qTrib = $dom->createElement("qTrib", $dados[8]);
                    }
                    $prod->appendChild($qTrib);
                    if (!empty($dados[14])) {
                        $vUnTrib = $dom->createElement("vUnTrib", $dados[14]);
                    } else {
                        $vUnTrib = $dom->createElement("vUnTrib", $dados[9]);
                    }
                    $prod->appendChild($vUnTrib);
                    if (!empty($dados[15])) {
                        $vFrete = $dom->createElement("vFrete", $dados[15]);
                        $prod->appendChild($vFrete);
                    }
                    if (!empty($dados[16])) {
                        $vSeg = $dom->createElement("vSeg", $dados[16]);
                        $prod->appendChild($vSeg);
                    }
                    if (!empty($dados[17])) {
                        $vDesc = $dom->createElement("vDesc", $dados[17]);
                        $prod->appendChild($vDesc);
                    }
                    if (!empty($dados[18])) {
                        $vOutro = $dom->createElement("vOutro", $dados[18]);
                        $prod->appendChild($vOutro);
                    }
                    if (!empty($dados[19]) || $dados[19] == 0) {
                        $indTot = $dom->createElement("indTot", $dados[19]);
                        $prod->appendChild($indTot);
                    } else {
                        $indTot = $dom->createElement("indTot", '0');
                        $prod->appendChild($indTot);
                    }
                    if (sizeof($dados) >= 20) {
                        if (!empty($dados[20])) {
                            $xPed = $dom->createElement("xPed", $dados[20]);
                            $prod->appendChild($xPed);
                        }
                        if (!empty($dados[21])) {
                            $nItemPed = $dom->createElement("nItemPed", $dados[21]);
                            $prod->appendChild($nItemPed);
                        }
                        if (!empty($dados[22])) {
                            $nFCI = $dom->createElement("nFCI", $dados[22]);
                            $prod->appendChild($nFCI);
                        }
                    }
                    if (!isset($infAdProd)) {
                        $det->appendChild($prod);
                    } else {
                        $det->insertBefore($det->appendChild($prod), $infAdProd);
                    }

**Comment by robmachado** [comment]
Isso não existe na classe ConvertNFePHP.php (branch master)

o NVE está na tag "I05a" na linha 838

Roberto
