### ISSUE TITLE
Implementação do Modal Aquaviário na impressão do DACTe

### ISSUE THREAD

**Issue by allanwolski** [nfephp-org/nfephp#454]
Implementei a impressão do CT-e Modal Aquaviário.

Além da criação do método zModalAquaviario, tive que realizar outros ajustes para que a impressão ficasse correta.
Gostaria de saber como posso fazer para enviar o fonte do DacteNFePHP.class.php, pois para detalhar todas as alterações aqui na issue fica complicado.

Peço desculpas caso não esteja seguindo o caminho correto, pois é minha primeira contribuição.

**Comment by robmachado** [comment]
O correto é abir um pull request

mas se você não sabe usar o GIT pode mandar o arquivo pra mim

Roberto

**Comment by allanwolski** [comment]
Acabei de lhe encaminhar um e-mail com os arquivos em anexo, Roberto.
Conforme comentei no e-mail, encaminhei algumas correções no DaEventoCTeNFePHP.class.php também.

Ainda não estou familiarizado com o GIT, mas para as próximas correções vou procurar abrir um pull request.

Allan
