### ISSUE TITLE
MailNFe - anexar PDF

### ISSUE THREAD

**Issue by guicalabria** [nfephp-org/nfephp#460]
Olá,
  Qual foi o motivo que a classe MailNFe seria responsável por:
        if ($comPdf) {
            //se $comPdf é verdadeiro então é criado o DANFE e anexado ao email
            //TODO : renderizar o pdf e anexar ao email
   Por que não somente enviar o path do PDF, como do XML para anexar quando não estiver vazio?
   Eu não consegui somente fazer um novo:
$this->addAttachment($pathPDF, '');
   O PDF não é enviado, precisa de algo a mais?

  Também não seria interessante também possuir um método para o envio do XML de cancelamento?
Abraços!

**Comment by robmachado** [comment]
Guilherme;

Em geral (como nos meus sistemas) eu não mantenho cópia do pdf então
renderizo sempre que necessário.

Mas podemos pensar em incluir formas de anexar o pdf por meios externos a
essa classe e o programador pode optar por renderizar ou apenas carregar o
pdf.

Roberto

**Comment by guicalabria** [comment]
Ok... eu não consegui anexar o PDF e o XML juntos :-(
Ou anexo o PDF ou o XML por enquanto...

Em 29 de março de 2015 09:12, Roberto L. Machado <notifications@github.com>
escreveu:

**Comment by guicalabria** [comment]
Vi que você atualizou vou testar!

Em 29 de março de 2015 17:33, Guilherme Calabria Filho <guiga86@gmail.com>
escreveu:

**Comment by guicalabria** [comment]
Roberto,
   Realizei testes de envios e aparenta estar funcionando corretamente.
   O que você acha de adicionar o número da chave no e-mail? Assim o
usuário poderia clicar duas vezes, copiar os valores e conferir no site da
receita.

Abraços!

Em 29 de março de 2015 17:41, Guilherme Calabria Filho <guiga86@gmail.com>
escreveu:
