### ISSUE TITLE
Parser XML: 'xmlns' is a duplicate attribute name

### ISSUE THREAD

**Issue by guicalabria** [nfephp-org/nfephp#464]
Roberto, 
   Os testes de cancelamento apontaram o erro no XML
CancNFe-procEvento.xml
   Salvo na pasta "eventos", no validador do RS acusa:
Parser XML: 'xmlns' is a duplicate attribute name. Line 1, position 162.
   Na tag  "evento" possui dois xmlns um com http://www.portalfiscal.inf.br/nfe e outro com http://www.w3.org/2000/09/xmldsig#

 Na carta de correção com o mesmo problema.

Abraços!

**Comment by robmachado** [comment]
Já corrigido
