### ISSUE TITLE
Problema para autorizar na SEFAZ GO

### ISSUE THREAD

**Issue by pdati** [nfephp-org/nfephp#468]
Caros,

inicie hoje a operação da NFE 3.10 e no DF estou autorizando normalmente. Quando tento autorizar no GO recebo o seguinte erro:

name lookup timed out Nao houve retorno Soap verifique a mensagem de erro e o debug!

No site da SEFAZ GO eles informam uma mudança no WSDL (http://www.nfe.go.gov.br/post/ver/194555/alteracao-de-web-service). Tentei replicar a alteração no arquivo nfe_ws3_mod55.xml, mas não tive sucesso. Alguém tem alguma idéia? Alguém está passando por isso?

Pablo Giordano

**Comment by robmachado** [comment]
Antes de fazer algo como isso que não acredito ser necessário veja os
comentários sobre GO na lista !!!

Outra coisa para fazer perguntar e interagir com os membros use o grupo e
não o github.

Roberto

**Comment by robmachado** [comment]
Isso não é um ISSUE da API para colocar aqui !!!
