### ISSUE TITLE
UnConvertNFe (XML para TXT) não converte corretamente

### ISSUE THREAD

**Issue by jonasmartinez** [nfephp-org/nfephp#472]
Boa tarde pessoal!

Tentei ajustar mas sem muito sucesso a classe de conversão de xml para txt, preciso assinar e emitir pelo emissor da receita federal, mas para isso ele só aceita txt, então preciso converter os xml que já consigo gerar perfeitamente em txt, mas nenhuma classe do projeto está exportando corretamente, alguém tem o mesmo problema?

Está também desatualizado, o dhEmi por exemplo etc...

**Comment by guicalabria** [comment]
O sistema da receita aceita XML.

Em 1 de abril de 2015 19:58, jonasmartinez <notifications@github.com>
escreveu:

**Comment by jonasmartinez** [comment]
Se tento importar sem signature ele da erro, se mando com ele da invalidez de certificação, como importo pro sistema gratuito para assinar transmitir etc?

Mesmo assim é legal o pessoal ter esse método funcionando.

**Comment by robmachado** [comment]
Eu não pretendo manter nem refatorar essa classe. Na nova versão não existirá mais ... não vou mais mantela. Se alguém estiver disposto a mante-la  e refatora-la para os padrões de DEVELOP ótimo senão vai pro "dedéu"

**Comment by jonasmartinez** [comment]
Certo, quem precisa importar a nfe para o emissor gratuito afim de usar o certificado a3 sem ser em txt faz como? sabe informar?

**Comment by robmachado** [comment]
Se tiver o XML o sistema gratuito também importa

Roberto
