### ISSUE TITLE
Índice associativo extracerts () inexistente

### ISSUE THREAD

**Issue by Gleidson2012** [nfephp-org/nfephp#478]
Boa tarde pessoal!

O método ToolsNFePHP->pLoadCerts tem uma instrução que menciona o índice 'extracerts', e ao ler o meu certificado esse índice não é definido.

Alguém sabe me explicar o porquê?
E se esse índice (essa informação) é importante ou não?

```php
                //acrescenta a cadeia completa dos certificados se estiverem
                //inclusas no arquivo pfx, caso contrario deverão ser inclusas
                //manualmente para acessar os serviços em GO
                $aCer = $x509certdata['extracerts'];
                $chain = '';
                foreach ($aCer as $cert) {
                    $chain .= "$cert";
                }
                file_put_contents($this->pubKEY, $x509certdata['cert']);
                file_put_contents($this->certKEY, $x509certdata['cert'] . $chain);
```

**Comment by robmachado** [comment]
Normalmente esse campo está vazio nos certificados

Eles deveriam existir caso o certificado você exportado com toda a cadeia
de certificação

Roberto

**Comment by Gleidson2012** [comment]
Entendi Roberto.

Blz!

Issue fechada pelo pull request #479
