### ISSUE TITLE
Dúvida arquivos XML dos webservices

### ISSUE THREAD

**Issue by fmertins** [nfephp-org/nfephp#480]
Bom dia pessoal, uma dúvida que surgiu aqui: nós temos os dois arquivos de webservices separados por modelo da NF-e:

config/nfe_ws3_mod55.xml ==> NF-e
config/nfe_ws3_mod65.xml ==> NFC-e

Mas se olharmos a relação de webservices no Portal Nacional da NF-e (http://www.nfe.fazenda.gov.br/portal/webServices.aspx?tipoConteudo=Wak0FwB7dKs=), não há distinção do modelo, portanto, em virtude da nossa estrutura de dois arquivos separados, temos que duplicar algumas URLs nos dois arquivos nos casos em que a URL é a mesma tanto para a NF-e quanto para a NFC-e, seria isto? Me parece que sim...

Obrigado!

**Comment by robmachado** [comment]
Não é bem assim Fernando

Existem webservices diferentes para NFe e NFCe e poderão haver mais

Na classe em DEVELOP assim que você define o modelo a própria classe pega o
arquivo certo

Haverá DUPLICAÇÃO  ? ====> SIM, existem URL que serão replicadas nos dois
casos

Roberto

**Comment by fmertins** [comment]
Exemplo prático: se eu pesquisar pela URL da SEFAZ RS, produção, webservice NfeAutorizacao, que é esta:

https://nfe.sefaz.rs.gov.br/ws/NfeAutorizacao/NFeAutorizacao.asmx

Encontra apenas uma ocorrência, a do arquivo nfe_ws3_mod55.xml, mas não deveria existir uma segunda ocorrência, no outro arquivo do modelo 65, já que o WS é o mesmo para autorizar tanto NF-e quanto NFC-e? :-)

(estou com a branch master aqui)

**Comment by robmachado** [comment]
Não importa se é master ou develop ...

A questão é incluir em um único arquivo MAIS uma chave de busca (modelo) já
pensei nisso mas está ficando muito carregado e complexo para manter.

Para isso tem que repensar muitas coisas na classe

Lembre-se que não estou avaliando um caso em particular mas sim toda a
estrutura

Roberto

**Comment by fmertins** [comment]
Perfeito Roberto entendi :-) Pensando superficialmente agora (não estou muito concentrado nas configurações) realmente me parece melhor um arquivo apenas para evitar a situação-problema de atualizar uma URL num dos arquivos e esquecer de atualizar a mesma URL no outro arquivo :-) Mas lembro que ano passado quando criamos estas novas configurações falamos a respeito e ficou implementado assim em separado.

IMPORTANTE: me parece que deste jeito, no arquivo do modelo 65, precisaremos ter todos os mesmos webservices do modelo 55, mais os webservices exclusivos da NFC-e, seria isto?

**Comment by robmachado** [comment]
É mais ou menos isso no arquivo do modelo 65 teremos quase todos os URL do
modelo 55 e aqueles específicos do modelo 65.

Esses URL específicos em geral são o autorização (síncrona ou não) os
demais PODEM mudar também no futuro em função de carga.

No modelo 65 processo mais acessado com certeza é o de autorização e é
nesse serviço que estão as maiores diferenças.

Ninguém usando modelo 65 vai ficar consultando CADASTROS, inutilizando
faixas, manifestando,  baixando NFe etc..

*No modelo 65 é apenas autorização, consulta e cancelamento (nem carta de
correção é viável)*

Roberto

**Comment by fmertins** [comment]
OK Roberto, mas uma dúvida nesta especificação:

*No modelo 65 é apenas autorização, consulta e cancelamento (nem carta de
correção é viável)*

Digamos que vou emitir uma NFC-e e antes de autorizar quero consultar o status da SEFAZ, precisamos ter a entrada <NfeStatusServico> duplicada igual ao arquivo nfe_ws3_mod55.xml confere?

**Comment by robmachado** [comment]
Exato

**Comment by fmertins** [comment]
Olá, fiz o PR #483 com atualização dos webservices, branch master, dá uma olhada por favor, obrigado!

**Comment by robmachado** [comment]
OK

mas Fernando, concentre-se  no DEVELOP !!! o que está em MASTER vai para
outra branch a "v3.1.0.a"

Roberto

**Comment by fmertins** [comment]
Oi, mas estou atualizando minha api em ambiente de produção, fiquei uns meses sem ajudar com melhorias e só acompanhando as alterações, aí fui atualizar e peguei direto a master, não sei a branch recomendada para ambiente de produção? Eu ainda vejo/entendo a develop como sinônimo de "unstable" :-) Mas posso ter me atrapalhado...

**Comment by robmachado** [comment]
Você está certo mas DEVELOP já está sendo usada em produção em alguns casos
...
O que eu quero é que vocês se concentrem nessa nova versão pois está bem
diferente da outra é uma REFATORAÇÃO
só não passei ainda para MASTER porque falta a parte da DANFE

Mas já estou perdendo a paciencia e vou logo logo passar para master

Roberto
