### ISSUE TITLE
Erro no carregamento dos volumes - ConvertNFe

### ISSUE THREAD

**Issue by guicalabria** [nfephp-org/nfephp#487]
Olá,
  Na classe ConvertNFe, o método yEntity está carregando os volumes, porém a tag Y é para pagamentos e optativa, quando o arquivo txt não possui Y os volumes não são adicionados para o XML.

    /**
     * yEntity
     * Carrega os volumes
     * @param array $aCampos
     */
    protected function yEntity($aCampos)
    {
        //Y|
        $aCampos = array();
        //carrega os volumes
        foreach ($this->linhaX26 as $vol) {
            $this->zLinhaXVolEntity($vol);
        }
    }

**Comment by robmachado** [comment]
Lenadro;
Coloquei isso ai pois antes de passar para os valores tinham de ser carregados dos os volumes. 
Mas eu não sei mesmo se é o melhor lugar.
Pergunta : Sempre existirá um "Y|" ? 
Podemos estudar uma solução !!

**Comment by robmachado** [comment]
Vixe !!! tô lendo Guilherme e escrevo Lenadro .... tá faltando café !?!?

**Comment by guicalabria** [comment]
Rsrsrs fica tranquilo, tenho um avô com 93 anos com o mesmo problema!!!! 
O Y não tem obrigação, quando o tipo de pagamentos é "Outros" como remessa para demonstração ou industrialização.
Eu coloquei 
    foreach ($this->linhaX26 as $vol) {        $this->zLinhaXVolEntity($vol);    }
 No zEntity pois mesmo sendo optativo também acredito que sempre conterá.
 Pensei também em durante a leitura do txt ir fazer o zLinhaXVolEntity, mas tenho que analisar a classe makenfe antes.

Abraços Roberto!!!

**Comment by robmachado** [comment]
Acho que tenho uma solução ...
podemos colocar esse laço na linha 84, ou seja depois que quase toda a
carga de dados  ...
pois a classe make só vai juntar esses blocos ("transp") no final no método
monta()
mas é necessário fazer alguns testes

Roberto

**Comment by robmachado** [comment]
Já fia a alteração é só testar ... e ai Guilherme o que achou da classe ConvertNFe, acho que ficou mais fácil entender e corrigir agora.

**Comment by guicalabria** [comment]
Roberto,

  Vou testar e lhe retorno.
  Sim, a classe convertnfe foi desenvolvida de forma muito boa, tornando-a
muito prática e inteligente. Ficou bem mais simples para entende-la.
  Agora, deixar cada parâmetro dos métodos em uma linha diferente tem qual
motivo? Na minha opinião dificulta a visualização.. acho que estou
acostumado com muito tempo com os parâmetros de lado.

Abraços, obrigado e parabéns pelo projeto!
Guilherme Filho

Em 8 de abril de 2015 11:08, Roberto L. Machado <notifications@github.com>
escreveu:

**Comment by guicalabria** [comment]
Roberto,
  Pelos testes realizados não encontrei nenhum erro.
  Eu nunca teste a realização de várias notas fiscais ao mesmo tempo, é realizado a limpeza das todas as variáveis toda vez? Já que a na instancia da classe é iniciado, mas talvez isso deva ser feito toda vez antes do método zArray2xml. Se não for feito dados de uma nota fiscal será usado na seguinte.

Abraços!

**Comment by robmachado** [comment]
Em teoria isso é feito em ao iniciar cada NF, ma sé preciso verificar se
realmente todos os parâmetros são limpos mesmo

/**
     * notafiscalEntity
     * Cria a entidade nota fiscal
     * @param array $aCampos
     */
    protected function notafiscalEntity($aCampos)
    {
        *$this->zClearParam();*
        $this->make = new MakeNFe();
        $aCampos = array();
    }


Roberto
