### ISSUE TITLE
Caracteres Especiais nas respostas da SEFAZ

### ISSUE THREAD

**Issue by robmachado** [nfephp-org/nfephp#496]
O SEFAZ PR na consulta do cadastro está retornando o & comercial sem a necessária transformação para a entidade "&amp;" isso faz com que o parser (DOM) falhe no carregamento. Esse problema poderá existir em outros serviços mal estruturados pelas SEFAZ, Que não cumprem suas próprias recomendações que mandam trocar os seguintes caracteres dos campos ANTES de formatar o XML.

&     &amp;
"      &quot;
'      &#39;
<       &lt;
>       &gt;

Como nas respostas dos SEFAZ já recebemos o XML montados a para desmonta-lo é necessário o parser, fica impossível corrigir essas falhas do lado da recepção (nosso lado). Apenas um caso a factível de correção, que é o & comercial seguido de um espaço em branco. Nesse e apenas nesse caso podemos automaticamente corrigir o xml recebido.

**Comment by robmachado** [comment]
Isso foi corrigido ... mas existem alguns casos em que a SEFAZ está retornando as entidades e não um XML. Verificar como contornar esse problemas !!!

**Comment by leandrogehlen** [comment]
Tive problemas com isso tb o código abaixo resolveu.
Não é muito elegante mas resolveu

```php
preg_replace('/&(?!;{6})/', '&amp;', $conteudo)
```

**Comment by robmachado** [comment]
Obrigado Leandro, vou ver onde colocar para prevenir esses erros.
