### ISSUE TITLE
Correcao classe ConvertNFePHP

### ISSUE THREAD

**Issue by fcaserio** [nfephp-org/nfephp#501]
Alguns segmentos do arquivo TXTmudaram de nome e nao estao sendo reconhecidos pela classe de conversao. Estou renomeando estes segmentos na minha versao e envio as referencias para atualizacao no master.
B13 => BA02
B14 => BA03
B20a => BA10
B20d => BA13
B20e => BA14
B20i => não consta
B20j => BA20

**Comment by robmachado** [comment]
Estou recomendando a todos a usar as classes em DEVELOP pois logo logo
passará para master.

Tente usar o que está em develop (versão 4.0.0 da API)

Roberto
