### ISSUE TITLE
NFSE RS

### ISSUE THREAD

**Issue by cacio** [nfephp-org/nfephp#525]
Ola, Estou a dias com dificuldade em mexer na classe que envia nfse para abrasf queria saber se essas classes vão ser ajustadas porque estou com uma dificuldade em passar alguns parâmetros como o caminho do certificado eu declaro no __construct mas não respeita alguém que é responsável por essas classes sera que teria como da uma implantada , ajustes desses caminhos, estou utilizando a classe NFSeSP para tentar enviar via abrasf.

Att,
Cacio

**Comment by robmachado** [comment]
Passe suas duvidas para o grupo, aqui no github normalmente eu recebo as
informações mas não criei nem uso essas classes, então não posso ajuda-lo.

Roberto

**Comment by cacio** [comment]
Aham , então os erros são esses , só que eu passo o caminho mas mesmo assim da o erro.

Warning: file_get_contents(diretorio_onde_esta_seu_certificado/privatekey.pem): failed to open stream: No such file or directory in C:\xampp\htdocs\PROJETOS\nfse\libs\NFSe\NFSeSP.class.php on line 250

Warning: openssl_sign(): supplied key param cannot be coerced into a private key in C:\xampp\htdocs\PROJETOS\nfse\libs\NFSe\NFSeSP.class.php on line 251

Warning: openssl_free_key() expects parameter 1 to be resource, boolean given in C:\xampp\htdocs\PROJETOS\nfse\libs\NFSe\NFSeSP.class.php on line 260

Fatal error: Call to a member function RpsEnvio() on a non-object in C:\xampp\htdocs\PROJETOS\nfse\libs\NFSe\NFSeSP.class.php on line 170
