### ISSUE TITLE
Problema na Danfe, Itens repetindo na segunda página.

### ISSUE THREAD

**Issue by gugacarmellino** [nfephp-org/nfephp#526]
Olá, boa noite!

estou com um erro na geração do Danfe. Os itens de uma página estão sendo repedidos em outra página. Poderia me dar uma luz de como resolver esse problema?

Segue o link de dois xml: https://www.dropbox.com/s/qacntc5b92uor1j/23150489850341000160550110025930791072250853.xml?dl=0

https://www.dropbox.com/s/55jewxbus8zmxow/13131204628426000145550020001301801671407013.xml?dl=0

Estou gerando em Retrato e A4

**Comment by gugacarmellino** [comment]
Só pra complementar, vi que o Danfe Online (https://www.danfeonline.com.br) também usa a API e essas mesmas NF-es estão sendo geradas normalmente!

**Comment by robmachado** [comment]
Gustavo passe o xml para teste

Roberto

**Comment by gugacarmellino** [comment]
Olá, Roberto!

os xml's estão nos links abaixo

https://www.dropbox.com/s/qacntc5b92uor1j/23150489850341000160550110025930791072250853.xml?dl=0

https://www.dropbox.com/s/55jewxbus8zmxow/13131204628426000145550020001301801671407013.xml?dl=0

**Comment by robmachado** [comment]
Fiz alterações .. mas a classe está um verdadeiro LIXO e necessita ser
refatora com urgência. Mas deve funcionar agora para os seus casos.

Roberto

**Comment by gugacarmellino** [comment]
Beleza, Roberto! Tá tudo certo agora.

...queria ter mais experiência com php pra te ajudar nessa refatoração.
