### ISSUE TITLE
Fluxo de trabalho

### ISSUE THREAD

**Issue by leandrogehlen** [nfephp-org/nfephp#531]
Já havia aberto um chamado (#239) anteriormente, para ser definido o fluxo de trabalho no git.
Mas acredito ser necessário aplicar o fluxo para trabalharmos com as **tags** e programar versões com os **milestones**

Atualmente uma correção realizada no `master` é perdida na versão `develop`. 
Logo, quando o branch `develop` virar `master` todas as correções devem ser realizadas novamente.

No fluxo adotado atualmente, dependemos do programador lembrar de replicar estas alterações para o `develop`.

Não sei se é possível, mas acredito ser necessário que o moderador, faça o merge para o branch `develop` quando chegam `Pull Request` no branch  `master`

**Comment by robmachado** [comment]
Na medida do aplicável ... tudo que é corrigido no MASTER é passado para
DEVELOP ...

Mas veja que estou dizendo CORRIGIDO e incluso, ampliado, modificado etc..
mas sempre pose ocorrer de eu acaber esquecendo algo ou julgando
inapropriado.

O moderador sou eu, está demorando para passar o DEVELOP para master pois
estou trabalhando praticamente sozinho e não tenho como testas e refatorar
CTe e MDFe (já a parte de NFSe estou quase retirando isso ....)

Roberto

**Comment by williamespindola** [comment]
Acho que se existir uma alteração realizada no master quem fez tem que ser preocupar em abrir ao menos uma issue para ser feita no develop. O Develop atualmente esta em constante inclusão, ampliação, modificação. Assim esta alterações não se perderiam no tempo.

**Comment by robmachado** [comment]
Sim senhor essa é a forma correta de faze-lo ....

Roberto
