### ISSUE TITLE
Campos Q05 e Q07 no ConvertNFePHP - PISOutr e vPIS

### ISSUE THREAD

**Issue by carlosmarian** [nfephp-org/nfephp#552]
Olá,
  Erro ao gerar a tag <PISOutr>, onde o vPIS esta preenchido no arquivo e não esta sendo gerado no XML.

  Avaliando o fonte encontrei o trecho que acho que deve ser revisado.
  Trecho que acredito estar errado:
```php
  case "Q05":
      //Grupo de PIS Outras Operações 0 ou 1 [PIS]
      //Q05|CST|vPIS|
      $PISOutr = $dom->createElement("PISOutr");
      $CST = $dom->createElement("CST", $dados[1]);
      $PISOutr->appendChild($CST);
      $vPIS = $dom->createElement("vPIS", $dados[2]);
      $PISOutr->appendChild($vPIS);
      $PIS->appendChild($PISOutr);
      break;
  case "Q07":
      //Valor da Base de Cálculo do PIS e Alíquota do PIS (em percentual) 0 pu 1 [PISOutr]
      // todos esses campos sao obrigatorios
      //Q07|vBC|pPIS|
      $vBC = $dom->createElement("vBC", $dados[1]);
      $PISOutr->insertBefore($vBC, $vPIS);
      $pPIS = $dom->createElement("pPIS", $dados[2]);
      $PISOutr->insertBefore($pPIS, $vPIS);
      break;
```
     Acredito que o correto seria algo parecido com isso:
 ```php
case "Q05":
	//Grupo de PIS Outras Operações 0 ou 1 [PIS]
	//Q05|CST|
	$PISOutr = $dom->createElement("PISOutr");
	$CST = $dom->createElement("CST", $dados[1]);
	$PISOutr->appendChild($CST);
	break;
case "Q07":
	//Valor da Base de Cálculo do PIS e Alíquota do PIS (em percentual) 0 pu 1 [PISOutr]
	// todos esses campos sao obrigatorios
	//Q07|vBC|pPIS|vPIS|
	$vPIS = $dom->createElement("vPIS", $dados[3]);
	$PISOutr->appendChild($vPIS);
	$PIS->appendChild($PISOutr);                    	
	$vBC = $dom->createElement("vBC", $dados[1]);
	$PISOutr->insertBefore($vBC, $vPIS);
	$pPIS = $dom->createElement("pPIS", $dados[2]);
	$PISOutr->insertBefore($pPIS, $vPIS);
	break;
 ```

**Comment by carlosmarian** [comment]
Manual:
Q|
[Seleção entre Q02 ou Q03 ou Q04 ou Q05]{
  Q02|CST|vBC|pPIS|vPIS|
  [ou]
  Q03|CST|qBCProd|vAliqProd|vPIS|
  [ou]
  Q04|CST|
  [ou]
  Q05|CST|
    [Seleção entre Q07 ou Q010]{
    Q07|vBC|pPIS|vPIS|
    [ou]
    Q10|qBCProd|vAliqProd|
 }
}

**Comment by carlosmarian** [comment]
Fiz um ajuste(conforme comentado na demanda) localmente no meu projeto e passou a gerar a TAG corretamente.

**Comment by robmachado** [comment]
Corrigido

Em 16 de maio de 2015 09:36, Carlos <notifications@github.com> escreveu:

> Fiz um ajuste(conforme comentado na demanda) localmente no meu projeto e
> passou a gerar a TAG corretamente.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/nfephp-org/nfephp/issues/552#issuecomment-102623433>.
>



-- 
Roberto

*Nisi utile est quod facimus stulta est gloriae* (Julius Phaedous)
