### ISSUE TITLE
conversao txt-xml

### ISSUE THREAD

**Issue by rspadim** [nfephp-org/nfephp#562]
G|
$xLgr nunca pode deixar de existir, pois G02 e G02a precisam dele

https://github.com/nfephp-org/nfephp/blob/master/libs/NFe/ConvertNFePHP.class.php#L693

linha 693:
//                    if (!empty($dados[1])) {   // sempre precisa gerar $xLgr
                        $xLgr = $dom->createElement("xLgr", $dados[1]);
                        $entrega->appendChild($xLgr);
//                    }

**Comment by robmachado** [comment]
Isso e o campo também não pode ser vazio !!! portanto não acredito ter que fazer nada nesse caso.

**Comment by rspadim** [comment]
postei pois não estava com o manual, entao nesse caso vamos ter que deixar uma variavel apontando pra onde deve ser incluido o g02a/g02

**Comment by robmachado** [comment]
Robertão ... você deveria ver e usar as classes de DEVELOP
