### ISSUE TITLE
Convert Develop

### ISSUE THREAD

**Issue by eduardokum** [nfephp-org/nfephp#586]
Olá, a classe ConvertNFe ja esta feita para as ultimas notas técnicas? por que na versao master a classe ConvertNFePHP em case "I":  ele ja trata por exemplo o campo NVE ja na que esta em develop ele não tem esse campo na função iEntity 

```
$this->make->tagprod(
            $this->nItem, //nItem
            $aCampos[1], //cProd
            $aCampos[2], //cEAN
            $aCampos[3], //xProd
            $aCampos[4], //NCM
            $aCampos[5], //EXTIPI
            $aCampos[6], //CFOP
```

ele pula do EXTIPI para o CFOP, teria que ter um NVE segundo o manual do TXT 3.1, como é no master. estou enganado ou teria alguma nova NT que desconheço?

Obrigado

**Comment by robmachado** [comment]
O NVE tem um método a parte ...


public function tagNVE($nItem = '', $texto = '')


Roberto

**Comment by robmachado** [comment]
E em ConvertNFe


/**
 * i05aEntity
 * Cria a tag NVE
 * @param array $aCampos
 */
protected function i05aEntity($aCampos)
{
    //I05A|
    $this->make->tagNVE($this->nItem, $aCampos[1]);
}

Roberto

Em 1 de junho de 2015 15:52, Roberto Machado <linux.rlm@gmail.com> escreveu:

> O NVE tem um método a parte ...
>
>
> public function tagNVE($nItem = '', $texto = '')
>
>
> Roberto
>
>


-- 
Roberto

*Nisi utile est quod facimus stulta est gloriae* (Julius Phaedous)

**Comment by eduardokum** [comment]
Eu vi isso, então substituiu não passa mais na I, mesmo no schema tendo a opção de NVE para o elemento... foi movido para uma tag separada é isso 

Vlw.
