### ISSUE TITLE
Erro na geração do DANFE, só aparecem 4 itens de uma NF-es que tem 5 itens

### ISSUE THREAD

**Issue by gugacarmellino** [nfephp-org/nfephp#587]
Olá, boa noite!

Estou com um erro na geração do Danfe. A NF-e tem 5 itens mas no Danfe só aparecem 4...

Segue o link do xml:
https://www.dropbox.com/s/v9huhc97zy6gi0u/35150545985371000108550200006334001634240206.xml?dl=0

**Comment by robmachado** [comment]
Na logica usada existe um erro, quando o tamanho do campos dos itens é exatamente igual ao total usado havia um salto e pulava o ultimo item. Isso foi corrigido agora e se a pagina atual é a ultima todos os campos restantes serão impressos.
Isso deve resolver até que essa classe seja refatorada e melhorada pois os cálculos e a logica utilizada contêm falhas.
Atualize sua classe e teste.
