### ISSUE TITLE
erro de dependencia no composer 

### ISSUE THREAD

**Issue by uelei** [nfephp-org/nfephp#590]
tentei instalar(develop) via composer da um erro na dependencia mpdf 
```shell
composer require 'nfephp-org/nfephp:4.0.*@dev'
```

```shell
    - nfephp-org/nfephp 4.0.x-dev requires mpdf/mpdf dev-master -> no matching package found.
```

**Comment by uelei** [comment]
no meu caso resolvi tb colocando como require "mpdf/mpdf":"dev-master"

**Comment by robmachado** [comment]
Já fiz uma correção para usar o mpdf stable, não irá mais causar esse erro
