### ISSUE TITLE
Consulta NFSe SP - safeCertContext

### ISSUE THREAD

**Issue by Verhaeg** [nfephp-org/nfephp#595]
Olá,

estou com problemas para consultar tanto notas emitidas quanto recebidas na NFSe Paulistana..
Estou tentando várias possibilidades de configuração mas não cheguei a nenhum resultado satisfatório com a biblioteca:

Caso 1: Consultar notas recebidas
* Destinatario em São Carlos (com certificado A1)
* Configuro a classe com os dados do cliente
* Chamo a função *queryNFeReceived* com os dados do prestador
* Erro que recebo: **Server was unable to process request. ---> safeCertContext is an invalid handle.**

Se eu troco os dados, exceto pelo certificado, eu recebo a mensagem de que a inscrição municipal é inválida (já que ele passa a usar a inscrição municipal de São Carlos).

Eu não tenho neste caso o certificado do prestador, apenas do destinatario, é possível fazer esta consulta?

Caso 2: Consultar notas emitidas
* Remetente situado em São Paulo, com certificado A1
* Instancio a classe com os dados do cliente
* Chamo a função *queryNFeIssued* com os dados do remetente
* Recebo o erro: **Server was unable to process request. ---> safeCertContext is an invalid handle.**

Ainda não consegui efetuar nenhuma chamada ao WS com sucesso
Alguma solução para isso? Preciso de alguma informação extra?

obrigado

**Comment by robmachado** [comment]
A que eu saiba ... não existem webservices para isso nas prefeituras. Ou
seja caso o Destinatário queira ver sua NFSe deverá faze-lo através do site
da prefeitura.

Quando a outros problemas teria que ser estudado caso a caso pois os
sistemas das prefeituras não tem um "padrão" de fato, cada prefeitura adota
e modifica um dos 20 "quase padrões" existentes para NFSe.

Para debugar corretamente você deve conhecer bem SOAP, cURL, PKCS12 e
usando o XDebug estudar passo a passo o que está ocorrendo, além é claro de
ter conhecimentos fortes em XML e OpenSSL.

Roberto

**Comment by Verhaeg** [comment]
Oi Roberto,
então, estes problemas estou tendo apenas com a nota paulistana, a qual o WS fornece (ao menos a documentação oficial, o WSDL e a class aqui, indicam ter suporte) a consulta tanto de notas de serviço emitidas quanto recebidas.
Para o Ginfes não tive problemas, só trabalhei por outro caminho, mas estou com problemas com a paulistana, utilizando a classe NFSeSP.

Tentei olhar tanto a classe presente no projeto, quanto a primeira versão dela que esta em outro projeto do GitHub, mas não achei nenhuma solução ainda. Meu problema não é ainda no tratamento do XML de NFSe, mas para obter o mesmo, sendo que não consegui ainda nem mesmo pegar as notas emitidas por um cliente de São Paulo.

Gostaria de saber se alguém teve sucesso com a consulta de NFSe e se sim, como conseguiu, quais parametros usou e nao usou

Obrigado
