### ISSUE TITLE
Tamanho do campo sobrepondo texto

### ISSUE THREAD

**Issue by delliriun** [nfephp-org/nfephp#605]
Tamanho dos campos do arquivo `install/index.php` está sobrepondo a descrição á direita.
(*offtopic:* deveria ter alguma label para `pouco importante`)

**Comment by robmachado** [comment]
No chrome não encontro essa sobreposição ?!?!

**Comment by robmachado** [comment]
Nem no chromium e nem no Firefox !?!?  e o que quer dizer com label para pouco importante ?!?

**Comment by delliriun** [comment]
Quiz dizer que não tem grande relevância para a API. Quanto ao erro, vou checar quando chegar em casa, mas acredito que acontece na resolução `1024x768`, navegadores: `chrome 44.0.2403.52`, `chromium  42.0.2283.0` no SO Windows 7.
![erro phpnfe](https://cloud.githubusercontent.com/assets/9023793/8252875/30cc035c-1660-11e5-9c02-28768fc77d7b.png)

**Comment by robmachado** [comment]
Vixe !!!

Não uso essa resolução a uma decada, nem testei nessas condições. Todas as
maquinas que tenho nos meus clientes e onde tenho acesso tem telas
widescreen.
Mas acredito que não impeça o funcionamento.

Roberto

**Comment by delliriun** [comment]
Sim, foi por isso que sugeri uma *tag* para *issues* com pouca relevância para a API.
Deixe o *issue* aberto que sábado a tarde eu resolvo.

**Comment by delliriun** [comment]
Corrigido em: #615
