### ISSUE TITLE
Adoçao da PSR

### ISSUE THREAD

**Issue by williamespindola** [nfephp-org/nfephp#606]
Vi que há algumas pendências da completa adoção da [PSR](http://www.php-fig.org/), mas não sei se a adoção completa é o objetivo. 
Há problemas como:
- Nomenclatura de arquivos (.class.php por exemplo)
- Namespaces
- PSR-4

**Comment by williamespindola** [comment]
Opa mancada minha! O Develop esta estes problemas ja foram tratados. 
Mas para eu me situar qual o nível da adoção hoje?

**Comment by robmachado** [comment]
Veja em DEVELOP e não em master

Roberto

**Comment by robmachado** [comment]
Acredito que alto para PSR-2 e PSR-4 em DEVELOP

É claro que ainda existe muita melhoria a ser feita usando os princípios
SOLID e faltam muitos testes unitários (phpunit) pois ainda não consegui me
adaptar para desenvolver em TDD, inclusive me faltam conhecimentos do uso
do phpunit.

Vários problemas pode ser vistos em
https://scrutinizer-ci.com/g/nfephp-org/nfephp/?branch=develop que devem
ser resolvidos para a melhoria do código.

E a refatoração de MDFe e CTe ainda está em andamento (de forma lenta)

Roberto

**Comment by williamespindola** [comment]
Consegue me esclarecer suas dificuldades com o phpunit em relação ao que esta sendo feito? Fica mais fácil para eu ajudar.

**Comment by robmachado** [comment]
Quer fazer um hangout ?

Em 19 de junho de 2015 09:04, William Espindola <notifications@github.com>
escreveu:

> Consegue me esclarecer suas dificuldades com o phpunit em relação ao que
> esta sendo feito? Fica mais fácil para eu ajudar.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/nfephp-org/nfephp/issues/606#issuecomment-113491395>.
>



-- 
Roberto

*Nisi utile est quod facimus stulta est gloriae* (Julius Phaedous)

**Comment by williamespindola** [comment]
Quando?

**Comment by robmachado** [comment]
Pode ser agora se estiver disponível !

**Comment by williamespindola** [comment]
Agora esta apertado. Entra no gitter ai combinamos.

**Comment by robmachado** [comment]
Pode ser amanha a tarde, mas não sei nem nunca usei esse Gitter, quem
colocou na pagina foi o Walker. Eu uso do Google.

Adiantando sobre PHPUNIT

Faltam testes sobre as classes NFe, e rever e melhorar os testes das
classes Common. Para aumentar a cobertura dos testes e evitar falhas em
atualizações.
É só olhar na pasta test para ver o que já está feito.

Roberto

**Comment by williamespindola** [comment]
@robmachado como falei para você, os métodos precisam ser apenas uma responsabilidade para poderem ser testados de forma unitária, vamos pegar um exemplo [NFePHP\MDFe\ToolsMDFe addProtocolo](https://github.com/nfephp-org/nfephp/blob/develop/libs/MDFe/ToolsMDFe.php#L101)

Podemos começar pelos parâmetros deste método, todos são opcionais, e o primeiro fator de excesso de responsabilidade.
Olhando sem analizar, suas 90 linhas ja fica óbvio o excesso de responsabilidade, mas vamos analizar.
Há alguns comentários que praticamente citam onde as responsabilidades estão:
- carrega a MDFe 
- carrega o protocolo
- carrega dados da NFe
- carrega os dados do protocolo
- cria a NFe processada com a tag do protocolo
- cria a tag nfeProc
- estabele o atributo de versão
- estabelece o atributo xmlns
- inclui a tag MDFe
- cria tag protNFe
- estabele o atributo de versão
- cria tag infProt
- salva o xml como string em uma variável
- remove as informações indesejadas

E possível sacar estas responsabilidades, isto deveria esta separados em métodos e objetos e ai sim é possível testar de forma unitária. Quando legibilidade? Vai melhorar 100% a manutenção, objetividade, prevenção, "testabilidade"... 

A idéia do teste unitário é você testar todos os possíveis resultados que aquele método pode retornar, se você tem este excesso a variação de resultado vai ser enorme, e dificulta a criação do teste, agora se eu tenho um método único para carregar a MDFe por exemplo, fica mais fácil saber que eu posso ter duas excessões apenas, e se escreve muito menos linhas para testar isto.

**Comment by walkeralencar** [comment]
Willian, se vc pegar os históricos antigos do projeto, fiz uma iniciativa sobre isso, mas não foi bem aceita na época.

Para ser sincero, eu partiria para uma perspectiva de comecar a projetar uma versao pensando no PHP7, reescrevendo toda a biblioteca, isso foi discutido e até iniciado ano passado mas parou.

**Comment by robmachado** [comment]
Vamos lá .... 

Primeiro o amigo está enganado na sua analise superficial, o método addProtocolo() não tem mutias funções, faz uma unica coisa ADICIONA O PROTOCOLO ao xml da NFe. E não é viável nem necessário tentar subdividir esse método em particular. E é um dos métodos mais fáceis para fazer teste unitário usando o phpunit.

Quanto ao PSR na versão refatorada acredito que atende em muito os padrões, e também atende algumas coisas do PHP7. (que estou estudando)

É claro que tem muita coisa a melhorar e sempre terá, mas temos que ser e ter:
- Objetividade (fazer uma coisa de cada vez)
- Real colaboração (e não só conversa)
- Envolvimento e participação (hangouts e estabelecimento de parâmetros, padrões)
- Usar realmente as classes (não dá para construir algo que você nunca usou e não entende a finalidade real)
- Pragamatismo (as coisas primeiro tem que funcionar bem e depois serem continuamente melhoradas)
