### ISSUE TITLE
Conversão da versão dos leiautes para texto

### ISSUE THREAD

**Issue by delliriun** [nfephp-org/nfephp#609]
Notei que a versão dos leitautes estão do tipo `double`, porém isto fáz algumas informações ficarem incongruentes, como:
```php
// aqui a versão se torna 3.1 já que o php arredonda
public $versao = 3.10;
```
`3.1 != 3.10` se tratando de versão, pode causar erro na SEFAZ, @robmachado o que acha da alteração?

**Comment by robmachado** [comment]
Isso são detalhes que devem ser tratados assim que localizados. Não vejo nenhum problema em colocar essa variável como STRING desde que todas as chamadas a essa variável estejam ajustada para esse caso.
