### ISSUE TITLE
Renovação da classe de certificados

### ISSUE THREAD

**Issue by lpj145** [nfephp-org/nfephp#617]
Machado, continuo a agradecer pelo desenvolvimento e por manter as coisas funcionando, eu analisei a classe Common/Certificate, não entendi bem a forma como são tratados, os documentos fiscais só precisam da chave privada certo? ( se estiver errado corrija me ). Analisando a classe percebi a repetição de funções e existe uma grande preocupação a saber se o arquivo é verdadeiro e se existe uma chave publica, será que a forma de adoção aos certificados não poderia ser de uma forma mais responsável? sem o uso de arquivos pem, somente pkcs12?

**Comment by robmachado** [comment]
Para tirar duvidas este não é o canal mais indicado use o Grupo.

Não .. você não esta certo, para qualquer tarefa usando certificados é necessário o uso de ambas as chaves PUBLICA e PRIVADA

PKCS12 é formato de transporte apenas nenhuma aplicação usa ou pode usar diretamente esse formato, existe sempre algum tipo de conversão interna. O PHP somente trabalha com o formato PEM e algumas funções do PHP somente utilizam certificados em ARQUIVOS (files) em formato PEM pois não consegue usar "resources" ou strings em memoria.

Saber se o certificado PERTENCE ao usuário e se é VALIDO é de estrema importância pois os servidores nem sempre retornam ERROS "entendiveis" quando uma  dessas condições não é satisfeita.

Quanto ao PERIGO dessa conversão compartilho com você essa preocupação e por isso essas certificados devem ser mantidos FORA do alcance de intrusos, mas isso é responsabilidade da APLICAÇÃO e não da API.

Para novos questionamentos use o grupo por favor
