### ISSUE TITLE
Novas URLs da SEFAZ RS

### ISSUE THREAD

**Issue by fmertins** [nfephp-org/nfephp#628]
Olá, no site da SEFAZ RS tem um aviso geral desde o dia 1º deste mês:
www.sefaz.rs.gov.br

As URLs da SEFAZ RS já foram atualizadas no Portal Nacional da NF-e, ambos os ambientes produção e homologação.

Neste link publicaram as novas URLs completas, não sei se todas mudaram, acredito que apenas algumas:
https://www.sefaz.rs.gov.br/site/MontaDuvidas.aspx?al=l_rel_end_ws_nfe

Precisamos revisar e atualizar os nossos arquivos de configuração dos webservices.

**Comment by robmachado** [comment]
Fernando;

Já atualizei ! para NFe mas acho que tem mais !!!

Roberto

**Comment by gersonfs** [comment]
Olá Roberto,

tem as URLs para NFC-e também. Agora os webservices da NF-e não autorizam mais NFC-e, vi isso por acaso, pois estava pegando o arquivo nfe_ws3_mod55.xml para autorizar NFC-e e deu erro de modelo diferente de 65.

**Comment by robmachado** [comment]
É claro meu amigo é por isso que existe um nfe_ws3_mod65.xml



Em 3 de julho de 2015 15:07, Gerson Felipe Schwinn <notifications@github.com
> escreveu:

> Olá Roberto,
>
> tem as URLs para NFC-e também. Agora os webservices da NF-e não autorizam
> mais NFC-e, vi isso por acaso, pois estava pegando o arquivo
> nfe_ws3_mod55.xml para autorizar NFC-e e deu erro de modelo diferente de 65.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/nfephp-org/nfephp/issues/628#issuecomment-118403179>.
>



-- 
Roberto

*Nisi utile est quod facimus stulta est gloriae* (Julius Phaedous)

**Comment by gersonfs** [comment]
Percebi hehehe

**Comment by robmachado** [comment]
Fernando eu atualizei tanto pra NFe como para CTe (branchs Master e Develop) me parece que foram as únicas alterações se puder testar eu agradeço.

Abraço

**Comment by fmertins** [comment]
Boa tarde, maravilha Roberto obrigado! Estou atualizando minha aplicação de NF-e Entrada e vou testar. Eu até ia tentar fazer as alterações mas você se antecipou :-)

**Comment by fmertins** [comment]
Olá, retomando para concluir, a princípio tudo certo.
