### ISSUE TITLE
Itens fora da margem na última página do DANFE

### ISSUE THREAD

**Issue by neilvilela** [nfephp-org/nfephp#635]
Na última página, vários itens estão saindo fora da margem, ao ponto de vários não aparecerem.

![screen_shot_2015-07-14_at_3_06_19_pm](https://cloud.githubusercontent.com/assets/761956/8680919/e06bd074-2a3a-11e5-821e-f703f7711bd7.png)

Fiz alguns experimentos e consegui imprimir corretamente revertendo o commit 448af60df682ecba1cdc968e0d7dfa6b2a28f09b no meu projeto. Tentei outras coisas além disso, mas acho que não conheço o suficiente de PHP para rastrear este problema.

![screen_shot_2015-07-14_at_3_06_01_pm](https://cloud.githubusercontent.com/assets/761956/8681139/1defd304-2a3c-11e5-9659-e66fd100e20e.png)

Enviei o mesmo XML para o webdanfe.com.br, que usa o NFePHP, e vi uma diferença: os produtos lá não possuem uma margem no fim do valor dos produtos, quando estes possuem infAdProd, e isso foi o suficiente para o DANFE ser impresso em 4 páginas. Imagino que essa quebra de linha não esteja sendo calculada na contagem de páginas, e isso gere o problema.

Alguém passou por algo parecido e tem alguma ideia de como resolver o problema?

**Comment by robmachado** [comment]
passe o xml EM ANEXO para testes

Roberto
