### ISSUE TITLE
Itens repetindo na segunda página do Danfe.

### ISSUE THREAD

**Issue by gugacarmellino** [nfephp-org/nfephp#638]
Fala Roberto, bom dia!

Aconteceu novamente o erro na geração do Danfe. Os itens de uma página estão sendo repedidos em outra página.

Segue links de dois xml: https://www.dropbox.com/s/brkg9m463ub9z3q/35150509028217000184550040000007881700082004-procNfe.xml?dl=0

https://www.dropbox.com/s/o8fg3aloq0v7ina/35150509028217000184550020000066961700082005-procNfe.xml?dl=0

Estou gerando em Retrato e A4

**Comment by robmachado** [comment]
Não tenho conta no DropBox e nem terei por isso não consigo pegar seu
arquivo

Roberto

**Comment by gugacarmellino** [comment]
Entendi,

Coloquei na Amazon S3: 
https://s3-us-west-2.amazonaws.com/recebaemcasabkp/35150509028217000184550020000066961700082005-procNfe.xml

https://s3-us-west-2.amazonaws.com/recebaemcasabkp/35150509028217000184550040000007881700082004-procNfe.xml

**Comment by robmachado** [comment]
Tem uma forma de "consertar" temporariamente o problema, mas isso não irá solucionar esse tipo de problema, apenas é uma solução para esse caso em particular.

Branch MASTER
Altere a linha 755
$hUsado += round(($numlinhas * $this->pdf->FontSize) + ($numlinhas * 0.48), 2);

Branch DEVELOP
Altere a linha 692
$hUsado += round(($numlinhas * $this->pdf->FontSize) + ($numlinhas * 0.48), 2);
