### ISSUE TITLE
NfeConsultaDest

### ISSUE THREAD

**Issue by eduardokum** [nfephp-org/nfephp#646]
Olá, o brach develop não tem o metódo para o serviço NfeConsultaDest???

**Comment by robmachado** [comment]
A branch DEVELOP, é uma refatoração para se adequar mais aos padrões PSR-2,
PSR-4 e aos princípios SOLID.

Nessa refatoração, o nome das Classes e dos métodos foram alterados, todos
os acessos a SEFAZ iniciam com "sefazXXX", nesse caso passou a ser
"sefazDistDFe()".

A branch DEVELOP será migrada aos poucos para a nova estrutura denominada
sped, onde teremos :

nfephp-org/sped-nfe
nfephp-org/sped-mdfe
nfephp-org/sped-cte
nfephp-org/sped-common

A instalação será feita preferencialmente via "composer" e note que  os
namespaces também serão refatorados nessa migração.
Ainda não tem prazo para isso acontecer.

Roberto
