### ISSUE TITLE
NFSe funcional?

### ISSUE THREAD

**Issue by jozephbrasil** [nfephp-org/nfephp#668]
Galera, a NFSe no repositório develop está funcional? No Master tem um aviso dizendo que nem tente usar em produção. Vi que no develop a estrutura é completamente diferente (ela foi re-escrita), então nem adianta investir na antiga.

**Comment by guicalabria** [comment]
Bom dia.
 Até onde eu saiba o NFS-e não tem um mantenedor oficial, por isso está
abandonado.
 Eu já o uso por alguns anos, sem muitos problemas, que quando ocorrem as
pessoas postam aqui.
 Eu uso para São Paulo e para prefeituras do sistema Ginfes.

Abraços!


Em 13 de setembro de 2015 12:43, jozephbrasil <notifications@github.com>
escreveu:
