### ISSUE TITLE
Disponibilizar releases

### ISSUE THREAD

**Issue by renatoargh** [nfephp-org/nfephp#684]
Apenas a release 2.00 está disponível aqui no GitHub. Eu sei que eu poderia baixar o `master` e sair usando mas eu não gosto de fazer isso porque frequentemente os devs (de qualquer projeto) comitam código quebrado na master. 

Eu gostaria de saber se você pretendem disponibilizar mais releases, ou se pelo menos poderiam apontar quais commits estão estáveis?

Miinha sugestão é que o projeto adote o [versionamento semântico](http://semver.org/)

PS.: Venho utilizando este projeto com grande satisfação! Ótimo trabalho! Valeu!

**Comment by robmachado** [comment]
Para NFe branch DEVELOP está estável, será passada para MASTER (faltou
tempo)

As releases 2.00 não é mais funcional e a 3.10 não será mais mantida agora
será a 4.00 (DEVELOP)

Roberto

**Comment by renatoargh** [comment]
Entendi, devo usar o último commit da branch `develop` que está estável, certo? 

Uma boa maneira de indicar para os usuários da lib que em tal commit o código está bom para ser usado é criando as releases do GitHub. É muito facil, dá uma olhada aqui: [Creating Releases](https://help.github.com/articles/creating-releases/), assim fica mais claro para os devs além de ser uma maneira padronizada no GitHub.

Valeu, obrigado pela resposta rápida!

**Comment by robmachado** [comment]
Renato; 
Primeiro obrigado pelas suas dicas, são úteis. 
O que ocorre, é que em virtude de muitos comentários, houve uma GRANDE mudança entra as versões anteriores e a atual. Com muito pouca colaboração na manutenção dos códigos. É só olhar quem fez os commits, e eu tenho que trabalhar para viver. Mas o que você está dizendo é o que eu quero fazer, já a algum tempo. Vou tentar arranjar um tempo para faze-lo essa semana.
Um outro problema que ocorre são as alterações de versão advindas da SEFAZ, quando isso acontece a versão anterior QUEBRA além de qualquer reparo, principalmente com um código tão ruim quanto o da versão 2.00.

As classes foram refatoradas para aplicar os princípios SOLID  e as PSR na branch DEVELOP e uma nova versão já está em gestação denominada SPED com cada elemento do SPED (NFe, CTe, MDFe, CLe, EFD, NFSe, ...) sendo tratado em um diferente repositório. Isso será mais uma mudança de paradigma. 

Estou sempre aberto a sugestões e ajuda.
Abraço

**Comment by renatoargh** [comment]
Entendo perfeitamente. Novamente, agradeço pelo seu trabalho. Abraço!
