### ISSUE TITLE
Erro ao Incluir infNFeSupl (Tag QR Code)

### ISSUE THREAD

**Issue by dafdesig** [nfephp-org/nfephp#696]
Ola tudo bem?

Quando descomento a linha que inclui o QR Code no xml, a NFC-e é gerada e assinada (com a tag 
infNFeSupl),  porém ao validar o xml com o metodo validarXML é apresentado o erro abaixo:

Elemento 'infNFeSupl': Este elemento não é esperado. Esperado é ( {http://www.w3.org/2000/09/xmldsig#}Signature ).

Atenciosamente,
Daniel

**Comment by robmachado** [comment]
Não há erro se utilizar o pacote de schemas corretos PL_008h

**Comment by dafdesig** [comment]
Obrigado!
