### ISSUE TITLE
Visão do projeto

### ISSUE THREAD

**Issue by dirtyman** [nfephp-org/nfephp#705]
Olá,

Parabéns ao autor e os contribuidores que conseguiram tornar este projeto o maior de todos (pelo fato de ser open source e php, que é amplamente utilizada). Porém, eu gostaria de citar duas coisas que eu considero extremamente importante para qualquer projeto:
- Interface
- Documentação

A nível de usuário, de quem vai utilizar uma API dita pública, a interface é _horrível_ o que torna a documentação difícil (e talvez, justamente por isso, não existe documentação).

Então o usuário que apenas queria utilizar a interface acaba tendo que ler o código para entender _como_ fazer a biblioteca funcionar (código o qual, na minha opinião, muito difícil de entender, com práticas procedurais (que acabam tornando-se más práticas)).

Mesmo que a interface não seja clara o suficiente, a documentação _really matter_, então talvez apenas isso já resolveria o problema (e provavelmente a maioria dos google groups).

Quando falo em documentação eu quero dizer:
- Uma tabela sobre cada classe, com os seus métodos públicos.
- Um exemplo (atual!) sobre a utilização de cada funcionalidade.
- Um report sobre como criar tópicos com problemas (debug)(para facilitar qualquer nova necessidade).
- Documentação atual (novamente!) sobre o estado do projeto, o que funciona e o que não funciona.

Agora, eu entendo que o projeto é open source. E geralmente quem contribui para ele pode mais tarde citar isso para qualquer cliente/empresa. Porém não é lá um belo projeto com uma interface limpa para os usuários REALMENTE utilizarem ela.

_Pessoas que realmente interagem com ela, constantemente, seriam os mais propensos a rever estes pontos dada a facilidade inicial. No meu caso, eu sou apenas um usuário frustado, por precisar entender o código da biblioteca para utilizá-la._

**Comment by walkeralencar** [comment]
Olá, 

Vou apenas resumir a história, o projeto começou em 2009, naquela época foi proposto, utilizar o padrão de codificação da Zend, mas o principal contribuidor, manteve a linha de fazer o projeto de forma mais simples para ele, caso outras pessoas quisessem, ajustar isso poderiam fazer, porém, por muito tempo o Roberto, fez o projeto atendendo suas necessidades e disponibilizando o código para quem quisesse utilizar, e se fosse comigo teria feito da mesma forma.

1. O projeto não é visual, é uma biblioteca que trabalha em Backend, visual tem apenas a instalação.
2. Caso tenha interesse em acompanhar as discussões do grupo, vai descobrir que está sendo planejado e trabalhado uma nova versao, baseada nas PSRs.
3. Caso leia a documentação, descobrirá que há uma pasta contendo exemplos de todas as funcionalidades do projeto.
4. Quando fizer uma crítica tenha em mãos uma proposta de solução, se for apenas criticar e não fazer nada, guarde a crítica para sí.
5. Sinta-se à vontade, para gerar toda e qualquer melhoria e documentação, faça um Merge Request, que avaliaremos e aprovaremos.

Até a próxima

**Comment by dirtyman** [comment]
Respondendo os itens:

1. Interface não é visual. Conforme a wikipedia `..o conjunto de meios planejadamente dispostos sejam eles físicos ou lógicos com vista a fazer a adaptação entre dois sistemas...`. Uma interface limpa, objetive torna o sistema mais fácil. Ou seja, é a _maneira_ de como o usuário se comunica com a biblioteca (instâncias, métodos, dependências, etc.)

2. Sim, e nesse ponto mesmo eu posso argumentar:

- O que quer dizer no README, de que a versão atual é a versão 4.0.x? Porém ela diz desenvolvimento, devo utilizar em produção? Até porque a 3.10 tem tag de obsoleta, porém o CTe não está completo na 4.10, devo usar a 3.10? Será que ela está atualizada? Mas eu leio obsoleta. Não sei.

3. De novo, eu citei isso quando eu digo refraseio que não existe código refletindo o estado atual da aplicação. Os exemplos apenas existem no 3.10, e os mesmos estão incompletos e clarifica _quase_ nada.

4. Bom, eu dei soluções. Documentação e interface. Citei algumas dicas de melhorias.

5. Eu também respondi isso, de quem seria mais prominente para fazer essas tarefas. Eu sou apenas um usuário.

Uma analogia:
- Eu sou um engenheiro. Imagine que todos os eletrodomésticos que eu compro, necessitam de um engenheiro para entender como ligá-los. Uma máquina de lavar por exemplo, preciso entender toda a estrutura dela apenas pra chegar no meu objetivo final: lavar roupas. Seria muito mais fácil, se a mesma tivesse um manual ou um botão de ligar.

**Comment by robmachado** [comment]
Prezado;

1 - Interface não é visual. Conforme a wikipedia ..o conjunto de meios
planejadamente dispostos sejam eles físicos ou lógicos com vista a fazer a
adaptação entre dois sistemas.... Uma interface limpa, objetive torna o
sistema mais fácil. Ou seja, é a *maneira* de como o usuário se comunica
com a biblioteca (instâncias, métodos, dependências, etc.)
*Perfeito faça um PULL REQUEST será muito bem vindo*

2 -  Sim, e nesse ponto mesmo eu posso argumentar:

   -

   O que quer dizer no README, de que a versão atual é a versão 4.0.x?
   Porém ela diz desenvolvimento, devo utilizar em produção? Até porque a 3.10
   tem tag de obsoleta, porém o CTe não está completo na 4.10, devo usar a
   3.10? Será que ela está atualizada? Mas eu leio obsoleta. Não sei

*A versão 4.0.x é desenvolvimento, na branch Master e na branch Develop. As
versões são validas e usáveis para NFe apenas. Essa API depende das REGRAS
da SEFAZ que mudam constantemente portanto está m constante
DESENVOLVIMENTO. *
*A TAG 3.10 - Obsoleta esta versão não mais funciona com as novas
alterações da SEFAZ e a API está sendo reestruturada para ser aderente aos
PSR e aos principios SOLID.*
*Eu uso apenas a NFe, NINGUÉM se candidatou a ajudar na revisão do CTe e do
MDFe, ferramentas que não sou usuário, não tenho nem forma de testar
adequadamente para ajustar essas ferramentas. Portanto estão com as
versões paralisadas em 3.10  e não funcionais em 4.0.x, até que sejam
refatoradas por algum interessado.*

3 - De novo, eu citei isso quando eu digo refraseio que não existe código
refletindo o estado atual da aplicação. Os exemplos apenas existem no 3.10,
e os mesmos estão incompletos e clarifica *quase* nada.
*A versão 4.0.x contém exemplos de uso para a sua parte funcional a qual
mantenho pessoalmente NFe*

4 - Bom, eu dei soluções. Documentação e interface. Citei algumas dicas de
melhorias.
*Perfeito novamente faça um PULL REQUEST estou ansioso para validar e
publicar*

5 - Eu também respondi isso, de quem seria mais prominente para fazer essas
tarefas. Eu sou apenas um usuário
*Se é apenas um usuário, que deve ser obrigatoriamente também um
programador, tem perfeitas condições de colaborar, e não apenas com idéias
e propostas, mas também com ações reais*

*6 - Sua analogia não está correta, a API não é uma maquina de lavar. É um
peça de programação que requer conhecimentos, investigação e conhecimentos
por parte de seu usuário e nesse caso SIM o usuário tem que ser um
especialista técnico e conhecedor para poder usar.*

Um projeto OpenSouce depende de ajuda real, eu não ganho nenhum centavo
para manter essa API, uso meu tempo livre para manter e auxiliar quem
necessita e eu também necessito de ajuda real para todas essas suas
sugestões.

Portanto aguardo ansioso sua colaboração real

Roberto

**Comment by dirtyman** [comment]
Eu pesquisei nos issue e nos grupos, e estou ciente que algumas peças ainda faltam. O que eu questionei de verdade foi a interface e a documentação.

Todos estes detalhes que @robmachado comentou, estão escondidos nos tópicos/issues. Não existe um lugar claro da situação atual do projeto.

De novo, eu como apenas um usuário queria utilizar a biblioteca, agora eu devo entender ela primeiro para utilizar e talvez, mais tarde colaborar com o projeto (a falta da mesma, até dificulta os próprios contribuidores).

O objetivo inteiro do meu issue foi dar uma crítica construtiva de como o projeto poderia melhorar de forma significativa, se eu falhei nisso, desculpe-me.

_Na verdade a minha analogia está correta. Uma analogia da analogia poderia ser feita com o facade pattern. O objetivo dele, deveria ser o objetivo de cada API público (o que é, na maioria dos casos). Para que complicar se pode simplificar?_

**Comment by tonicospinelli** [comment]
@dirtyman obrigado por constatar o que já era óbvio!

Já houve diversas discussões a respeito de refatoração para adequação a PSR e sem contar nas melhorias em OO.

Porém, infelizmente, neste projeto tem mais [galinha do que porco](https://en.wikipedia.org/wiki/The_Chicken_and_the_Pig), eu mesmo me sinto uma galinha, pois sei que poderia acrescentar e muito ao projeto, principalmente pelo poder que ele pode dar as empresas/devs que usam PHP como forma de renda. Não vou me justificar aqui, pois não vem ao caso.

Sim, você falhou, não na crítica, ela é válida, mas falhou em chegar "cagar" a regra de ser cordial e cuspir na cara de todos que fizeram o seu melhor (apesar de não ser o melhor código do mundo)
 
Se hoje existe essa lib é porque o @robmachado e outros colaboradores dispensaram milhares de horas para conseguir colocar esta lib onde está hoje!

Eu te desculpo, mas lembre-se o código é aberto, fork it e Pull Request, estamos precisando de mão que ajude. Se puder ajudar agradecemos.

**Comment by lerox** [comment]
E é bem isso o que o @tonicospinelli comentou: `lembre-se o código é aberto, fork it e Pull Request`. :sunglasses: 

Prefiro acreditar que o @dirtyman tenha sido infeliz em sua colocação e esquecer que li isso :/

**Comment by dirtyman** [comment]
Mandar a real para os "programadores" aqui:
- VOCÊS NÃO FAZEM A MÍNIMA IDEIA DO QUE ESTÃO FAZENDO.

Que código bosta! É sério. Meus olhos ardem tentando olhar essa merda!
Eu realmente tentei ser educado mas fica difícil quando AS CRIATURAS NÃO ASSUMEM o erro, e jogam pra frente.

"NOS SEGUIMOS AS MELHORES PRÁTICAS SOLID"' DA ONDE CARA????? DA ONDE????
Para de te iludar, pelo amor de deus!!!

Depois essa raça (sim, raça. Daqueles que não buscam melhorar, daqueles que preferem mentir pra si mesmos dizendo que não tem nada errado e a culpa é dos outros.) vem reclamar de salário de TI no brasil. VAI SABER PROGRAMADOR ANTES DE FALAR MERDA.

** É incrivelmente insuportável olhar pra essa biblioteca.
** Quando surgir outra biblioteca mais sustentável e acessível, saibam que fui eu.

** Porque não adianta CRIAR UMA IDEIA UTIL, SE ELA NÃO É ÚTIL DE VERDADE.

Com carinho, vão a merda.
Pra cada um que escreveu o código cagado que é essa biblioteca.

**Comment by tonicospinelli** [comment]
:clap: até excluiu a conta, @dirtyman seja feliz!

**Comment by walkeralencar** [comment]
Vou apenas ignorar, já que o "fantasma", é incapaz de ler e perceber que está sendo desenvolvido uma nova biblioteca baseada em PSRs e SOLID, onde claramente o Roberto cita: "a API está sendo reestruturada para ser aderente aos PSR e aos principios SOLID.*".
