### ISSUE TITLE
Classe ToolsNFe, identificação contingência offline

### ISSUE THREAD

**Issue by fmertins** [nfephp-org/nfephp#707]
Olá, revisando a classe `ToolsNFe` me parece que atualmente não tratamos a possibilidade de NFC-e autorizada com cStat=150, fora do prazo, nos casos de contingência offline. Fiz alguns "find" na Tools e BaseTools por "100" e "150" no sentido de encontrar os cStat e não tem nada relacionado ao 150.

Acredito que tenhamos que proceder quando cStat=150 na autorização, da mesma forma como já é feito no cStat=100, o que acham?

**Comment by robmachado** [comment]
Sim voce está certo 150 também é aprovado !!!

Em 4 de dezembro de 2015 09:31, Fernando Mertins <notifications@github.com>
escreveu:

> Olá, revisando a classe ToolsNFe me parece que atualmente não tratamos a
> possibilidade de NFC-e autorizada com cStat=150, fora do prazo, nos casos
> de contingência offline. Fiz alguns "find" na Tools e BaseTools por "100" e
> "150" no sentido de encontrar os cStat e não tem nada relacionado ao 150.
>
> Acredito que tenhamos que proceder quando cStat=150 na autorização, da
> mesma forma como já é feito no cStat=100, o que acham?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/nfephp-org/nfephp/issues/707>.
>



-- 
Roberto

*Nisi utile est quod facimus stulta est gloriae* (Julius Phaedous)

**Comment by robmachado** [comment]
Fernando ;

Não acredito ser necessária nenhuma alteração nas classes da API devido ao
cStat = 150.
Isso deve ter mais impacto sobre seu ERP

Mas caso você encontre algum problema me avise

Roberto

**Comment by robmachado** [comment]
Existe uma unica condição de teste no método verificaValidade() que já estou alterando para considerar o 150 também como valido
Acredito ser somente isso.

**Comment by robmachado** [comment]
Feito.  Se achar mais algum problema é só reabrir a ISSUE
