### ISSUE TITLE
Erros na classe MakeNFe

### ISSUE THREAD

**Issue by eduardokum** [nfephp-org/nfephp#714]
na linha 2491 tag com o nome de "ICMSFDest"  correto "ICMSUFDest", faltou o U
na linha 3027 tag com o nome de "vICMSUFRemt" correto "vICMSUFRemet", faltou o segundo e

**Comment by victorvilella** [comment]
Acho que este tipo de erro deveria ser reportado através de um pull request, não?

**Comment by eduardokum** [comment]
Tentei mais cedo fazer um pull request mais meu fork estava desatualizado mesmo eu atualizando ele antes de enviar, achei melhor criar por aqui até eu conseguir ver qual o problema no meu fork

**Comment by robmachado** [comment]
Pull Request Aceito 

OBRIGADÃO !!!!
