### ISSUE TITLE
Pasta /libs

### ISSUE THREAD

**Issue by rochapablo** [nfephp-org/nfephp#739]
Porque não separar a pasta /libs em um projeto mais independente?

**Comment by robmachado** [comment]
É isso ai PABLO, e isso que estamos começando a fazer veja em

https://github.com/nfephp-org

Todas os repositórios denominados sped-* irão conter os pedaços de cada
grupo de API's do SPED

Roberto

**Comment by rochapablo** [comment]
Putz que mancada minha! Bem melhor agora em.

Outra coisa...

Vi que existe a dependência ""zendframework/zend-mail": "2.4.*@dev"", mas no caso eu não estou usando zendframework e acredito que pode existir outros que vão utilizar diferentes frameworks.

Seria possível remover essa dependência separando o código que faz o envio de e-mail?

**Comment by robmachado** [comment]
Mesmo instalando o Zend-Mail não irá afetar sua aplicação ... caso não
queira instalar terá que manualmente remover essa dependência ... coisa que
não aconselho a fazer pois irá causar problema numa atualização da
biblioteca. E se não quiser usar basta ignorar a classe MailNFe.php

Roberto
