### ISSUE TITLE
tag $encerrante (MakeNFe linha 4024)

### ISSUE THREAD

**Issue by wilkerjosepereira** [nfephp-org/nfephp#741]
Tenho um cliente que revende óleo lubrificante, mas não é um posto de combustivel, assim sou obrigado a usar uma CFOP de venda de oleo/lubrificante e informar a tag a Comb mas não sou obrigado a informar a tag a aEncerrante.

Assim quando vou gerar o XML recebo um erro "Undefined offset: 1" na linha 4024 pois o como $this->aEncerrante não existe, this->aEncerrante[$nItem] retorna nulo.

alterei a linha 4024 da seguinte forma para resolver o problema:

$encerrante = $this->aEncerrante ? $this->aEncerrante[$nItem] : null;

Não sei se este é realmente um bug ou se foi a minha forma de gerar o xml que deu o erro, mas mesmo assim acho interessante que o "bug" seja verificado.

Espero ter podido colaborar

Atenciosamente

Wilker

**Comment by robmachado** [comment]
Atualize e teste para ver se resolveu o caso

**Comment by wilkerjosepereira** [comment]
resolveu sim Robson

Muito obrigado

**Comment by robmachado** [comment]
E não é Robson não é ROBERTO

OK

**Comment by wilkerjosepereira** [comment]
Ok roberto desculpe.... E que eu tinha respondido pelo github e la so
mostra robmachado ai achei q fosse robson. So vi o email agora.

Obrigado mais uma vez

Wilker
Em 15/01/2016 11:56, "Roberto L. Machado" <notifications@github.com>
escreveu:
