### ISSUE TITLE
Separar a lógica de alteração do texto adicional do Danfe->montaDANFE

### ISSUE THREAD

**Issue by wilsonglasser** [nfephp-org/nfephp#746]
Hoje o método Danfe::montaDANFE altera o texto adicional, toda a lógica da alteração está no método.

Em uma necessidade de estender o texto adicional é necessário replicar todo o método que na maioria da lógica contempla a formulação do PDF.

Eu gostaria de sugerir a separação do método a parte do código que altera a variável:
$this->textoAdic, ela está destoando da função do método em si.

**Comment by robmachado** [comment]
Wilson;
Primeiro é muito bom receber comentários, mostra interesse !
Segundo, realmente essa classe está "HORRIVEL", do meu ponto de vista, uma verdadeira bagunça e necessita ser REFATORADA por completo, pois não atende aos princípios do SOLID nem de boas práticas (como a que você sugere). 

Nós do grupo precisamos de bons programadores para nos ajudarem a fazer essas refatorações e melhorias tão necessárias.

**Comment by robmachado** [comment]
Danfe em processo de refatoração
