### ISSUE TITLE
Download XML

### ISSUE THREAD

**Issue by cristianocrc2** [nfephp-org/nfephp#747]
Estou tentando utilizar um arquivo de exemplo para download da nfe... o mesmo retorna o erro abaixo:

Fatal error: Uncaught exception 'NFePHP\Common\Exception\RuntimeException' with message 'Não houve retorno do Curl. Unknown SSL protocol error in connection to www.nfe.fazenda.gov.br:443 ' in C:\laragon\www\nota\nfe\libs\Common\Soap\CurlSoap.php:180 Stack trace: #0 C:\laragon\www\nota\nfe\libs\NFe\ToolsNFe.php(1694): NFePHP\Common\Soap\CurlSoap->send('https://www.nfe...', 'http://www.port...', '<nfeCabecMsg xm...', '<nfeDadosMsg xm...', 'nfeDownloadNF') #1 C:\laragon\www\nota\download.php(16): NFePHP\NFe\ToolsNFe->sefazDownload('421601025958940...', '1', '02595894000135', Array) #2 {main} thrown in C:\laragon\www\nota\nfe\libs\Common\Soap\CurlSoap.php on line 180

Sou novo no php, alguem poderia ajudar?

**Comment by tryvin** [comment]
Seu php tá atualizado? Com todos os protocolos SSL habilitados no curl?
Em 20/01/2016 12:59, "cristianocrc2" <notifications@github.com> escreveu:

**Comment by tryvin** [comment]
O Servidor da Fazenda usa uma versão antiga de TLS, e nem sempre ela tá habilitada no CURL

**Comment by cristianocrc2** [comment]
Entendi, tem alguma ideia de qual a versão do tls é usada? O Curl está habilitado aqui.

**Comment by tryvin** [comment]
cristiano, a Fazenda usa TLS 1.0, provavelmente seu Curl desabilitou esse protocolo.

**Comment by cristianocrc2** [comment]
Ok, deu certo, Obrigadão....
