### ISSUE TITLE
Rejeicao: Ambiente informado diverge do Ambiente de recebimento

### ISSUE THREAD

**Issue by celomamp** [nfephp-org/nfephp#748]
Boa noite

Estou com um xml assinado, enviado, porém quando tento enviar o retorno para receber o protocolo recebo o seguinte erro:

Rejeicao: Ambiente informado diverge do Ambiente de recebimento

Pensei que era porque estava num ambiente de homologação e o retorno ou o config.json ou a variável $tpAmb estavam setados para produção, porém após verificar constatei que todos estão setados para ambiente de homologação. O que pode estar acontecendo?

**Comment by tryvin** [comment]
Boa noite, poderia colocar o XML aqui? Esse tipo de erro acontece se no XML tiver como um ambiente, e na hora de enviar for outro

**Comment by celomamp** [comment]
<?xml version="1.0" encoding="utf-8"?>
<NFe xmlns="http://www.portalfiscal.inf.br/nfe"><infNFe versao="3.10" Id="NFe42160102595894000135550020000161411000000017"><ide><cUF>42</cUF><cNF>00000001</cNF><natOp>VENDA DE MERCADORIA ADQUIRIDA OU RECEBIDA DE TERCEIROS</natOp><indPag>0</indPag><mod>55</mod><serie>2</serie><nNF>16141</nNF><dhEmi>2016-01-19T13:48:20-02:00</dhEmi><dhSaiEnt>2016-01-19T13:48:20-02:00</dhSaiEnt><tpNF>1</tpNF><idDest>1</idDest><cMunFG>4208203</cMunFG><tpImp>1</tpImp><tpEmis>1</tpEmis><cDV>7</cDV><tpAmb>1</tpAmb><finNFe>1</finNFe><indFinal>0</indFinal><indPres>0</indPres><procEmi>0</procEmi><verProc>3.10</verProc></ide><emit><CNPJ>02595894000135</CNPJ><xNome>REPRETEC TRADING LTDA</xNome><xFant>REPRETEC TRADING LTDA</xFant><enderEmit><xLgr>RUA JOINVILLE</xLgr><nro>304</nro><xCpl>EDIFICIO ATHON</xCpl><xBairro>CENTRO</xBairro><cMun>4208203</cMun><xMun>ITAJAI</xMun><UF>SC</UF><CEP>88301410</CEP><fone>4733492261</fone></enderEmit><IE>254492061</IE><CRT>3</CRT></emit><dest><CNPJ>08807524000109</CNPJ><xNome>NF-E EMITIDA EM AMBIENTE DE HOMOLOGACAO - SEM VALOR FISCAL</xNome><enderDest><xLgr>RUA: URUGUAI</xLgr><nro>435</nro><xBairro>CENTRO</xBairro><cMun>4208203</cMun><xMun>ITAJAI</xMun><UF>SC</UF><CEP>88302201</CEP><fone>4733498599</fone></enderDest><indIEDest>9</indIEDest><email>alexandrerepretec@hotmail.com; GILBERTO@REPRETEC.COM.BR</email></dest><det nItem="1"><prod><cProd>25</cProd><cEAN/><xProd>ARAME RECOZIDO PRETO SIMPLES BWG12</xProd><NCM>72171090</NCM><CFOP>5102</CFOP><uCom>KG</uCom><qCom>1000.0000</qCom><vUnCom>3.2381</vUnCom><vProd>3238.10</vProd><cEANTrib/><uTrib>KG</uTrib><qTrib>1000.0000</qTrib><vUnTrib>3.2381</vUnTrib><indTot>1</indTot></prod><imposto><ICMS><ICMS00><orig>0</orig><CST>00</CST><modBC>3</modBC><vBC>3400.01</vBC><pICMS>17.00</pICMS><vICMS>578.00</vICMS></ICMS00></ICMS><IPI><clEnq>999</clEnq><cEnq>999</cEnq><IPITrib><CST>50</CST><vBC>3238.10</vBC><pIPI>5.0000</pIPI><vIPI>161.91</vIPI></IPITrib></IPI><PIS><PISAliq><CST>01</CST><vBC>3238.10</vBC><pPIS>1.6500</pPIS><vPIS>53.43</vPIS></PISAliq></PIS><COFINS><COFINSAliq><CST>01</CST><vBC>3238.10</vBC><pCOFINS>7.6000</pCOFINS><vCOFINS>246.10</vCOFINS></COFINSAliq></COFINS></imposto></det><total><ICMSTot><vBC>3400.01</vBC><vICMS>578.00</vICMS><vICMSDeson>0.00</vICMSDeson><vBCST>0.00</vBCST><vST>0.00</vST><vProd>3238.10</vProd><vFrete>0.00</vFrete><vSeg>0.00</vSeg><vDesc>0.00</vDesc><vII>0.00</vII><vIPI>161.91</vIPI><vPIS>53.43</vPIS><vCOFINS>246.10</vCOFINS><vOutro>0.00</vOutro><vNF>3400.01</vNF></ICMSTot></total><transp><modFrete>0</modFrete><vol><qVol>1</qVol><esp>1</esp><marca>1</marca><nVol>1</nVol><pesoL>1000.000</pesoL><pesoB>1000.000</pesoB></vol></transp><cobr><dup><nDup>16141/1</nDup><dVenc>2016-02-16</dVenc><vDup>3400.01</vDup></dup></cobr><infAdic><infAdFisco>INFORMACOES INTERESSE FISCO</infAdFisco></infAdic></infNFe><Signature xmlns="http://www.w3.org/2000/09/xmldsig#"><SignedInfo><CanonicalizationMethod Algorithm="http://www.w3.org/TR/2001/REC-xml-c14n-20010315"/><SignatureMethod Algorithm="http://www.w3.org/2000/09/xmldsig#rsa-sha1"/><Reference URI="#NFe42160102595894000135550020000161411000000017"><Transforms><Transform Algorithm="http://www.w3.org/2000/09/xmldsig#enveloped-signature"/><Transform Algorithm="http://www.w3.org/TR/2001/REC-xml-c14n-20010315"/></Transforms><DigestMethod Algorithm="http://www.w3.org/2000/09/xmldsig#sha1"/><DigestValue>V/6LWPpR7TYtbwmv5bLj98EbVfs=</DigestValue></Reference></SignedInfo><SignatureValue>gI+34EpWgNvWdDy9sJRgddmEfRLzL4d+pE7LHJnV9m8N3UepW3PypDH1+WdJbATorwfzerMTy4R6I5nfIaCbZlWj6ImAymRkoFmctNcVqn+TwB9n51Rb+GS3TrTe+mpeg2fdk/JixD+N3+tIropJLJM2zxXBpGh1RV81zpor8V3FAhyyGvrKgV3d1ZUj7OzWeBB97hYXZ0z5apoQECUQJ9uwouJFrkXwcFo9NA9AdfaXhTv0YHYh0I8RJY1yQLlc0p019MaSdpBdxF9avJ5uAdtUbOtKYf9WR5AHd+FltkwU8alqjz7ooViM09xi+2oPX8V2j0fO6N1g6IPvfQ7NyA==</SignatureValue><KeyInfo><X509Data><X509Certificate>MIIHcjCCBVqgAwIBAgIEAM1EWzANBgkqhkiG9w0BAQsFADCBiTELMAkGA1UEBhMCQlIxEzARBgNVBAoTCklDUC1CcmFzaWwxNjA0BgNVBAsTLVNlY3JldGFyaWEgZGEgUmVjZWl0YSBGZWRlcmFsIGRvIEJyYXNpbCAtIFJGQjEtMCsGA1UEAxMkQXV0b3JpZGFkZSBDZXJ0aWZpY2Fkb3JhIFNFUlBST1JGQnY0MB4XDTE2MDExMjEwNDgwNFoXDTE3MDExMTEwNDgwNFowgdUxCzAJBgNVBAYTAkJSMQswCQYDVQQIEwJTQzEPMA0GA1UEBxMGSVRBSkFJMRMwEQYDVQQKEwpJQ1AtQnJhc2lsMTYwNAYDVQQLEy1TZWNyZXRhcmlhIGRhIFJlY2VpdGEgRmVkZXJhbCBkbyBCcmFzaWwgLSBSRkIxFDASBgNVBAsTC0FSSU5GT0NPTUVYMRYwFAYDVQQLEw1SRkIgZS1DTlBKIEExMS0wKwYDVQQDEyRSRVBSRVRFQyBUUkFESU5HIExUREE6MDI1OTU4OTQwMDAxMzUwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQCy6fZMQo0xocytYViR6WgN/KVm49xiCmdeHQDQ7aAcuQbEQysnrDc/JwQ1aevxaT6VDXhbHRz9n7W/nLJUCRMi5o2g9ikMD5J1Rt0g0+ZCeS1rlD0Dpe/H8VZCshYYIb8qwRmV9xuwqIhVO//75navbiSy9KyPSeRWyb40dNiRugkSeXKEcLDKn3k/wBGASzz1+hn9OCzvZQOH3rp1+hTqVW6x9Z/jHlvtZ7z9GerOxoyLyAL9dPJnO7l4KNXVvgNazfE+xA6qorsBVYSLSljUerrnuJDPc/ARzQ9F4bPS1/42lOVapotEV7MUbq7eR5o4brkTI/Rr6HPyB9rGh2yrAgMBAAGjggKSMIICjjAfBgNVHSMEGDAWgBQwCiwMuDcr4PbaAv6AgmeWmFQZOzBbBgNVHSAEVDBSMFAGBmBMAQIBCjBGMEQGCCsGAQUFBwIBFjhodHRwOi8vcmVwb3NpdG9yaW8uc2VycHJvLmdvdi5ici9kb2NzL2RwY2Fjc2VycHJvcmZiLnBkZjCB0QYDVR0fBIHJMIHGMDygOqA4hjZodHRwOi8vcmVwb3NpdG9yaW8uc2VycHJvLmdvdi5ici9sY3IvYWNzZXJwcm9yZmJ2NC5jcmwwPqA8oDqGOGh0dHA6Ly9jZXJ0aWZpY2Fkb3MyLnNlcnByby5nb3YuYnIvbGNyL2Fjc2VycHJvcmZidjQuY3JsMEagRKBChkBodHRwOi8vcmVwb3NpdG9yaW8uaWNwYnJhc2lsLmdvdi5ici9sY3Ivc2VycHJvL2Fjc2VycHJvcmZidjQuY3JsMFYGCCsGAQUFBwEBBEowSDBGBggrBgEFBQcwAoY6aHR0cDovL3JlcG9zaXRvcmlvLnNlcnByby5nb3YuYnIvY2FkZWlhcy9hY3NlcnByb3JmYnY0LnA3YjCBsgYDVR0RBIGqMIGnoD0GBWBMAQMEoDQEMjIxMDYxOTc1MDE1NTg5MDU5MDEwMDAwMDAwMDAwMDAwMDAwMDAwMTk5MjU3N1NTUFNDoBoGBWBMAQMCoBEED0FVR1VTVE8gU0NISUVXRaAZBgVgTAEDA6AQBA4wMjU5NTg5NDAwMDEzNaAXBgVgTAEDB6AOBAwwMDAwMDAwMDAwMDCBFnJlbmF0YUByZXByZXRlYy5jb20uYnIwDgYDVR0PAQH/BAQDAgXgMB0GA1UdJQQWMBQGCCsGAQUFBwMEBggrBgEFBQcDAjANBgkqhkiG9w0BAQsFAAOCAgEAnIEJyfS02XEVWKFk5+Parl5WhJqxaVL7+QpI+RMTFAV/a8pOSVcCU4SotRAouxgULrwe9VfxjydCCnjZpfpUlToe1hYVzv1svxSZtthLnD+OYKVcQ0DLrwq8UQMRpnTbyFOLoJDCO938SKdaga+37k0P2tlHaig/M5QOBuwf975oeMuux75MmwLRWviac8GNcJ56+IBmO0bab8dBCBXF/jQEniSsJpejlL1ioG1I4VyjNxEHgAp+mkWfsafw364tJA85hj/1/vIzq1/jKW+ahvuz0dhnb1VZIi5GcktVDcxIDIS5uLZ5Ix1PmJpz3w9ONvE0jiacUhy2cmYLX+uLPTWxOgbExzl1luWmr341qXUyPEUrcwIRY7sZwqIWBzUzKKae71uU5lPTdC633CD1OZv2M/k09I6E4kztqlOnIGm7l/NzAwdDJIBlHal9Kqedbb15Azfkgy0FslB4VIylbxvoafQAdrpFCmpwpGX3kkUqNrbk7oNK9Xp63Xpc/gANVkdJ0WEeEv4vdeCYkOu3iwIAn4qPx9ycfmC9Svfbvw55rqXloFdbS6liyCbCtkZDi7CV+ea7BdHUhFL9AUEgrPpQyjQhHixf+kJBRoNLJ5Qu8p0am1iLr1KnNiOR2wI8E7K+FTmne3J6Pe/Wal8ZqO8lwHZlkjvVUTs/5X5e9Y8=</X509Certificate></X509Data></KeyInfo></Signature></NFe>

Este é o XML que estou enviando, a nota assinada

**Comment by tryvin** [comment]
Então, ajuda se enviar como upload de arquivo, usando o link abaixo "Attach files by drag and drop"

**Comment by celomamp** [comment]
<?xml version="1.0" encoding="utf-8"?>
<NFe xmlns="http://www.portalfiscal.inf.br/nfe"><infNFe versao="3.10" Id="NFe42160102595894000135550020000161411000000017"><ide><cUF>42</cUF><cNF>00000001</cNF><natOp>VENDA DE MERCADORIA ADQUIRIDA OU RECEBIDA DE TERCEIROS</natOp><indPag>0</indPag><mod>55</mod><serie>2</serie><nNF>16141</nNF><dhEmi>2016-01-19T13:48:20-02:00</dhEmi><dhSaiEnt>2016-01-19T13:48:20-02:00</dhSaiEnt><tpNF>1</tpNF><idDest>1</idDest><cMunFG>4208203</cMunFG><tpImp>1</tpImp><tpEmis>1</tpEmis><cDV>7</cDV><tpAmb>1</tpAmb><finNFe>1</finNFe><indFinal>0</indFinal><indPres>0</indPres><procEmi>0</procEmi><verProc>3.10</verProc></ide><emit><CNPJ>02595894000135</CNPJ><xNome>REPRETEC TRADING LTDA</xNome><xFant>REPRETEC TRADING LTDA</xFant><enderEmit><xLgr>RUA JOINVILLE</xLgr><nro>304</nro><xCpl>EDIFICIO ATHON</xCpl><xBairro>CENTRO</xBairro><cMun>4208203</cMun><xMun>ITAJAI</xMun><UF>SC</UF><CEP>88301410</CEP><fone>4733492261</fone></enderEmit><IE>254492061</IE><CRT>3</CRT></emit><dest><CNPJ>08807524000109</CNPJ><xNome>NF-E EMITIDA EM AMBIENTE DE HOMOLOGACAO - SEM VALOR FISCAL</xNome><enderDest><xLgr>RUA: URUGUAI</xLgr><nro>435</nro><xBairro>CENTRO</xBairro><cMun>4208203</cMun><xMun>ITAJAI</xMun><UF>SC</UF><CEP>88302201</CEP><fone>4733498599</fone></enderDest><indIEDest>9</indIEDest><email>alexandrerepretec@hotmail.com; GILBERTO@REPRETEC.COM.BR</email></dest><det nItem="1"><prod><cProd>25</cProd><cEAN/><xProd>ARAME RECOZIDO PRETO SIMPLES BWG12</xProd><NCM>72171090</NCM><CFOP>5102</CFOP><uCom>KG</uCom><qCom>1000.0000</qCom><vUnCom>3.2381</vUnCom><vProd>3238.10</vProd><cEANTrib/><uTrib>KG</uTrib><qTrib>1000.0000</qTrib><vUnTrib>3.2381</vUnTrib><indTot>1</indTot></prod><imposto><ICMS><ICMS00><orig>0</orig><CST>00</CST><modBC>3</modBC><vBC>3400.01</vBC><pICMS>17.00</pICMS><vICMS>578.00</vICMS></ICMS00></ICMS><IPI><clEnq>999</clEnq><cEnq>999</cEnq><IPITrib><CST>50</CST><vBC>3238.10</vBC><pIPI>5.0000</pIPI><vIPI>161.91</vIPI></IPITrib></IPI><PIS><PISAliq><CST>01</CST><vBC>3238.10</vBC><pPIS>1.6500</pPIS><vPIS>53.43</vPIS></PISAliq></PIS><COFINS><COFINSAliq><CST>01</CST><vBC>3238.10</vBC><pCOFINS>7.6000</pCOFINS><vCOFINS>246.10</vCOFINS></COFINSAliq></COFINS></imposto></det><total><ICMSTot><vBC>3400.01</vBC><vICMS>578.00</vICMS><vICMSDeson>0.00</vICMSDeson><vBCST>0.00</vBCST><vST>0.00</vST><vProd>3238.10</vProd><vFrete>0.00</vFrete><vSeg>0.00</vSeg><vDesc>0.00</vDesc><vII>0.00</vII><vIPI>161.91</vIPI><vPIS>53.43</vPIS><vCOFINS>246.10</vCOFINS><vOutro>0.00</vOutro><vNF>3400.01</vNF></ICMSTot></total><transp><modFrete>0</modFrete><vol><qVol>1</qVol><esp>1</esp><marca>1</marca><nVol>1</nVol><pesoL>1000.000</pesoL><pesoB>1000.000</pesoB></vol></transp><cobr><dup><nDup>16141/1</nDup><dVenc>2016-02-16</dVenc><vDup>3400.01</vDup></dup></cobr><infAdic><infAdFisco>INFORMACOES INTERESSE FISCO</infAdFisco></infAdic></infNFe><Signature xmlns="http://www.w3.org/2000/09/xmldsig#"><SignedInfo><CanonicalizationMethod Algorithm="http://www.w3.org/TR/2001/REC-xml-c14n-20010315"/><SignatureMethod Algorithm="http://www.w3.org/2000/09/xmldsig#rsa-sha1"/><Reference URI="#NFe42160102595894000135550020000161411000000017"><Transforms><Transform Algorithm="http://www.w3.org/2000/09/xmldsig#enveloped-signature"/><Transform Algorithm="http://www.w3.org/TR/2001/REC-xml-c14n-20010315"/></Transforms><DigestMethod Algorithm="http://www.w3.org/2000/09/xmldsig#sha1"/><DigestValue>V/6LWPpR7TYtbwmv5bLj98EbVfs=</DigestValue></Reference></SignedInfo><SignatureValue>gI+34EpWgNvWdDy9sJRgddmEfRLzL4d+pE7LHJnV9m8N3UepW3PypDH1+WdJbATorwfzerMTy4R6I5nfIaCbZlWj6ImAymRkoFmctNcVqn+TwB9n51Rb+GS3TrTe+mpeg2fdk/JixD+N3+tIropJLJM2zxXBpGh1RV81zpor8V3FAhyyGvrKgV3d1ZUj7OzWeBB97hYXZ0z5apoQECUQJ9uwouJFrkXwcFo9NA9AdfaXhTv0YHYh0I8RJY1yQLlc0p019MaSdpBdxF9avJ5uAdtUbOtKYf9WR5AHd+FltkwU8alqjz7ooViM09xi+2oPX8V2j0fO6N1g6IPvfQ7NyA==</SignatureValue><KeyInfo><X509Data><X509Certificate>MIIHcjCCBVqgAwIBAgIEAM1EWzANBgkqhkiG9w0BAQsFADCBiTELMAkGA1UEBhMCQlIxEzARBgNVBAoTCklDUC1CcmFzaWwxNjA0BgNVBAsTLVNlY3JldGFyaWEgZGEgUmVjZWl0YSBGZWRlcmFsIGRvIEJyYXNpbCAtIFJGQjEtMCsGA1UEAxMkQXV0b3JpZGFkZSBDZXJ0aWZpY2Fkb3JhIFNFUlBST1JGQnY0MB4XDTE2MDExMjEwNDgwNFoXDTE3MDExMTEwNDgwNFowgdUxCzAJBgNVBAYTAkJSMQswCQYDVQQIEwJTQzEPMA0GA1UEBxMGSVRBSkFJMRMwEQYDVQQKEwpJQ1AtQnJhc2lsMTYwNAYDVQQLEy1TZWNyZXRhcmlhIGRhIFJlY2VpdGEgRmVkZXJhbCBkbyBCcmFzaWwgLSBSRkIxFDASBgNVBAsTC0FSSU5GT0NPTUVYMRYwFAYDVQQLEw1SRkIgZS1DTlBKIEExMS0wKwYDVQQDEyRSRVBSRVRFQyBUUkFESU5HIExUREE6MDI1OTU4OTQwMDAxMzUwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQCy6fZMQo0xocytYViR6WgN/KVm49xiCmdeHQDQ7aAcuQbEQysnrDc/JwQ1aevxaT6VDXhbHRz9n7W/nLJUCRMi5o2g9ikMD5J1Rt0g0+ZCeS1rlD0Dpe/H8VZCshYYIb8qwRmV9xuwqIhVO//75navbiSy9KyPSeRWyb40dNiRugkSeXKEcLDKn3k/wBGASzz1+hn9OCzvZQOH3rp1+hTqVW6x9Z/jHlvtZ7z9GerOxoyLyAL9dPJnO7l4KNXVvgNazfE+xA6qorsBVYSLSljUerrnuJDPc/ARzQ9F4bPS1/42lOVapotEV7MUbq7eR5o4brkTI/Rr6HPyB9rGh2yrAgMBAAGjggKSMIICjjAfBgNVHSMEGDAWgBQwCiwMuDcr4PbaAv6AgmeWmFQZOzBbBgNVHSAEVDBSMFAGBmBMAQIBCjBGMEQGCCsGAQUFBwIBFjhodHRwOi8vcmVwb3NpdG9yaW8uc2VycHJvLmdvdi5ici9kb2NzL2RwY2Fjc2VycHJvcmZiLnBkZjCB0QYDVR0fBIHJMIHGMDygOqA4hjZodHRwOi8vcmVwb3NpdG9yaW8uc2VycHJvLmdvdi5ici9sY3IvYWNzZXJwcm9yZmJ2NC5jcmwwPqA8oDqGOGh0dHA6Ly9jZXJ0aWZpY2Fkb3MyLnNlcnByby5nb3YuYnIvbGNyL2Fjc2VycHJvcmZidjQuY3JsMEagRKBChkBodHRwOi8vcmVwb3NpdG9yaW8uaWNwYnJhc2lsLmdvdi5ici9sY3Ivc2VycHJvL2Fjc2VycHJvcmZidjQuY3JsMFYGCCsGAQUFBwEBBEowSDBGBggrBgEFBQcwAoY6aHR0cDovL3JlcG9zaXRvcmlvLnNlcnByby5nb3YuYnIvY2FkZWlhcy9hY3NlcnByb3JmYnY0LnA3YjCBsgYDVR0RBIGqMIGnoD0GBWBMAQMEoDQEMjIxMDYxOTc1MDE1NTg5MDU5MDEwMDAwMDAwMDAwMDAwMDAwMDAwMTk5MjU3N1NTUFNDoBoGBWBMAQMCoBEED0FVR1VTVE8gU0NISUVXRaAZBgVgTAEDA6AQBA4wMjU5NTg5NDAwMDEzNaAXBgVgTAEDB6AOBAwwMDAwMDAwMDAwMDCBFnJlbmF0YUByZXByZXRlYy5jb20uYnIwDgYDVR0PAQH/BAQDAgXgMB0GA1UdJQQWMBQGCCsGAQUFBwMEBggrBgEFBQcDAjANBgkqhkiG9w0BAQsFAAOCAgEAnIEJyfS02XEVWKFk5+Parl5WhJqxaVL7+QpI+RMTFAV/a8pOSVcCU4SotRAouxgULrwe9VfxjydCCnjZpfpUlToe1hYVzv1svxSZtthLnD+OYKVcQ0DLrwq8UQMRpnTbyFOLoJDCO938SKdaga+37k0P2tlHaig/M5QOBuwf975oeMuux75MmwLRWviac8GNcJ56+IBmO0bab8dBCBXF/jQEniSsJpejlL1ioG1I4VyjNxEHgAp+mkWfsafw364tJA85hj/1/vIzq1/jKW+ahvuz0dhnb1VZIi5GcktVDcxIDIS5uLZ5Ix1PmJpz3w9ONvE0jiacUhy2cmYLX+uLPTWxOgbExzl1luWmr341qXUyPEUrcwIRY7sZwqIWBzUzKKae71uU5lPTdC633CD1OZv2M/k09I6E4kztqlOnIGm7l/NzAwdDJIBlHal9Kqedbb15Azfkgy0FslB4VIylbxvoafQAdrpFCmpwpGX3kkUqNrbk7oNK9Xp63Xpc/gANVkdJ0WEeEv4vdeCYkOu3iwIAn4qPx9ycfmC9Svfbvw55rqXloFdbS6liyCbCtkZDi7CV+ea7BdHUhFL9AUEgrPpQyjQhHixf+kJBRoNLJ5Qu8p0am1iLr1KnNiOR2wI8E7K+FTmne3J6Pe/Wal8ZqO8lwHZlkjvVUTs/5X5e9Y8=</X509Certificate></X509Data></KeyInfo></Signature></NFe>

**Comment by celomamp** [comment]
Estava tentando enviar no texto haha

**Comment by celomamp** [comment]
O github não suporta xml, vou criar um link

**Comment by tryvin** [comment]
Continuou vindo como texto, mas enfim, deu pra ver que tá criando a nota como homologação. O NFePHP usa duas classes separadas, uma que faz o XML, e outra que envia, e assina. Ambas na instancia tem que configurar, você poderia postar o trecho de código que você tá usando para criar, e para mandar? das classes MakeNFe e ToolsNFe, só a parte que instancia mesmo, e seta as configurações

**Comment by celomamp** [comment]
https://drive.google.com/open?id=0BxG9JviJRLiGQnFpSk5pN1pnaUU se preferir olhar com mais detalhes

**Comment by celomamp** [comment]
$tpAmb = '2'; //tipo de ambiente (Homologação)
			$aResposta = array(); // Instancia um array de respostas			
			$aXml = file_get_contents($xml_file); //Pega o arquivo xml
			$idLote = '';
			$indSinc = '0';
			$flagZip = false;
			$retorno = $nfe->sefazEnviaLote($aXml, $tpAmb, $idLote, $aResposta, $indSinc, $flagZip); //Se comunica com a sefaz
			$numero_recibo = $aResposta['nRec'];

			//========================== CONSULTA RETORNO (RECIBO) ==============

			$tpAmb = '2'; //tipo de ambiente (Homologação)
			$aRespostaRecibo = array();
			$recibo = $numero_recibo;
			$retorno = $nfe->sefazConsultaRecibo($recibo, $tpAmb, $aRespostaRecibo);
			//echo '<br><br><PRE>';
			echo $nfe->soapDebug;
			//echo '</PRE><BR>';
			//print_r($aRespostaRecibo);
			//echo "<br>";


Eu já recebo a nota assinada do cliente, só faço a transmissão

**Comment by tryvin** [comment]
a TAG tpAmb do XML tá como 1 - Produção, deveria ser 2, homologação. O cliente então tá gerando o XML errado.

**Comment by tryvin** [comment]
Mas ele acertou pelo menos na parte do xNome, <xNome>NF-E EMITIDA EM AMBIENTE DE HOMOLOGACAO - SEM VALOR FISCAL</xNome>

**Comment by celomamp** [comment]
Tem Razão, tryvin. Obrigado pela ajuda!

**Comment by tryvin** [comment]
Disponha! Alguém marque como closed
