### ISSUE TITLE
NFePHP está preparado para a nova norma do ICMS?

### ISSUE THREAD

**Issue by alamops** [nfephp-org/nfephp#758]
O título já diz tudo.

Lembrando, a partir do dia 01/01/2016, entrou em vigor a nova norma de ICMS.
No qual se deve exercer o imposto tanto para o estado de origem quanto para o estado de destino.

Por exemplo, existe uma loja virtual de AM que vendeu para um consumidor de RJ.

Então, fica ai a minha dúvida, a NFePHP está pronta para emitir dentro desta nova regra?

**Comment by robmachado** [comment]
Sim

**Comment by alamops** [comment]
@robmachado ela faz o trabalho de emitir e gerar as guias para a loja virtual enviar junto com o produto?

**Comment by robmachado** [comment]
O NFePHP gera e envia a NFe (ou NFCe)

As guias para o pagamento é com outro pacote sped-gnre
<https://github.com/nfephp-org/sped-gnre>

Roberto

**Comment by alamops** [comment]
Ótimo...
Muito obrigado, @robmachado
