### ISSUE TITLE
Composer.json

### ISSUE THREAD

**Issue by jorgemarcondes** [nfephp-org/nfephp#764]
Vocês podem alterar o composer.json para versão 2.4.*@dev para ~2.5
Estou tendo muito mais trabalho para essa versão do zend-mail, devido as configurações do meu sistema.

**Comment by robmachado** [comment]
Vou verificar e corrijo sim

Roberto

**Comment by robmachado** [comment]
Ja corrigido para ^2.5

**Comment by jorgemarcondes** [comment]
Obrigado!
