### ISSUE TITLE
PHP 5.5 vs PHP 5.6

### ISSUE THREAD

**Issue by fmertins** [nfephp-org/nfephp#767]
Bom dia Roberto, uma dúvida/sugestão, se poderíamos ficar com a definição do composer.json do PHP 5.5 no mínimo, ao invés do 5.6? Ou se tem algum motivo que justifique o 5.6?

No Ubuntu (particularmente o meu caso), a última versão LTS ainda vem com o PHP 5.5, e olhando na Wikipedia esta versão será mantida até Julho deste ano, gostaria de sugerir mínimo 5.6 apenas a partir do encerramento do suporte da versão 5.5, obrigado.

Penso também para os demais usuários da API, quem não estiver no PHP 5.6 não vai conseguir utilizar?

**Comment by juniorb2ss** [comment]
Bom dia, Roberto. Tudo bom?

Eu dei uma pesquisa e falando a modo grosso não existiria motivos reais para se manter a requisição do PHP >= 5.6.*

Porém se analisarmos bem, acredito que há.

Versão LTS do 5.5 esta preste acabar, este seria primeiro motivo.
Segundo motivo trata-se a necessidade de refactor desta biblioteca, urgentemente a meu ver. Com novas tecnologias que são abordadas na versão 5.6.

Então, acredito eu que tendo em mente sobre a necessidade do refactor, já devemos manter a exigência de uma versão do PHP mais atual.

Quanto a questão apenas da versão PHP 5.5 estar disponivel em seu OS recomendo atualizar os repositórios, afins de poder atualizar sua versão.

Também devemos ressaltar a questão que maioria dos servidores de produção já possuem a versão 5.6.

**Comment by tonicospinelli** [comment]
@fmertins você pode fazer o upgrade da sua versão do php no ubuntu, veja como neste [link](https://joshtronic.com/2014/08/31/upgrade-to-php-56-on-ubuntu-1404-lts/)

É bem isso que o @juniorb2ss comentou :smile:  

@juniorb2ss já foi iniciado o refactoring da biblioteca para utilizar melhor os recursos das versões mais recentes do PHP bem como do composer :wink:

**Comment by juniorb2ss** [comment]
@tonicospinelli sim, estou ciente. Implementações como PSR-4 necessitam de urgência.

Ajudarei com o possível ;)

**Comment by robmachado** [comment]
Isso é uma discussão longa meus amigos, mas é o seguinte :


   - *Posso até deixar o minimo com PHP 5.5 *porém todos os testes e
   verificações de funcionalidade serão feitos com PHP >= 5.6 e PHP >= 7.0,
   então se houver alguma incompatibilidade com o PHP 5.5 não vamos saber e
   nem corrigir.



   - *Não gostaria de fazer essa alteração porque a "Data de Fim de
   Manutenção" do PHP 5.5  é em 10 de JULHO de 2016 e já faz mais de 6 meses
   que essa versão só recebe BUG FIXES e não é mais mantida.*



   - A ideia é deixar o PHP minimo estabelecido no composer apenas para
   versões ativamente suportadas, quando deixam de ser ativamente suportadas
   ainda são mantidas por no máximo mais 6 meses e depois retiradas.


O trabalho que teria seria de atualizar seus servidores, como eu faço com
os meus, eu entendo que não é fácil algumas vezes.
Uma solução seria usar seu próprio "fork" com essas alterações por enquanto
(nesse período em que seu servidor ainda não está atualizado) .

Antes de fazer qualquer outra coisa gostaria de mais opiniões dos amigos

Abraço
Roberto

**Comment by gersonfs** [comment]
Olá amigos,

como ainda existe o suporte a versão 5.5 por parte da comunidade do PHP, acredito que podemos manter ela como versão mínima até que este seja encerrado.
Por questão de refatoração, não acho necessário ter como versão mínima a 5.6. Na versão 5.5 temos disponíveis todos os recursos para aplicar as melhores práticas de design patterns, PSR's, composer, etc.
Fazer upgrade da versão do PHP localmente é tranquilo, a questão é em servidores em produção, a tática de "não mexer em time que está ganhado" é muito usada. Eu, por exemplo, gerencio servidores compartilhados com mais de 500 domínios, e solicitar para toda essa galera manter seu código atualizado é complicado. Nem todos pensam como nós. Por isso postergo ao máximo sem comprometer a segurança.

Resumindo: Eu votaria pelo PHP 5.5 como versão mínima até terminar o suporte dela.

Abraços!

**Comment by robmachado** [comment]
PHP minimo do composer setado para 5.5 isso será mantido até julho então será passado para 5.6.
