### ISSUE TITLE
Estou tendo um problema ainda na instalação

### ISSUE THREAD

**Issue by maiconkamiya** [nfephp-org/nfephp#770]
Warning: include(C:\wamp\www\nfe/vendor/autoload.php): failed to open stream: No such file or directory in C:\wamp\www\nfe\bootstrap.php on line 3

Algume pode me ajudar

**Comment by robmachado** [comment]
Antes de qualquer outra coisa, tem que rodar o "composer" para instalar as dependências definidas no composer.json.

A API atende PSR-4 !!!

Se o seu sistema não usa PSR-4, nem o PSR-0 (ou seja não usa o "composer" e o autoload) você terá quer fazer muitas alterações para usar coisas antigas como o require_once() e por ai vai.

**Comment by robmachado** [comment]
Para obter ajuda ... entre no grupo do google https://groups.google.com/forum/#!forum/nfephp
Sempre tem aguem disposto a ajudar

**Comment by jderibamar** [comment]
Olá, eu baixei usando o **composer**, ele criou a pasta **vendor**, mas ele continuar dando o mesmo erro, Robmachado você falou para rodar o **composer** antes de qualquer coisa, por gentileza, como exatamente rodar o composer, é entrar na pasta **vendor** e digitar commposer e se sim o que mais deve ser digitado depois de composer?

Muito grato pela ajuda.

**Comment by robmachado** [comment]
O que é o seu bootstrap.php ??? espero que NÃO seja o do nfephp se for você ainda não entendeu como usar o autoload !!!

**Comment by fmertins** [comment]
@jderibamar Por favor postar estas dúvidas no grupo de discussão, aqui é mais relacionado ao desenvolvimento do API.

**Comment by jderibamar** [comment]
Já postei mas não teve respostas, sim, esse bootstrap é o da pasta, estou pesquisando as configurações do PHP.Ini para ver os Paths e se tem algo haver, ele dar os dois erros abaixo.

Warning: require_once(../bootstrap.php): failed to open stream: No such file or directory in C:\Users\NOTE\Dropbox\Programação\Projetos PHP\SiscoriWeb\vendor\nfephp-org\nfephp\install\index.php on line 42

Fatal error: require_once(): Failed opening required '../bootstrap.php' (include_path='.;C:\php\pear') in C:\Users\NOTE\Dropbox\Programação\Projetos PHP\SiscoriWeb\vendor\nfephp-org\nfephp\install\index.php on line 42
