### ISSUE TITLE
MDF-e

### ISSUE THREAD

**Issue by angraxs2** [nfephp-org/nfephp#773]
Boa Tarde,

Tenho muito interesse no módulo de MDF-e e gostaria de saber qual o seu atual status (desatualizado, não funcional, etc) com mais detalhes para contribuir com o projeto.

Obrigado

**Comment by robmachado** [comment]
Em principio  a versão que está na tag 3.10-obsoleta deveria estar funcional mas como não temos um mantenedor dessas classes elas não foram ainda refatoradas para um padrão melhor. Como é o caso da NFe. 
Inclusive não sei se houveram alterações das regras da SEFAZ para essa parte do SPED e se foram inclusas até a ultima correção.
Essas classes deveriam ser refatoradas para os padrões das classes da NFe e colocadas no diretorio correto do pacote.

**Comment by robmachado** [comment]
Posso ajudar e orientar essa tarefa de refatoração, se você estiver interessado em participar, estamos procurando alguém que use o MDFe e assim possa realizar testes diretos, acompanhar as alterações junto a SEFAZ e manter esse pacote atualizado e funcional.
