### ISSUE TITLE
Usando class da NFE

### ISSUE THREAD

**Issue by cacio** [nfephp-org/nfephp#777]
Ola, estou com uma dificuldade em usar as class de dentro das libs todas as classes que tento estanciar da erro 
Fatal error: Class 'ConvertNFe' not found in
<?php
include_once '../nfe/bootstrap.php';
												
include ("../nfe/libs/NFe/ConvertNFe.php");
				 
$convert = new ConvertNFe();
$txtfile = '../nfe/NOTAFISCAL_232216.txt';

$aNFe = $convert->txt2xml($txtfile);

?>

Não sei oque pode ser, se alguém puder me ajudar .

**Comment by robmachado** [comment]
Use o PSR-4 para estabelecer as classes

Roberto

**Comment by cacio** [comment]
Aham, tipo se eu uso dessa maneira abaixo

<?php
error_reporting(E_ALL);
ini_set('display_errors', 'On');
include_once '../bootstrap.php';

use NFePHP\NFe\ConvertNFe;

$convert = new ConvertNFe();

$txtfile = '../homologacao/entradas/NOTAFISCAL_232216.txt';

$aNFe = $convert->txt2xml($txtfile);

header("Content-Type:text/xml");
echo $aNFe[0];

no meu arquivo que eu defini dentro de uma pasta php ele não da erro ,
mas se eu ussar o metodo que eu quero chamar ele tipo exemplo abaixo

<?php
	
	require_once('../inc/inc.autoload.php');
	session_start();
	if(isset($_REQUEST['act']) and !empty($_REQUEST['act'])){
		
		header('Access-Control-Allow-Origin: *');
		$act = $_REQUEST['act'];	
		
		switch($act){			
			case 'gerar':
				
				error_reporting(E_ALL);
				ini_set('display_errors', 'On');
				include_once '../bootstrap.php';
				
				use NFePHP\NFe\ConvertNFe;
				
				$convert = new ConvertNFe();
				
				$txtfile = '../xml/NOTAFISCAL310.txt';
				
				$aNFe = $convert->txt2xml($txtfile);
				
				header("Content-Type:text/xml");
				echo $aNFe[0];
				 
			
				
			break;
	
		}
	
	
	}
?>

ai da o erro, qual a diferença ;

**Comment by robmachado** [comment]
Menino;

*Ponto numero um ... *
Porque está usando dois arquivos autoload ??? o seu o da API !!!! o arquivo
bootstrap.php da api apenas aponta para o autoload

*Ponto numero dois ...*
Você sabe o que é composer ??? você entende o PSR-4 ??? você usou o SEU
composer jason para carregar a API ???

Roberto

**Comment by tonicospinelli** [comment]
baixou Linus Torvalds no @robmachado :smiley: 

@cacio você precisa do composer (gerenciador de dependências) para conseguir fazer o autoload das classes [https://getcomposer.org/](https://getcomposer.org/)

**Comment by cacio** [comment]
Desculpe só estava colocando um posição de como uma maneira funciona e outro não, e estou usando o composer só descobri que tenho que usar no começo do arquivo, e o autoload que eu tenho é da minha aplicação que eu chamo as minhas classes, antes não utilizava o composer por não saber usar como tive que me adaptar com uma nova chamada estava pedindo uma ajuda mas agora ja consegui carregar as classes e esta funcionando , desculpa por ser um pouco leigo só estou me atualizando, mas agradeço pelo ajuda , Obrigado.

**Comment by robmachado** [comment]
Cacio;

Isso não é uma critica, mas todo o programador tem por obrigação entender
as coisas antes de usar.
Eu mesmo fico as vezes horas em cima de um problema que até já resolvi mas
fico analisando para entender o PorQue ?? assim uma vez que a gente entende
como as coisas funcionam fica muito mais fácil usa-las de forma correta.

Mesmo com o composer e com o autoload isso também é numa "novidade" para
mim e eu demorei semanas para entender como funcionava, pesquisei bastante,
assisti a video aulas, comparei projetos no GitHub achei muita coisa boa
como isso http://composer.json.jolicode.com/ .

Não é nenhum problema não saber, mas é um problema não buscar entender
primeiro

Bons estudos
Roberto

**Comment by angraxs2** [comment]
O problema é quando você parte do pre-suposto que a outra pessoa não faz
isso (ou não fez o suficiente), como foi o meu caso. Uma simples pergunta
foi motivo pra uma resposta desnecessariamente rude.

Sabemos que o projeto é de sua autoria e que grande parte da contribuição
foi sua, e, como já disse, toda a comunidade é bastante grata (sim, eu li
praticamente todos os tópicos e e-mails dos últimos 2 anos do projeto).

Em 1 de março de 2016 10:27, Roberto L. Machado <notifications@github.com>
escreveu:

**Comment by cacio** [comment]
Roberto;
Entendo, como eu sempre digo sou um mero aprendiz mesmo sabendo um pouco de alguma coisa ou de outra estou sempre aqui para aprender e melhorar e estou buscando essas novidades só peso um pouco de compreensão da parte por tu saber mais dessa parte e ser o mentor de tudo isso. e como o colega disse ali "toda a comunidade é bastante grata" e ainda mais pelo um belo trabalho em fazer isso , 

Obrigado.

**Comment by robmachado** [comment]
Não quero estender essa conversa mas eu não acho que fui RUDE apenas firme,
não vejo solução em apenas corrigir os erros, mas sim fazer com que o
programador repense o que está fazendo.

Se você apenas corrige, o colega não vai aprender o porque esse erro
ocorre! e vai continuar cometendo os mesmos erros.
Por exemplo, toda essa conversa está dentro de uma ISSUE que na verdade nem
deveria existir. Ela só existe devido ao fato que há pouco conhecimento
sobre um determinado assunto. E esse assunto (composer) tem inúmeros
tutoriais na internet. Uma vasta documentação e esse tipo de ocorrência
deveria ser tratada no forum e não aqui.

Muitas vezes as perguntas (não a do Cacio) são devido a falta de
conhecimento de ingles, pois a resposta já foi dada pelo próprio PHP.

**Comment by DavidsonPimenta** [comment]
Provavelmente é erro ao apontar onde está o bootstrap ou autloader...  verifica ae
