### ISSUE TITLE
Novo formato de nfe

### ISSUE THREAD

**Issue by gustavolira** [nfephp-org/nfephp#780]
Bom dia,

Existe alguma previsão para integração com o novo formato da nfe que entrará em vigor em abril?

**Comment by robmachado** [comment]
A o que você está se referindo ??

**Comment by robmachado** [comment]
Se você está se referindo a tag "CEST" isso já foi incluso na classe MakeNFe a bastante tempo. Está disponível no método tagCEST()

**Comment by gustavolira** [comment]
era exatamente isso, desculpe a minha ignorância, estou começando a implementar nfe agora.
Obrigado

**Comment by fmertins** [comment]
Pegue um café, acomode-se e boa leitura... :-) Qualquer coisa prende o grito.
