### ISSUE TITLE
DateTime

### ISSUE THREAD

**Issue by robmachado** [nfephp-org/nfephp#782]
Refatorar as classes MailNFe, DateTime e outras para usar a classe DateTime do PHP

**Comment by rafael-renan-pacheco** [comment]
Caso seja interessante, verifique a possibilidade de utilizar Carbon:

http://carbon.nesbot.com/

É uma api que utiliza o DateTime do PHP, e facilita bastante o uso de datas e horários.

Também é a biblioteca padrão de data/hora do framework Laravel.

**Comment by robmachado** [comment]
Sim ... não fiz ainda porque comecei a estudar o Laravel e vi o Carbon, mas sua lembrança é  muito bem vinda.

**Comment by tonicospinelli** [comment]
não sou a favor de usar muitas bibliotecas externas (somente se tiver features realmente relevantes).
Acredito que o próprio `DateTime` do PHP seja suficiente para atender as demandas deste projeto

**Comment by rafael-renan-pacheco** [comment]
@tonicospinelli com certeza, por isso comentei o "Caso seja interessante" rs

Carbon poderia entrar em ação apenas se o uso do DateTime nativo do php ficar muito confuso ou complexo. Afinal, ele existe por causa disso.

:+1:

**Comment by robmachado** [comment]
Concordo, com o @tonicospinelli , quanto menos a API depender de outros pacotes melhor e o que puder ser feito apenas com o PHP garante mais estabilidade. Nesse caso em particular como é uma coisa muito simples a tendencia é usar apenas os recursos do PHP.

**Comment by tonicospinelli** [comment]
@rafael-renan-pacheco estamos alinhados 😉  (tendo em vista o que existe implementado do DateTime do projeto, hoje não faz sentido o Carbon)
