### ISSUE TITLE
Geração do pdf em outra pasta

### ISSUE THREAD

**Issue by msouzarunner** [nfephp-org/nfephp#783]
Olá, Pessoal.

    Estou iniciando a utilização da NFEPHP e ao fazer o teste como o arquivo 4.00testaDanfe.php, fiz a mudança de parâmetro nas funções Danfe() e $danfe->printDANFE() , indicando a pasta no servidor para gravação do pdf. Apesar disso o arquivo e gravado na pasta nfephp\libs\Extras.

   Eu alterei a função PRINTDANFE() incluindo o path de gravação juntamente com o nome do arquivo e funcionou. Se houver alguma outra forma de fazer isso favor me indicar ou alterar a função PRINTDANFE().

 Marcio Souza

**Comment by guicalabria** [comment]
Bom dia.
 Eu faço assim:
$danfe = $danfe = new NFePHP\Extras\Danfe($docxml, 'L',
'A4',$logo,'F',DIRETORIO_ONDE_QUERO_QUE_SALVE');
$id = $danfe->montaDANFE();
$teste =
$danfe->printDANFE(DIRETORIO_ONDE_QUERO_QUE_SALVE.'/'.$id.'.pdf','F');

Em 6 de março de 2016 09:30, msouzarunner <notifications@github.com>
escreveu:

**Comment by robmachado** [comment]
Fiz os testes aqui e não encontrei nenhum problema para salvar o PDF em qualquer diretório. Apenas tive o cuidado de dar as devidas permissões de escrita para o usuário do apache no diretório destino, e passei o path REAL para a escrita do PDF. 
Estou fechando esse issue.
