### ISSUE TITLE
Impressão de DANFE Simplificado

### ISSUE THREAD

**Issue by jorge600** [nfephp-org/nfephp#787]
Olá pessoal!
Gostaria de saber se alguém pode me ajudar na questão de impressão de DANFE Simplificado. Alguém já fez a implementação deste tipo de impressão ($tpImp='3'), ou sabe de algum post sobre este assunto, e que possa me ajudar? O objetivo é imprimir o DANFE em uma impressora térmica, em uma bobina de 80mm (igual a usada para impressão da NFC-e). Desde já agradeço atenção de vcs!

**Comment by robmachado** [comment]
Jorge;
Essa sua duvida, não é uma ISSUE e portanto deve levar sua duvida para o Grupo (forum) e não aqui no repositório. Cadastre-se no forum e faça suas perguntas lá por favor. https://groups.google.com/forum/#!forum/nfephp

**Comment by jorge600** [comment]
Ok! Muito obrigado Roberto!
