### ISSUE TITLE
CEST

### ISSUE THREAD

**Issue by cacio** [nfephp-org/nfephp#789]
Estou passando este elemento, mas ele me fala que não é esperado e esse elemento só esta passando dois parâmetros que é o item eo xcest, como posso fazer para isolar essa mensagem porque mesmo dando essa mensagem a sefaz me autoriza a nota.
Elemento 'CEST': Este elemento não é esperado. Esperado é um de ( NVE, EXTIPI, CFOP ).

**Comment by robmachado** [comment]
Primeiro necessito entender do que você está falando ?!?!
Essa mensagem está ocorrendo na validação interna do seu XML ??
Se for o caso qual versão do xsd está usando ?? Qual é o PL_??? ? 
Esse elemento não é requerido até dia 01/04/2016, mas a partir de 01/04/2016 será exigido pela SEFAZ.
Essa mensagem é decorrente do xsd sendo usado ... se usar o xsd correto a mensagem deixa de existir.

**Comment by cacio** [comment]
1 = Estou falando do cest como esta na mensagem,
2 =  Esta mensagem esta dando quando estou validando para depois transmitir.
3 = a versão que estou usando do PL = PL_008f ;

**Comment by robmachado** [comment]
Cacio;
Primeiro você deve permanecer atento as sequentes versões dos XSD disponibilizados no portal da Receita. Nós estamos usando a versão PL_008h2 e versão PL_008f não deve mais ser usada. Infelizmente, uma das tarefas que você como desenvolvedor e usuário de NFe deve executar é acompanhar o portal no mínimo uma vez por semana, bem como acompanhar a nossa lista de discussões e o versionamento da NFePHP. Fique atento pois as mudanças são constantes.

**Comment by robmachado** [comment]
Mais alguma duvida ou posso fechar esse ISSUE ???

**Comment by cacio** [comment]
Ok, pois é como eu tenho uma demanda muito alta de trabalho aqui fico meio sem ter como olhar as atualizações feita por vocês e também se cada atualização que vocês fizessem tivesse um alerta para saber ai blz mas nem todo ser é vidente então conforme vai surgindo vou ter que fazer um chamado mas brigado desde ja agradeço pela ajuda e compreensão da parte.

**Comment by tryvin** [comment]
Só clicar em watch no github
Em 22/03/2016 10:43, "Cacio" <notifications@github.com> escreveu:

**Comment by cacio** [comment]
Boa obrigado @tryvin

**Comment by cacio** [comment]
mas por fim é isso obrigado a todos e um bom trabalho

**Comment by robmachado** [comment]
Como disse o @tryvin existem formas de acompanhar.
Mas lembre-se Cacio que a maioria das alterações não são "CRIADAS" por nós, a maior parte é "IMPOSTA" pela SEFAZ.
Um abraço e bom trabalho para você também, vamos ficar atentos por aqui caso hajam novas alterações nos requisitos da SEFAZ.
