### ISSUE TITLE
Certificado A1

### ISSUE THREAD

**Issue by ricardofrdrc** [nfephp-org/nfephp#790]
Boa noite,

O certificado A1 pode ser instalado em um servidor?

Temos uma loja virtual com um servidor linux ubuntu e vamos começar a emitir as notas de forma automática pela loja.

**Comment by fmertins** [comment]
Bom dia, sim, mas na prática não precisa "instalar" no sentido literal, pois o certificado A1 é apenas um arquivo comum em alguma pasta do filesystem e a API vai ler e extrair as informações deste arquivo, no caso para assinar o XML, etc. Resumindo: basta o arquivo estar acessível, não precisa instala-lo ;-)

**Comment by ricardofrdrc** [comment]
Olá @fmertins,

Obrigado pela resposta.

Uma outra dúvida... eu já tenho o certificado A3 com token(pen drive)... é possível extrair dele esse arquivo para ser utilizado?

**Comment by tryvin** [comment]
Infelizmente a resposta para essa pergunta 99% das vezes é não.
Em 24/03/2016 09:20, "Ricardo Frederico Souza da Silva" <
notifications@github.com> escreveu:

**Comment by robmachado** [comment]
Na verdade por enquanto a possibilidade de usar um certificado A3 com o PHP é ZERO !
Veja que a probabilidade disso ocorrer no futuro também é muito REMOTA, pois um A3 não é um dispositivo indicado para operar em um servidor que é onde o PHP roda.

**Comment by ricardofrdrc** [comment]
Obrigado pela respostas @tryvin e @robmachado!

Blz, vou solicitar para o meu cliente a compra do certificado NF-e A1.

Ou dado importante... as notas que vamos emitir são de serviço (NFS-e)... é este mesmo certificado, certo?

OBS:
Liguei para diversas empresas que vendem certificados, mas o suporte deles é tão ruim que o atendente não conseguia tirar metade das minha dúvidas.

**Comment by tryvin** [comment]
Eu já ouvi falar que algumas fabricantes de cartões a3, ou tem um erro, ou
permite mesmo, mas você consegue exportar a chave privada e pública.

Eu usei uma solução junto com c++, como o pos roda localmente, eu uso o
nfephp para criar o XML, se o certificado for a1 ele envia e assina no
servidor mesmo, senão, ele baixa o XML, e o uninfe assina e envia, e eu só
retorno pro servidor o XML assinado, o número do lote, e o protocolo de
autorização.
Em 24/03/2016 15:33, "Ricardo Frederico Souza da Silva" <
notifications@github.com> escreveu:

**Comment by robmachado** [comment]
sso não é PHP puro, você está usando o Delphi para assinar e enviar ...
É uma solução para poucos, esse "quebra galho" gerá mais um ponto de controle e mais um ponto de falha, além de custos e de trabalho na instalação.

Funciona, como funcionaria com Java e várias outras linguagens mas cria outros tipos de problema e de gestão.

Não existe NENHUM motivo real para usar o certificado A3 no lugar do A1, qualquer motivo alegado não passa de uma desculpa esfarrapada e cria mais problemas do que resolve.

**Comment by tryvin** [comment]
Sim Roberto, eu não gosto dessa solução não, me dá mais trabalho que tudo,
além de que esses certificados em si normalmente param de funcionar do
nada.

Mas o problema é que os contadores não são cientes disso, e já compram pro
cliente o a3, aí depois disso que o cliente vem procurar a empresa do
sistema, quando vemos, já estão com o a merda do certificado a3
Em 24/03/2016 15:44, "Roberto L. Machado" <notifications@github.com>
escreveu:

**Comment by robmachado** [comment]
Eu entendo, mas mesmo sistemas GRANDES como TOTVS e SAP/R3 usam apenas A1 
O A3 só dá para usar normalmente em aplicativos locais e que são normalmente de pequeno porte.
Meus clientes são industrias e tem o A3 (e-CNPJ) que usam nesses sistemas de contabilidade, RH e coisas do tipo mas o ERP usa o A1. Então elas tem os dois. E ninguém foi a falência por isso.

**Comment by tryvin** [comment]
Sim, claro, nosso foco é micro e pequenas empresas. A situação financeira é
diferente. Tentam economizar em todos os lados
Em 24/03/2016 15:58, "Roberto L. Machado" <notifications@github.com>
escreveu:

**Comment by robmachado** [comment]
Bacana ! Mais alguma duvida ou podemos fechar essa ISSUE, tendo em vista que não existe uma solução apenas alternativas que não envolvem o PHP.

**Comment by ricardofrdrc** [comment]
Blz... uma última dúvida... hehe

Aqui na https://serasa.certificadodigital.com.br/p/nf-e/ tem "**NF-e A1 Sem dispositivo**" e "**Servidor NF-e sem dispositivo**"... a diferença de preço entre eles é muito alta.

O que você utilizam nos servidores é este NF-e A1, certo? (não quero correr o risco do cliente comprar o certificado errado).

**Comment by tryvin** [comment]
Sim, nfe a1,  ou pj a1, mas o pj é uma procuração em branco em nome da
empresa.
Em 24/03/2016 17:36, "Ricardo Frederico Souza da Silva" <
notifications@github.com> escreveu:

**Comment by robmachado** [comment]
É recomendável que quando usar o A1 seja o destinado a NFe ou seja certificado com proposito único então se torna mais seguro.

**Comment by robmachado** [comment]
@ricardofrdrc  

Esse certificado "Servidor NFe" é novidade para mim, desconheço isso, o correto é o mais barato de R$ 319,00 (NFe A1 sem dispositivo)
 
Veja o certificado no CERTISIGN o sistema deles funciona, na minha opinião melhor que o do SERASA, mas tem vários outros fornecedores autorizados e mais baratos.

Roberto

**Comment by ricardofrdrc** [comment]
blz, obrigado pelas dicas!

**Comment by nailsonlinux** [comment]
Fiquei curioso pra saber o que é esse "Servidor NFe".

**Comment by ricardocaldeira** [comment]
Acessa esse site, tem algumas informações. http://www.lunacloud.com/
Em 25 de mar de 2016 4:43 AM, "Nailson Landim" <notifications@github.com>
escreveu:

**Comment by rvicentine82** [comment]
So uma duvida básica, nao achei exatamente nas faqs, o certificado a1 que recebrei da certign ou qualquer outra certificadora eu deixo ele no servidor dentro da pasta /cert correto??? apenas isso ou preciso instalar ele no apache etc?

**Comment by fmertins** [comment]
Correto. Não precisa instalar no Apache.
