### ISSUE TITLE
Instalação Windows Wamp 

### ISSUE THREAD

**Issue by camilohikage** [nfephp-org/nfephp#798]
Tem algum passo a passo para que eu possa seguir ?

Estou tentando instalar e estou com certa dificuldade.

Clonei o projeto em minha pasta - ok
Rodei o comando composer install - ok
Rodei o comando "./vendor/bin/phpunit" - erro - "c:\wamp\www\nfe>composer ./vendor/bin/phpunit
You are running composer with xdebug enabled. This
 performance. See https://getcomposer.org/xdebug

  [Symfony\Component\Console\Exception\CommandNotF
  Command "./vendor/bin/phpunit" is not defined."

Podem me ajudar ?

**Comment by robmachado** [comment]
http://tableless.com.br/composer-para-iniciantes/

2016-04-12 11:06 GMT-03:00 camilohikage <notifications@github.com>:

> Tem algum passo a passo para que eu possa seguir ?
>
> Estou tentando instalar e estou com certa dificuldade.
>
> Clonei o projeto em minha pasta - ok
> Rodei o comando composer install - ok
> Rodei o comando "./vendor/bin/phpunit" - erro - "c:\wamp\www\nfe>composer
> ./vendor/bin/phpunit
> You are running composer with xdebug enabled. This
> performance. See https://getcomposer.org/xdebug
>
> [Symfony\Component\Console\Exception\CommandNotF
> Command "./vendor/bin/phpunit" is not defined."
>
> Podem me ajudar ?
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/nfephp-org/nfephp/issues/798>
>



-- 
Roberto

*Nisi utile est quod facimus stulta est gloriae* (Julius Phaedous)

**Comment by robmachado** [comment]
https://packagist.org/packages/nfephp-org/nfephp

**Comment by robmachado** [comment]
O NFePHP é uma API, você somente deve clonar a API caso queira colaborar com o seu desenvolvimento.
Para APENAS usar a API, você necessita incluir o pacote nfephp-og/nfephp (do packagist) como uma de suas dependências no SEU arquivo composer.json (ou seja no composer.json da SUA aplicação) .
Quando executar o comando composer install a partir da RAIZ da SUA aplicação (onde está o SEU composer.json TODAS as dependências lá registradas serão instaladas na pasta vendor criada pelo composer.
