### ISSUE TITLE
Emissor nfephp

### ISSUE THREAD

**Issue by rspadim** [nfephp-org/nfephp#801]
Fala galera, com a nova noticia da SEFAZ-SP, agora o emissor gratuito será descontinuado em 1/1/2017, vamos voltar a desenvolver um emissor da NFEPHP? será necessário NFe/CTe/MDFe

**Comment by tryvin** [comment]
Acredito que ele tá  saindo de circulação justamente porque temos vários
serviços disponíveis nessa área com melhor integração com os sistemas já
usados, ele tava sendo mais usado por contadores mesmo
Em 19/04/2016 16:38, "rspadim" <notifications@github.com> escreveu:

**Comment by rspadim** [comment]
Microempresas e MEI agora estão descobertas de um software para gerar de forma gratuita com "apoio" do SEFAZ, contadores até utilizavam pois reflete os novos campos e schema mais rapido, vamos ver oque vão inventar daqui pra frente, mas a idéia não é questionar, a idéia é criar um emissor gratuito

**Comment by robmachado** [comment]
Pessoal mantenham essa discussão no forum, isso não é uma ISSUE da API pois a API não tem nem nunca terá uma interface (é apenas uma API).
Mas eu mesmo já postei meus comentários lá no grupo.

**Comment by tryvin** [comment]
Mei só precisa tirar nota na venda a empresas, e na maior parte do tempo,
tira na própria prefeitura, é tanto que é raro certificados digitais para
mei.

E micro empresas têm contadores, entendeu ai a coisa.?
Em 19/04/2016 16:43, "rspadim" <notifications@github.com> escreveu:
