### ISSUE TITLE
Extrair todos os dados de uma nota

### ISSUE THREAD

**Issue by kikolino** [nfephp-org/nfephp#802]
Consigo extrair todos os dados de uma nota já cadastrada?
Utilizei o arquivo de exemplo 4.00testaConsultaChave.php mas só vieram poucos dados.

    [bStat] => 1
    [versao] => 3.10
    [tpAmb] => 1
    [cStat] => 100
    [verAplic] => SP_NFE_PL_008h2
    [xMotivo] => Autorizado o uso da NF-e
    [dhRecbto] => 2016-04-22T18:52:53-03:00
    [cUF] => 35

    [aProt] => Array
        (
            [dhRecbto] => 2016-03-28T10:33:57-03:00
            [nProt] => 135160185509106
            [cStat] => 100
            [xMotivo] => Autorizado o uso da NF-e
        )

    [aCanc] => Array
        (
        )

    [aEvent] => Array
        (
        )

**Comment by robmachado** [comment]
## Recomendo que você use o Forum para esse tipo de duvida.

Primeiro, para usar a API você pelo menos deve ser o manual da SFEAZ para entender o funcionamento dos webservices.  Esse método consulta a SEFAZ para dizer se a Nota é verdadeira e está válida, **apenas isso** e também retorna os dados do protocolo de autorização, de cancelamento (se houver) e de qualquer evento a ela vinculado (se houver).

**Não existe na API nada que converta o xml em sei lá o que você queira.** Foi iniciado um projeto denominado [nfephp-serializer](https://github.com/jansenfelipe/nfephp-serialize) que talvez atenda a sua necessidade.

**Comment by kikolino** [comment]
Qual o endereço do forum?O que eu quero é, pelo numero da chave da nota conseguir trazer todos os dados da mesma.Vou utilizar em um outro sistema.


Date: Sat, 23 Apr 2016 06:19:44 -0700
