### ISSUE TITLE
Site offline nfephp.org

### ISSUE THREAD

**Issue by rubensfernandes** [nfephp-org/nfephp#806]
Database Error: Unable to connect to the Database: Could not connect to MySQL.
Warning: Cannot modify header information - headers already sent by (output started at /home/nfephp/nfephp.org/libraries/loader.php:149) in /home/nfephp/nfephp.org/libraries/joomla/factory.php on line 546
Database Error: Unable to connect to the Database: Could not connect to MySQL.

**Comment by mikaelhadler** [comment]
Você conferiu as connections string?

**Comment by rubensfernandes** [comment]
o site nfephp.org está off eu estou tentando acessar http://www.nfephp.org/

**Comment by mikaelhadler** [comment]
Opa! Não me atentei ao assunto, somente a descrição haha, de acordo com a lista de discussão, ainda não se sabe com quem está a hospedagem do site e por isso não foi continuado, agora não sei dizer se tocaram esta thread.

**Comment by robmachado** [comment]
Logo estará sendo movido para o "Read The Docs", o site atual está com erros devido a falta de manutenção. Quem criou não manteve !!!

**Comment by rubensfernandes** [comment]
Uma dúvida Machado, os exemplos estão atualizados? é a primeira vez que me deparo com o dev de notas e estou meio perdido.

**Comment by robmachado** [comment]
Primeiro isso não é o lugar para perguntar isso !! vá ao forum e questione lá. 
Mas adiantando:
Sim, pode haver algum exemplo que não foi atualizado !

**Comment by rubensfernandes** [comment]
ok, desculpa.
