### ISSUE TITLE
Página duplicada

### ISSUE THREAD

**Issue by neilvilela** [nfephp-org/nfephp#807]
Boa tarde!

Percebi um bug que, em algumas circunstâncias, todos os produtos da primeira página são duplicados numa segunda página.

Consegui resolver temporariamente (pra esse caso) alterando a margem inferior de 2 para 3. Não consegui identificar no código para enviar um pull request.

Seguem XML e PDF gerado.

[NFe33160513644704000149550010000081241007766060.xml.txt](https://github.com/nfephp-org/nfephp/files/258075/NFe33160513644704000149550010000081241007766060.xml.txt)
[NFe 8124 - NIKITA COMERCIO DE ACESSSORIOS AUTOMOTIVOS NITEROI LTDA (2).pdf](https://github.com/nfephp-org/nfephp/files/258076/NFe.8124.-.NIKITA.COMERCIO.DE.ACESSSORIOS.AUTOMOTIVOS.NITEROI.LTDA.2.pdf)

**Comment by robmachado** [comment]
Sim ... isso é um problema RECORRENTE pois existem muitas falhas na logica que faz a construção do PDF. 
Essa classe necessita ser completamente REFATORADA.

**Comment by lpj145** [comment]
Eu tava pensando na construção do pdf como algo mais sólido, o atual é muito instável e cheio de código delicado. kkkkk
Quando podemos começar a reconstruir?

**Comment by robmachado** [comment]
Agora !!! 
Veja que estou tentando segmentar a complexa estrutura do NFePHP em repositórios menores e mais dedicados. Por exemplo no caso das impressões, temos o **[sped-da](https://github.com/nfephp-org/sped-da)** que é justamente para os Documentos Auxiliares (todos eles) como a DANFE.
Porém temos alguns entraves, que necessitam ser resolvidos:
1 - FPDF, usar o FPDF como está é INACEITÀVEL, ele não atende minimamente os padrões PSR então  teria de ser refatorado para uso nessa estrutura, já incluindo as funções extras necessárias. E usando já internamente os códigos de barra fornecidos por outras fontes bem melhor estruturadas.
2 - Melhorar a forma de identificação dos XML, de forma que ao passar um xml para o construtor o mesmo já identifique de que se trata e possa assim montar o documento desejado (veja isso em [sped-common](https://github.com/nfephp-org/sped-common)).

**Comment by lpj145** [comment]
O que acha da adoção do ZendPDF?

**Comment by robmachado** [comment]
Foi DESCONTINUADO !!!

**Comment by lpj145** [comment]
hmm que pena. Eu trabalho com Front também, e estou pensando num método sólido onde possamos como no css definir tamanho e margens globais a ser respeitadas por cada campo.

**Comment by lpj145** [comment]
Transformar html em pdf?

**Comment by robmachado** [comment]
Pesado !!! Lento !!! possui mutas falhas ... não recomendável .

**Comment by lpj145** [comment]
teremos de escrever uma nova classe então?

**Comment by robmachado** [comment]
Eu gostaria que essa discussão fosse passada para outro repositório já o sped-da !!
