### ISSUE TITLE
Exemplos desatualizados

### ISSUE THREAD

**Issue by jeanCarloMachado** [nfephp-org/nfephp#811]
Encontrei alguns exemplos que não funcionam, sendo assim concluí que estão desatualizados:

**https://github.com/nfephp-org/nfephp/blob/master/exemplos/NFe/guiTesteValidarXML.php**
Neste arquivo é utilizada a classe: ```$nfe = new ToolsNFePHP```; que não existe no repositório, concluo que é a ToolsNFe, mas o método validXML não existe.

**https://github.com/nfephp-org/nfephp/blob/master/exemplos/NFe/guiTesteTransmitirXML.php**
O mesmo que foi dito acima também vale para este exemplo. A única diferença é que o método autoriza não existe mais.

Os exemplos também não levam em consideração que a classe ToolsNFE precisa de argumentos no construtor para ser inicializada.

**Comment by robmachado** [comment]
É isso ai Jean existem muitos exemplos e documentos no WIKI que estão desatualizados.
Proponho que quem achar algo desatualizado faça um "PULL RESQUEST" e corrija essas falhas, tendo em vista que esse é um projeto aberto. 
Agradeço qualquer colaboração.

**Comment by jeanCarloMachado** [comment]
Obrigado pelo feedback @robmachado, vou mandar prs de ajuste conforme vou utilizando a lib, esses dois itens que comentei mandarei em breve. Talvez seria interessante colocar testes funcionais ao invés de documentação pura, aí forçamos o ajuste quando algo mudar/quebrar.

**Comment by robmachado** [comment]
Jean aos poucos estou migrando esse pacote deste repositório para os sped-* para tornar menores e mais específicos cada bloco do projeto. Que está ficando muito grande e desarticulado, em função disso a introdução desses novos repositórios também implica em alguma refatoração e os testes unitários. A meta é elevar o nível de cobertura dos testes a pelo menos uns 70%.  
Minha maior dificuldade é a falta de tempo, consegui migrar o conteúdo da pasta common para o repositório sped-common, mas temos que mover aos poucos todas as partes para esses outros repositórios.
Além dos testes unitários devemos também melhorar a documentação usando o mkDocs e o Read The Docs, mas isso é melhor feito nessas estruturas separadas (NFe, CTe, MDFe, Da, Common, etc...) . 
Essa é a ideia ,,.  falta tempo e colaboração
