### ISSUE TITLE
QRcode

### ISSUE THREAD

**Issue by Tairone** [nfephp-org/nfephp#818]
Boa noite,
pessoal preciso de uma ajuda, pois faz 3 dias q estou tentando gerar um xml para NFCe com qrcode, mas não estou conseguindo. Só retorna erro 394 "Nota Fiscal sem a informacao de QR-Code".
Existe algum bug nesse processo?

**Comment by tryvin** [comment]
Amigo, contanto que esteja no modelo 65 e com as informações do csc, não
tem que dar esse erro.
Em 30/05/2016 7:35 PM, "Tairone" <notifications@github.com> escreveu:

**Comment by robmachado** [comment]
**Isso não é uma ISSUE** ... caso você não tenha estudado o código, por favor questione no nosso forum 
Apenas para complementar o qrcode é inserido no xml durante o processo de assinatura desde que existam os csc e o csc_id no config são chamados de "token" e exista uma URL referente ao QRCode na sua UF veja o arquivo nfe_ws3_mod65.xml
