### ISSUE TITLE
Erro 4.00testaMakeNFe.php

### ISSUE THREAD

**Issue by LeonardoBragaBrazil** [nfephp-org/nfephp#821]
Boa tarde,
Instalei a biblioteca conforme wiki, e após isso chamei via browser: http://localhost/nfephp/exemplos/NFe/4.00testaMakeNFe.php 
e aparece a seguinte mensagem de erro:
--------------------------------------
No Chrome:
--------------------------------------
This page contains the following errors:

error on line 2 at column 1: Extra content at the end of the document
Below is a rendering of the page up to the first error.
--------------------------------------
No firefox:
--------------------------------------
Erro no processamento de XML: caracteres sem utilidade após um elemento do documento
Posição: http://localhost/nfephp/exemplos/NFe/4.00testaMakeNFe.php
Número da linha 2, coluna 1:<font size='1'><table class='xdebug-error xe-warning' dir='ltr' border='1' cellspacing='0' cellpadding='1'>
^
--------------------------------------
Alguém tem ideia do que eu fiz de errado?

Att.,
Leonardo Braga de Oliveira

**Comment by robmachado** [comment]
Primeiro o GitHub não é lugar para perguntar isso .. use o forum https://groups.google.com/forum/#!forum/nfephp

**SIM, ocorreu algum erro, ou aviso no PHP antes de retornar o xml.**
para ver o que aconteceu comente essas linhas header('Content-type: text/xml; charset=UTF-8');
apenas um comentário para usar a API são requeridos conhecimentos em PHP e SOAP, XML, PKCS#12, composer, PSR4 entre outros.
