### ISSUE TITLE
Passando parâmetros como array.

### ISSUE THREAD

**Issue by lpj145** [nfephp-org/nfephp#829]
Pessoal, numa situação que passei aqui, senti a necessidade de passar para um component apenas os dados necessários para aquela tag, registrados no bd do usuário logado.
Então para não encher muito o componente de variáveis e visando a facilidade, fiz uso de:

$dadosUser = [
 00000,
"blasldlsa"
]

$nfe->tagemit( ...$dadosUser  ).

Agora será que a gente poderia fazer alterações para que, futuramente possamos fazer uso de array com índices? Sendo assim uma tag não necessária, não precisaríamos passar como null. Definiríamos um modelo de objeto para as tags. Isso facilitaria na documentação.  Implementação e começaríamos a montar uma lógica estruturada, o que facilita para os novos.

**Comment by rafael-renan-pacheco** [comment]
Com certeza, chamar uma função passando mais de 4-5 parâmetros já é algo que necessita de atenção e refatoração, além de dificultar bastante o uso dessas funções.

No meu sistema, já estou planejamento em criar uma classe para receber os parâmetros em forma de array ou classe e fazer as chamadas nfephp, evitando assim a chamada dessas functions gigantes no código principal da aplicação.

Assim cada tag pode inclusive ter tratamento garantido pela classe, como por exemplo, um valor numérico ter sempre 2 casas decimais para algumas tags (valor do frete por exemplo). Dessa forma o código principal da aplicação não precisa se preocupar em fazer um number_format só pra gerar a tag corretamente.

O ideal seria que isso fosse disponibilizado direto pelo nfephp :)

**Comment by tonicospinelli** [comment]
entendo seu ponto, também acho que poderia ser melhorado, mas array fica muito aberto e suscetível a falha.

O importante nesse caso é sempre pensar em Backward Compatibility (BC) e com essa alteração o usuário (dev) acaba perdendo a referência do que deve estar em cada lugar.

Minha sugestão a respeito:
* criar um novo método `$nfe->emitente(new Emitente())` que encapsule essa regra do `tagemit`;
* depreciar `tagemit` e fazer ele usar este novo método internamente

**Comment by tonicospinelli** [comment]
@rafael-renan-pacheco também concordo, estamos passando por um longo processo de refatoração e precisamos de ajuda mesmo que seja de idéias! 😉

**Comment by robmachado** [comment]
@rafael-renan-pacheco essa sua solução é com certeza a mais recomendada de todas !!!
É sempre mais "lógico" ter uma camada entre a API e sua aplicação, para ser ajustada e garantir o funcionamento.
Estamos analisando essa alteração com relação aos parâmetros com cuidado, porém isso somente poderá ser implementado na versão 4.1.x. E também é muito provável que na nova versão hajam outras alterações como a indicada pelo Tonico.

**Comment by robmachado** [comment]
Srs.

Isso já pode ser feito pelo próprio recurso do PHP sem que eu tenha que alterar uma unica linha de programa. Apenas usando o operador ... na chamada do método e passando um array com os dados necessários na ordem solicitada pelo método.

exemplo:
`$chave = $nfe->montaChave($cUF, $ano, $mes, $cnpj, $mod, $serie, $nNF, $tpEmis, $cNF);`

Pode ser chamado como
`$chave = $nfe->montaChave(... [$cUF, $ano, $mes, $cnpj, $mod, $serie, $nNF, $tpEmis, $cNF]);`

Simples assim
