### ISSUE TITLE
Cupom Fiscal Eletronico

### ISSUE THREAD

**Issue by icompsoftcleiton** [nfephp-org/nfephp#83]
ola, já tem alguma ideia de iniciar o projeto de CFe ?

**Comment by aloisogomes** [comment]
Acho q poderiamos ser mais sensíveis ao respoder uma duvida. A emissao de Cupom Fiscal eletronico deve ser feita atraves de um emissor homologado chamado SAT, esse documento precisa ser impresso por uma impressora termica de rolo continuo. 

Mas infelizmente nao é qualquer desenvolvedor que pode desenvolver um sistema como esse, é preciso estar credenciado como uma Software House junto a Sefaz. Nao é permitido se credenciar como Software houses, pessoas fisicas ou micro empresario individual, apenas empresas com (ME, Eireli, LTDA ou SA) com cnae 61. 

o valor da impressora e do sat estao em torno de 1400 reais juntos.

Basicamente o sistema funciona da seguinte forma: 

o sistema desenvolvido pela software house gera um xml de acordo com as especificacoes de um CF-e armazena e transmite no equipamento Sat esse se encarrega de enviar a Sefaz. Nesse momento o cupom deve ser impresso na impressora, um otimo exemplo disso é em um supermercado.

Espero ter esclarecido algumas duvidas ao menos dos colegas
