### ISSUE TITLE
Ajuda - Manifesto Destinatario

### ISSUE THREAD

**Issue by pixuim** [nfephp-org/nfephp#831]
Prezados, Bom dia!

Consegui instalar a aplicacao no NF-ePHP estou com duvidas em relacao ao servico 4.00testaDistDFe.php.  O servico esta funcionando perfeitamente. Acontece que o mesmo retorna a TAG DOCZIP. Queria pegar o retorno do servico 4.00testaDistDFe.php e fazer a ciencia da operacao. Ate aonde eu sei a chave de acesso esta na TAG DOCZIP do retorno do servico 4.00testaDistDFe.php. Como eu posso descriptografar essa TAG ? Alguem pode me ajudar?

**Comment by robmachado** [comment]
Colega, se necessita de ajuda use o FORUM !!
Isso não é uma ISSUE .... a falta de leitura do codigo, ou a falta de documentação não representam BUGS ou melhorias a serem feitas no codigo.
Se deseja ajuda básica, como esssa, questione no forum https://groups.google.com/forum/#!forum/nfephp, mas pesquise antes de perguntar. 

NOTA: a própria função já descomprime e retorna esses dados em um array passado como parâmetro para a função.
