### ISSUE TITLE
Incluir parâmetro para informar o ano na função "sefazInutiliza"

### ISSUE THREAD

**Issue by JulianoAmaralChaves** [nfephp-org/nfephp#842]
De acordo com uma documentação que li, o ano a ser informado é o ano em que ocorreu a quebra da sequência e não o ano da solicitação da inutilização

Se pegar o ano atual poderá ter problema ao inutilizar em janeiro, uma quebra de sequência que tenha corrido em dezembro do ano anterior

**Comment by chinnonsantos** [comment]
Concordo, no manual versão 6.0 pág 49 tem a definição do atributo:

> Ano de inutilização da numeração

Se estiver mexendo nisso, faz a alteração pra nós e manda um pull request

**Comment by robmachado** [comment]
Olha com atenção !!!

O campo diz "ano da inutilização" e não "ano de emissão das notas
inutilizadas" !!!

Pelo que li o código está correto.

Roberto

**Comment by JulianoAmaralChaves** [comment]
Na documentação que li esta deste jeito:

"informar o ano, considerar o ano em tenha ocorrida a quebrada da sequência, se o problema ocorreu em dezembro/2009, mesmo que a inutilização seja solicitada em 2010, o ano deve ser 2009"

**Comment by robmachado** [comment]
Novamente eu pergunto "onde" está essa informação em qual manual ou Nota Técnica da SEFAZ

**Comment by robmachado** [comment]
Caso você encontre alguma "BASE LEGAL" para a sua afirmação, por favor reabra essa ISSUE !!!
Obrigado
