### ISSUE TITLE
txt2xml e emissor gratuito

### ISSUE THREAD

**Issue by AdryanSignor** [nfephp-org/nfephp#844]
Olá,
Utilizando o método de importação de "txt2xml", o "zSliceNotas" verifica se existe mais de uma Nota Fiscal dentro do txt com a tag "NOTA", porém o emissor gratuito está exportando uma única tag "NOTA" com a quantidade de notas, deixando as demais NFs separadas pelas tags "A" com a versão.
Assim quando é realizada a importação de um arquivo txt contendo várias notas é convertida apenas uma nota, ignorando as demais.

**Comment by robmachado** [comment]
Adryan me faça uma gentileza e passe uma cópia desse arquivo TXT para mim que eu faço as devidas correções

**Comment by AdryanSignor** [comment]
Roberto, segue o anexo.
[NFe.txt](https://github.com/nfephp-org/nfephp/files/378056/NFe.txt)

**Comment by robmachado** [comment]
Corrigido o erro relativo a classe MakeNFe 
Por erro haviam sido inclusos campos incorretos na montagem da método tagprod(), os campos NVE e CEST tem entradas separadas, pois podem ocorrer mais de uma vez para cada produto.
E em alguma contribuição anterior foram erroneamente inseridos nesse método.
