### ISSUE TITLE
Conversão de TXT para XML (txt2xml)

### ISSUE THREAD

**Issue by marciolr** [nfephp-org/nfephp#845]
Testado com oarquivo txt do exemplo, NOTAFISCAL310.txt
O arquivo xml está vindo com os campos do produto, grupo I, trocados como por exemplo o CFOP.
TXT:
`I|BOLH-S1252||BE6007550 SACO BOLHA SIMPLES 010 DIAM 600X1200X0,10|39232190||5101|MI|0.4000|1060.5000000000|424.20||MI|0.4000|1060.5000000000|||||1|12345|1|D1B1EAD4-5AEF-4648-A5E3-A5EB391B19BB|`
XML:
`<det nItem="1"><prod><cProd>BOLH-S1252</cProd><cEAN/><xProd>BE6007550 SACO BOLHA SIMPLES 010 DIAM 600X1200X0,10</xProd><NCM>39232190</NCM><CEST>5101</CEST><NVE>AB0001</NVE><NVE>AA0022</NVE><NVE>AF1111</NVE><EXTIPI>MI</EXTIPI><CFOP>0.4000</CFOP><uCom>1060.5000000000</uCom><qCom>424.20</qCom><vUnCom/><vProd>MI</vProd><cEANTrib>0.4000</cEANTrib><uTrib>1060.5000000000</uTrib><qTrib/><vUnTrib/><vDesc>1</vDesc><vOutro>12345</vOutro><indTot>1</indTot><xPed>D1B1EAD4-5AEF-4648-A5E3-A5EB391B19BB</xPed><nFCI/></prod><imposto><ICMS><ICMS00><orig>0</orig><CST>00</CST><modBC>3</modBC><vBC>424.20</vBC><pICMS>18.0000</pICMS><vICMS>76.36</vICMS></ICMS00></ICMS><IPI><cEnq>999</cEnq><IPINT><CST>52</CST></IPINT></IPI><PIS><PISAliq><CST>01</CST><vBC>424.20</vBC><pPIS>0.6500</pPIS><vPIS>2.76</vPIS></PISAliq></PIS><COFINS><COFINSAliq><CST>01</CST><vBC>424.20</vBC><pCOFINS>3.0000</pCOFINS><vCOFINS>12.73</vCOFINS></COFINSAliq></COFINS></imposto></det>`

**Comment by robmachado** [comment]
Sinto mas você está ERRADO !!!

O seu TXT está incorreto!
