### ISSUE TITLE
Paths absolutos

### ISSUE THREAD

**Issue by yurisa2** [nfephp-org/nfephp#847]
Olá pessoal. 

Projeto realmente impressionante, uso bastante.
Nem me arrisco a virar contribuidor pois nem de longe sou bom o suficiente como a "lista recomendada" sugere.

Mas os paths absolutos do programa realmente atrapalham bastante, embora seja de fácil correção, é muito chato ficar procurando qual arquivo que tá referenciando o recurso/objeto errado...

Trabalho geralmente com 2 ou mais computadores, em diferentes situações, usualmente 1 mac e 2 Linux e uso bitnami de stack, o que invariavelmente tem caminhos diferentes, imagino se usasse windows.

Só uma sugestão....

Aquele abraço.

Parabéns pelo trabalho.

**Comment by robmachado** [comment]
Concordo com você e por isso estamos fazendo a refatoração no novo repositório sped-nfe, nessa refatoração todos os paths serão verificados e os relativos serão automaticamente tornados absolutos, onde necessário

**Comment by yurisa2** [comment]
Valeu, vou estudar a API e tentar ajudar! mas nem de longe sou ninja em PSR e tal...

**Comment by fmertins** [comment]
@yurisa2 Comece como um Padawan hehe...
Abraços.
