### ISSUE TITLE
Download de xml`s da SEFAZ

### ISSUE THREAD

**Issue by akaytatsu** [nfephp-org/nfephp#848]
Bom dia pessoal,

Qual rotina me permite baixar os XML emitidos para mim em lote?

Por exemplo,

sou da empresa A. Essa semana emitiram para mim 10 XML ou seja, comprei em 10 fornecedores que me emitiram a nota fiscal. Digamo que nenhum dos fornecedores me enviou o XML por email. Em qual rotina eu baixo um lote de XMLS emitido para mim?

**Comment by robmachado** [comment]
Isso não é uma ISSUE ... solicita ajuda no forum https://groups.google.com/forum/#!forum/nfephp
