### ISSUE TITLE
ConvertNFe pegando campos errados

### ISSUE THREAD

**Issue by yurisa2** [nfephp-org/nfephp#849]
Arquivo ConvertNFe.php
Convertendo um txt ele troca vários campos e dá errado 
No emissor gratuito importa ok. (aliás o TXT está igualzinho do emissor)

dá vários erros de Offset (array sem index) também. (abaixo)

```
Notice: Undefined offset: 23 in .... /nfephp/libs/NFe/ConvertNFe.php on line 293

Notice: Undefined offset: 22 in .... /nfephp/libs/NFe/ConvertNFe.php on line 844

Notice: Undefined offset: 23 in .... /nfephp/libs/NFe/ConvertNFe.php on line 845

Notice: Undefined offset: 24 in .... /nfephp/libs/NFe/ConvertNFe.php on line 846
```

Não consegui achar ainda que versão que funciona, mas os campos que ele troca são vários, CFOP x Qtd, CEST x Unidade .... e por aí vai.

Honestamente não sei como proceder, se eu achar o erro ou corrigi-lo aviso aqui antes de commitar, mas quem tem intimidade deve saber o que é....fds procurando...

Abraços.

p.s.-> mais uma vez parabéns e obrigado

**Comment by robmachado** [comment]
Vamos lá me passa o seu txt que vou converter aqui para ver essa falha ... eu mesmo uso o conversor e não tenho problemas

**Comment by yurisa2** [comment]
Roberto, valeu pela ajuda...

realmente só funcionou na versão 4.0.40, mesmo assim com erro de offset....

[nf.txt](https://github.com/nfephp-org/nfephp/files/391239/nf.txt)

Valeu demais....

(txt meramente "ilustrativo")

**Comment by robmachado** [comment]
Os "Notices" não são erros,  são apenas informações que poderiam estar melhor definidas.
Mas ok,  se está funcionando é o que importa !! vou encerrar esse ISSUE.

**Comment by yurisa2** [comment]
Então, mas tá funcionando só com uma versão antigassa...

**Comment by robmachado** [comment]
Você tem razão ... eu permiti uma contribuição e foi inserido esse ERRO estou corrigindo, mas seu TXT também tem falhas 

Primeiro na sua estrutura do mercador "I" faltam  dois campos 

I|0006||POSTE RETO 07 METROS COM SUPORTE PARA DUAS LUM|73069090||5101|PC|6.0000|536.1000|3216.60||PC|6.0000|536.1000|||||1|||**nItemPed|nFCI|**

//I|cProd|cEAN|xProd|NCM|EXTIPI|CFOP|uCom|qCom|vUnCom
// |vProd|cEANTrib|uTrib|qTrib|vUnTrib
// |vFrete|vSeg|vDesc|vOutro|indTot|xPed|nItemPed|nFCI|

No marcador "B" faltam também dois campos no final 

B|35||VENDA DE MERCADORIA|1|55|1|1842|2016-04-15T08:23:11-03:00|2016-07-29T08:23:11-03:00|1|1|3501152|1|1||1|1|0|9|3|3.10.78|**dhCont|xJust|**

//B|cUF|cNF|natOp|indPag|mod|serie|nNF|dhEmi
        // |dhSaiEnt|tpNF|idDest|cMunFG|tpImp|tpEmis
        // |cDV|tp Amb|finNFe|indFinal
        // |indPres|procEmi|verProc|dhCont|xJust|

**Comment by yurisa2** [comment]
Puts, vou verificar o TXT aqui, o mais rápido possível! obrigado demais.

Esses campos estão vindo de um ERP que estou tendo que integrar aqui... Vou avisar o DEV deles lá.


Se você precisar de alguma ajuda, por favor... nao exite
