### ISSUE TITLE
Remover o uso da classe ToolsNFe na classe DANFCE

### ISSUE THREAD

**Issue by chinnonsantos** [nfephp-org/nfephp#851]
Issue criada para formalizar a alteração, a instância da classe **ToolsNFe** na classe **Danfce** é desnecessária visto que tanto a Logo quanto o Link do QRCode podem ser informado via parâmetro na inicialização da classe, e o uso da ToolsNFe obriga a utilizar o arquivo config.json que muitos usuários não utilizam trazendo os dados direto do banco.

Se houver objeções me informe.

**Comment by robmachado** [comment]
Sem, objeções
Isso nunca deveria estar ali !!!

**Comment by robmachado** [comment]
Para a emissão do DANFCE são necessários apenas o XML e talvez o path para o LOGO nada mais !!!
Qualquer outra coisa é dispensável e não deve ser inclusa ...
