### ISSUE TITLE
NVE e CEST no método tagprod

### ISSUE THREAD

**Issue by ewertoncode** [nfephp-org/nfephp#855]
Boa noite pessoal!

Temos assim no exemplo (testaMakeNfe.php) 
$resp = $nfe->tagprod($nItem, $cProd, $cEAN, $xProd, $NCM, $NVE, $CEST, $EXTIPI, $CFOP, $uCom, $qCom, $vUnCom, $vProd, $cEANTrib, $uTrib, $qTrib, $vUnTrib, $vFrete, $vSeg, $vDesc, $vOutro, $indTot, $xPed, $nItemPed, $nFCI);

No entanto, o método tagprod da classe MakeNFe não espera os parâmetros NVE e CEST.
É isso mesmo?

**Comment by robmachado** [comment]
Esses parâmetros tem funções próprias pois podem haver mais de um valor por
item !!!!!!

*Erroneamente um colaborador incorporou isso a essa função, esses campos
não podem existir nessa função !!!*

Portanto, a função tagProd() não PODE receber e nem espera receber esses
campos (NVE e CEST)

Roberto

**Comment by ewertoncode** [comment]
Obrigado Roberto!
