### ISSUE TITLE
Não esta montando o Pdf quando o php é v7

### ISSUE THREAD

**Issue by gersonmollo** [nfephp-org/nfephp#856]
Quando estou tentando emitir o Danfce, no momento de exibição do pdf da erro de compatibilidade com o php v7. Queria saber se tem um meio de atualizar a lib mpdf pelo composer para um versão compatível com o php v7, pois estou tentando atualizar e da o seguinte erro:
 - nfephp-org/nfephp v4.0.54 requires mpdf/mpdf 6.0.0 -> satisfiable by mpdf/mpdf[v6.0.0] but these conflict with your requirements or minimum-stability.

**Comment by lpj145** [comment]
Acho que deve haver alguma outra coisa ai, aqui eu rodo tranquilamente com php 7.0 e não tive problema algum.

**Comment by lpj145** [comment]
aqui também não é lugar de se abrir questionamentos, esse repositório também perderá o seu uso, tendo em vista a atualização nos novos repositórios.

**Comment by lpj145** [comment]
https://packagist.org/packages/mpdf/mpdf segundo o requisito, php >= 5.4

**Comment by gersonmollo** [comment]
Quando ele vai exibir o Pdf, da o erro "Falha ao carregar o documento PDF", mas quando eu utilizo o php v5.4 ele exibe normalmente

**Comment by lpj145** [comment]
você deve testar a saída antes, faz um pastcode da função de impressão do pdf pra gente vê.

**Comment by gersonmollo** [comment]
Deprecated: Methods with the same name as their class will not be constructors in a future version of PHP; mPDF has a deprecated constructor in D:\Sites\franquia.hinode.com.br\vendor\mpdf\mpdf\mpdf.php on line 89

Deprecated: Methods with the same name as their class will not be constructors in a future version of PHP; grad has a deprecated constructor in D:\Sites\franquia.hinode.com.br\vendor\mpdf\mpdf\classes\grad.php on line 3

Deprecated: Methods with the same name as their class will not be constructors in a future version of PHP; mpdfform has a deprecated constructor in D:\Sites\franquia.hinode.com.br\vendor\mpdf\mpdf\classes\mpdfform.php on line 3

Deprecated: Methods with the same name as their class will not be constructors in a future version of PHP; cssmgr has a deprecated constructor in D:\Sites\franquia.hinode.com.br\vendor\mpdf\mpdf\classes\cssmgr.php on line 3

Deprecated: Methods with the same name as their class will not be constructors in a future version of PHP; otl has a deprecated constructor in D:\Sites\franquia.hinode.com.br\vendor\mpdf\mpdf\classes\otl.php on line 12

esses sao os erros que dao antes de carregar o pdf, o codigo abaixo mostra onde coloquei um var_dump, antes disso, não ocorre nenhum erro

public function printDANFCE($output = 'pdf', $nome = '', $destino = 'I')
    {
        if ($output == 'pdf') {
            //montagem do pdf
            $m = 2.1; //Margens 2.1mm = 8px do formato HTML
            if (is_array($this->papel) && strtolower($this->papel[1])=='one-page') {
                $mpdf=new mPDF('', array($this->papel[0], 841.89), 0, '', $m, $m, $m, 0, 0, 'P');
                $mpdf->useCoreFontsOnly = true;
                $mpdf->WriteHTML($this->html, 0, true, false);
                $this->papel=array($this->papel[0], $mpdf->y + $m);
            }
            $this->mpdf=new mPDF('', $this->papel, 0, '', $m, $m, $m, 0, 0, 'P');
            echo "<pre>";
            var_dump($this->mpdf);
            echo "</pre>";
            exit;
            $this->mpdf->WriteHTML($this->html);            
            return $this->mpdf->Output($nome, $destino);
        } else {
            echo $this->html;
        }
        return true;
    }

**Comment by lpj145** [comment]
só não entendo esse uso, se apegue aos exemplos.

**Comment by robmachado** [comment]
Desabilite o aviso de erros do PHP nas operações de impressão de pdf.
