### ISSUE TITLE
Incluir opção de abrir dialogo de impressão na DANFCe

### ISSUE THREAD

**Issue by JulianoAmaralChaves** [nfephp-org/nfephp#857]
Fiz um testes passando o código:

$this->mpdf->SetJS("this.print();");

antes do 

$this->mpdf->WriteHTML($this->html);

na função printDANFCE 

isso permite que assim que carregar o pdf já abra a caixa de dialogo de impressão, não sei se seria  a melhor maneira de se fazer isso, mas poderia se incluso um parâmetro na função para determinar se deve abrir ou não a caixa de dialogo de impressão, também não sei se a sugestão é um boa pedida, mas eu tive essa necessidade e talvez isso possa facilitar um pouco

**Comment by robmachado** [comment]
Olha Juliano, essa classe usando o MPDF deve desaparecer na próxima versão da API.
O mPDF não é a ferramenta adequada para essa operação devido a vários fatores (atendimento aos PSR, manutenção, PHP7 e por ai vai).

Sua solução é excelente ... mas vai desaparecer com o tempo

**Comment by JulianoAmaralChaves** [comment]
Ok Roberto, muito obrigado pela resposta

**Comment by robmachado** [comment]
Se quiser aplicar pode sugerir um PULL REQUEST não sou contra :+1:

**Comment by JulianoAmaralChaves** [comment]
Ok, eu mandei um PULL REQUEST da issue #851 que é no mesmo arquivo, não sei como funciona o controle de conflitos no git, se eu propor outro PULL REQUEST não da conflito?

**Comment by robmachado** [comment]
Você sempre deve manter seu repositório local atualizado. Com isso não o git é muito inteligente e não gera conflitos.
Para manter seu repositório local e remoto atualizado tem informações na internet, no wiki e se necessitar alguma ajuda me chame no hangout terei prazer em te ajudar no que puder 
Grande abraço

**Comment by JulianoAmaralChaves** [comment]
Obrigado Roberto, vou pesquisar na internet, se eu tiver duvidas entro em contato
