### ISSUE TITLE
Solução para parametro $templateFile da função enviaMail

### ISSUE THREAD

**Issue by rrricci** [nfephp-org/nfephp#858]
Olá.. estou utilizando a função enviaMail que se encontra em ToolsNFe.php:
public function enviaMail($pathXml = '', $aMails = array(), $templateFile = '', $comPdf = false, $pathPdf = '')porém a mesma não está considerando o parâmetro $templateFile.
Fiz uma alteração na mesma para que o template possa ser levado em consideração.. Apenas adicionei as seguintes linhas:
```
if ($templateFile != '') {
            $mail->setTemplate($templateFile);
}
```

Segue função:

```
 public function enviaMail($pathXml = '', $aMails = array(), $templateFile = '', $comPdf = false, $pathPdf = '')
    {
        $mail = new MailNFe($this->aMailConf);
        // Se não for informado o caminho do PDF, monta um através do XML
        if ($comPdf && $this->modelo == '55' && $pathPdf == '') {
            $docxml = Files\FilesFolders::readFile($pathXml);
            $danfe = new Extras\Danfe($docxml, 'P', 'A4', $this->aDocFormat['pathLogoFile'], 'I', '');
            $id = $danfe->montaDANFE();
            $pathPdf = $this->aConfig['pathNFeFiles']
                . DIRECTORY_SEPARATOR
                . $this->ambiente
                . DIRECTORY_SEPARATOR
                . 'pdf'
                . DIRECTORY_SEPARATOR
                . $id . '-danfe.pdf';
            $pdf = $danfe->printDANFE($pathPdf, 'F');
        }
	     if ($templateFile != '') {
            $mail->setTemplate($templateFile);
        }
        if ($mail->envia($pathXml, $aMails, $comPdf, $pathPdf) === false) {
            throw new Exception\RuntimeException('Email não enviado. '.$mail->error);
        }
        return true;
    }
```

Obs.: Já realizei testes na mesma e está funcionando perfeitamente..

Obrigado.
Renato Ricci

**Comment by robmachado** [comment]
O Renato .. legal ... vou corrigir sim .. mas se quiser adiantar pode faze-lo com pull request na branch DEVELOP, ou aguarde que farei isso.

Grato

**Comment by rrricci** [comment]
Estou sem permissão...

$ git push origin develop
Username for 'https://github.com': rrricci
Password for 'https://rrricci@github.com':
remote: Permission to nfephp-org/nfephp.git denied to rrricci.
fatal: unable to access 'https://github.com/nfephp-org/nfephp.git/': The requested URL returned error: 403

**Comment by robmachado** [comment]
Não ... o pull request requer que seja feito pelo seu fork

Não tenho tempo no momento de te explicar .. mas é fácil

Roberto

**Comment by rrricci** [comment]
Sem problema Roberto..
Fiz o fork do projeto.. atualizei novamente meus arquivos locais, fiz a alteração no arquivo ToolsNFe.php e submeti..
Já fiz o pull request...
Por favor veja se está tudo certo,
Obrigado,
Renato Ricci

**Comment by robmachado** [comment]
Só dois comentários

1 - faça os pull requests neste repositório apenas na branch develop, no
futuro isso não mais será feito assim e poderá usar o master sem problemas

2 - aplique o PHPCBF ao arquivo alterado para remover TABs e espaços
perdidos atendendo o PSR-2

Mas obrigado !! Já esta no ar
😀
Roberto

**Comment by rrricci** [comment]
Bacana Roberto.. pode deixar..

Obrigado!
