### ISSUE TITLE
Erro ao validar o xml

### ISSUE THREAD

**Issue by DeyvsonRS** [nfephp-org/nfephp#864]
Pessoal, sou por aqui. Estou com esse problema na hora de validar o xml gerado a partir desse txt. Quem puder me ajudar, por favor. Os erros são os seguintes:

Notice: Undefined offset: 24 in C:\xampp\htdocs\safira\data\modulos\nfephp\libs\NFe\ConvertNFe.php on line 846

Notice: Undefined offset: 24 in C:\xampp\htdocs\safira\data\modulos\nfephp\libs\NFe\ConvertNFe.php on line 846

Notice: Undefined offset: 24 in C:\xampp\htdocs\safira\data\modulos\nfephp\libs\NFe\ConvertNFe.php on line 846

Notice: Undefined offset: 16 in C:\xampp\htdocs\safira\data\modulos\nfephp\libs\NFe\ConvertNFe.php on line 2376
Eita !?! Tem bicho na linha ....
Elemento 'NVE': [Erro 'Layout'] O valor '' não é aceito para o padrão. '[A-Z]{2}[0-9]{4}'.
Elemento 'NVE': '' não é um valor válido.
Elemento 'CEST': Este elemento não é esperado. Esperado é um de ( EXTIPI, CFOP ).
Elemento 'NVE': [Erro 'Layout'] O valor '' não é aceito para o padrão. '[A-Z]{2}[0-9]{4}'.
Elemento 'NVE': '' não é um valor válido.
Elemento 'CEST': Este elemento não é esperado. Esperado é um de ( EXTIPI, CFOP ).
Elemento 'NVE': [Erro 'Layout'] O valor '' não é aceito para o padrão. '[A-Z]{2}[0-9]{4}'.
Elemento 'NVE': '' não é um valor válido.
Elemento 'CEST': Este elemento não é esperado. Esperado é um de ( EXTIPI, CFOP ).
Elemento 'vNF': [Erro 'Layout'] O valor '' não é aceito para o padrão. '0|0\.[0-9]{2}|[1-9]{1}[0-9]{0,12}(\.[0-9]{2})?'.
Elemento 'vNF': '' não é um valor válido 'TDec_1302'.
Elemento 'vTotTrib': [Erro 'Layout'] O valor '' não é aceito para o padrão. '0|0\.[0-9]{2}|[1-9]{1}[0-9]{0,12}(\.[0-9]{2})?'.
Elemento 'vTotTrib': '' não é um valor válido 'TDec_1302'. 

[Nfe3.1-209.txt](https://github.com/nfephp-org/nfephp/files/434841/Nfe3.1-209.txt)

**Comment by robmachado** [comment]
Bom vamos lá ... em seu TXT havia o seguinte

I05a||
I05c|| 

Isso indica as TAG NVE e CEST porém você não passou nada para esses campos estão vazios. A classe MakeNFe ao receber os dados está criando essas tags mesmo que vazias. Isso foi corrigido agora então se ERRONEAMENTE você passar campos dessa forma não serão criadas essas TAGS em branco.

Outro erro está no registro  
W02|0.00|0.00|0.00|0.00|1575.00|0.00|0.00|0.00|0.00|0.00|0.00|0.00|0.00|1575.00|

Falta um campo no final desse registro **_vTotTrib_**

W02|vBC|vICMS|vICMSDeson|vBCST|vST|vProd|vFrete|vSeg|vDesc|vII|vIPI|vPIS|vCOFINS|vOutro|vNF|**vTotTrib**|

Isso foi o que eu achei até agora, pode ter mais !!!

**Comment by robmachado** [comment]
Mas existem vários outros erros que vão provocar a rejeição da NFe !!!

**Comment by DeyvsonRS** [comment]
Robmachado, obrigado. Vou verificar.

**Comment by DeyvsonRS** [comment]
Robmachado, desculpa minha ignorância. Mas atualizei o arquivo: nfephp/libs/NFe/ConvertNFe.php. Mas ainda ta dando os primeiros erros que postei antes.

Notice: Undefined offset: 16 in C:\xampp\htdocs\safira\data\modulos\nfephp\libs\NFe\ConvertNFe.php on line 2358
Eita !?! Tem bicho na linha ....
Elemento 'NVE': [Erro 'Layout'] O valor '' não é aceito para o padrão. '[A-Z]{2}[0-9]{4}'.
Elemento 'NVE': '' não é um valor válido.
Elemento 'CEST': Este elemento não é esperado. Esperado é um de ( EXTIPI, CFOP ).
Elemento 'vNF': [Erro 'Layout'] O valor '' não é aceito para o padrão. '0|0\.[0-9]{2}|[1-9]{1}[0-9]{0,12}(\.[0-9]{2})?'.
Elemento 'vNF': '' não é um valor válido 'TDec_1302'.
Elemento 'vTotTrib': [Erro 'Layout'] O valor '' não é aceito para o padrão. '0|0\.[0-9]{2}|[1-9]{1}[0-9]{0,12}(\.[0-9]{2})?'.
Elemento 'vTotTrib': '' não é um valor válido 'TDec_1302'.

**Comment by robmachado** [comment]
Eu não te disse para atualizar a classe ConvertNFe ... disse ????
Quando se usa uma API, o correto em primeiro lugar é usar o composer para instalar a API na pasta vendor, para poder manter as coisas atualizadas, e não copiar um arquivo na mão !!
Não basta copiar esse arquivo pois outros foram alterados, mas eu já havia te informado do SEUS erros no TXT. 

I05a||
I05c||

Esses registros não poder ficar vazios !!! se não tem NVE ou não tem CEST não coloque esses registros no TXT

**Comment by edigomes** [comment]
Esse pull request errado que adicionou o NVE e o CEST ferrou muita gente hein!!

**Comment by DeyvsonRS** [comment]
Consegui, Roberto Machado, obrigado pela atenção!

**Comment by fmertins** [comment]
Fechando por inatividade e foi resolvido, ok...
