### ISSUE TITLE
Atualizar URL para NfeConsultaQR em nf_ws3_mod65.xml SEFAZ GO.

### ISSUE THREAD

**Issue by gitonline** [nfephp-org/nfephp#867]
Olá,

PS:  Atualizar URL para NfeConsultaQR em   nf_ws3_mod65.xml   SEFAZ GO.

 <homologacao>  
       <NfeConsultaQR method="QR-CODE" operation="NfeConsultaQR" version="100">https://homolog.sefaz.go.gov.br/nfeweb/sites/nfce/danfeNFCe</NfeConsultaQR>
    </homologacao>

```
<producao>

   <NfeConsultaQR method="QR-CODE" operation="NfeConsultaQR" version="100">http://nfe.sefaz.go.gov.br/nfeweb/sites/nfce/danfeNFCe</NfeConsultaQR>

</producao>
```

**Comment by gitonline** [comment]
Homologação
<NfeConsultaQR method="QR-CODE" operation="NfeConsultaQR" version="100">https://homolog.sefaz.go.gov.br/nfeweb/sites/nfce/danfeNFCe</NfeConsultaQR>

**Comment by robmachado** [comment]
Corrigido

**Comment by robmachado** [comment]
Isso já está lá
