### ISSUE TITLE
Rejeição: Falha no Schema XML do lote de NFe

### ISSUE THREAD

**Issue by DeyvsonRS** [nfephp-org/nfephp#868]
Pessoal, boa tarde. Estou com esse problema na hora de consultar a resposta do envio. Quem puder dar um help, por favor. Segue respota do soapDebug:
Array
(
    [bStat] => 1
    [versao] => 3.10
    [tpAmb] => 2
    [cStat] => 225
    [verAplic] => SP_NFE_PL_008i2
    [xMotivo] => Rejeição: Falha no Schema XML do lote de NFe
    [dhRecbto] => 2016-08-31T15:02:04-03:00
    [cUF] => 35
    [nRec] => 351000102973591
    [aProt] => Array
        (
        )

)

**Comment by fmertins** [comment]
Olá, não parece ser erro da API, por favor escreva no grupo do Google que deves conseguir melhor ajuda lá, abraços.
https://groups.google.com/forum/#!forum/nfephp
