### ISSUE TITLE
Metodo zClean

### ISSUE THREAD

**Issue by weguri** [nfephp-org/nfephp#869]
O método **zClean** da classe **ConvertNFe** retorna a mesma variável de entrada.

```
protected function zClean($aCampos = array())
{
    foreach ($aCampos as $campo) {
        $campo = trim(preg_replace('/\s+/', ' ', $campo));
        if ($this->limparString) {
            $campo = Strings::cleanString($campo);
        }
    }
    return $aCampos;
}
```

Não deveria retornar um novo array?

**Comment by robmachado** [comment]
Sim e é isso que ele retorna o ARRAY $aCampos
Não entendi sua colocação ?!?!

**Comment by weguri** [comment]
O meu exemplo de uso: `var_dump(zClean(['  teste   ','ação','é       agora       ção ']));`
a saída ficou igual a entrada.

Fiz sobrescrita no método para resolver o meu problema, da forma que está abaixo os caracteres de especiais e os espaços extras foram limpados:

    protected function zClean($aCampos = array()) 
    {
       $arrAuxiliar=[];
        foreach ($aCampos as $campo) {
            $campo = trim(preg_replace('/\s+/', ' ', $campo));
            if ($this->limparString) {
                $arrAuxiliar[] = Strings::cleanString($campo);
            }
        }
        return $arrAuxiliar;
    }

**Comment by robmachado** [comment]
OK .. já chequei o problema. Realmente é um BUG vou corrigir mas de outra forma. Pois no seu caso ainda tem um erro quando a propriedade $this->limparString for FALSE essa sua função vai retornar um array vazio.

**Comment by weguri** [comment]
Muito obrigado...
