### ISSUE TITLE
Validação do XML

### ISSUE THREAD

**Issue by maiconkamiya** [nfephp-org/nfephp#884]
Mesmo informando o modelo 55 esta aparencendo a mensagem 
"Elemento 'NFe': Elemento filho faltando. Era esperado um de ( infNFeSupl, {http://www.w3.org/2000/09/xmldsig#}Signature )"

**Comment by robmachado** [comment]
Não sei o que você está fazendo ? Mas com certeza é um erro seu .

**Comment by maiconkamiya** [comment]
Após assinar o XML eu tentei validar o XML, e é nesse momento que aparece este erro.

**Comment by maiconkamiya** [comment]
Eu verifiquei o xsd e esse erro é pra nfce que utiliza qrcode, mas é para o modelo 65 e não o 55

**Comment by robmachado** [comment]
Repito que você está cometendo algum erro ... essa tag é criada na assinatura de um NFCe (modelo 65 apenas)

**Comment by maiconkamiya** [comment]
Hum. Desculpe pela falta de conhecimento, é que sou novo no nfephp. É que estou seguindo o exemplo que está no repositório.

**Comment by robmachado** [comment]
Faça um debug ... em algum momento o modelo está sendo colocado como 65 !!! Ou esta usando o xsd de versão incorreta !!

**Comment by robmachado** [comment]
Parceiro!!! 
é OBVIO que eu já sei isso!!!
Eu escrevi a API, estou dizendo que você está fazendo algo muito errado ai faça o DEBUG linha a linha com o xDebug

**Comment by heltucosta** [comment]
Vou aproveitar que essa issue está aberta e colocar uma duvida que estou tendo aqui.
Estou enviando uma NFe, por enquanto no ambiente de homologação, e consigo criar, assinar e validar, porém, ao tentar enviar, recebo a seguinte resposta:

`[xMotivo] => Rejeicao: Falha no Schema XML do lote de NFe`

Achei esquisito, verifiquei tanto o arquivo que esta sendo utilizado para validação do XML quanto o link para o ambiente de homologação e ambos estão corretos.

Agradeço se alguém puder me dar uma luz.

**Comment by olavocneto** [comment]
Olá @heltucosta ,

Essa mensagem já aconteceu comigo e não me recordo as soluções exatas por que a cada vez era diferente a solução e as vezes questões de negócio em vez de técnicas.

Já conhece o grupo de discussão do projeto? Se não, acessa a página da organização http://www.nfephp.org/pt/latest/ e no 2° parágrafo tem o link. Usa a **barra de pesquisa**; https://groups.google.com/forum/#!searchin/nfephp/%22Falha$20no$20Schema$20XML$20do$20lote$20de$20NFe%22%7Csort:relevance Tem bastante tópico parecido, dá uma boa estudada. Oportunidade pra já ver outros assuntos.

Outra, tem o Gitter da organização também; https://gitter.im/nfephp-org/nfephp. Lá você pode trocar uma ideia com uma resposta mais rápida.

Abraço.

**Comment by heltucosta** [comment]
Nossa, obrigado @olavocneto. 
Vai me ajudar bastante, vou participar dos grupos com certeza.
