### ISSUE TITLE
Dacte

### ISSUE THREAD

**Issue by cacio** [nfephp-org/nfephp#887]
Bom dia ,
Não sei se é aqui que devo colocar esse problema mas eu tenho uma impressão de dacte do cte, mas o problema que acontece é que na parte dos DOCUMENTOS ORIGINÁRIOS eu tenho 17 notas e quando eu vo gera as chaves passam por cima de OBSERVAÇÃO E DADOS ESPECÍFICOS ABAIXO faz com que meu dacte mal visualizado , sera que alguém tem uma atualização disso para me auxiliar. 
segue o link da imagem abaixo.
[http://prodapro.com/cacio/Capturar.PNG](url)

**Comment by robmachado** [comment]
Cacio este repositório não tem DACTE nem CTe .. este repositório serve apenas e UNICAMENTE a NFe.

Por favor leve seu problema ao grupo ou ao repositório correto, os documentos auxiliares estão em sped-da https://github.com/nfephp-org/sped-da
