### ISSUE TITLE
Envio de NFC-e por email

### ISSUE THREAD

**Issue by ianclever** [nfephp-org/nfephp#892]
Bom dia,
Conforme a própria documentação do nfephp diz, o envio de e-mail só está habilitado para NFe, venho aqui para solicitar que vocês adicionem essa funcionalidade. O que acham é viável?

Enquanto isso eu vou improvisar no meu ambiente local, para fazer isso funcionar.

**Comment by robmachado** [comment]
Toda melhoria será feita apenas no novo repositório em sped-nfe, este repositório apenas recebe e implementa correções de BUG.
