### ISSUE TITLE
Dependência com ServiceManager ?

### ISSUE THREAD

**Issue by rwrz** [nfephp-org/nfephp#894]
Estou querendo utilizar a biblioteca, porém vejo que temos uma dependencia pelo ServiceManager ^2.5... além de ser uma versão obsoleta, não consegui encontrar vocês utilizam o ServiceManager para que eu atualize os arquivos para nova versão e publique um Pull Request.

**Comment by robmachado** [comment]
Apenas para o email pode retirar, na refatoração isso foi retirado  junto
com várias outras coisas inuteis

Roberto

**Comment by robmachado** [comment]
Já atualizado o release
