### ISSUE TITLE
Docker da nfephp

### ISSUE THREAD

**Issue by alexsandro-xpt** [nfephp-org/nfephp#897]
Alguem ja pensou em rodar o nfephp em uma imagem docker?

**Comment by robmachado** [comment]
Eu rodo com Vagrant, muitas vezes. 
Mas por que esse interesse ?

**Comment by alexsandro-xpt** [comment]
Mais pratico, ainda não instalei o nfephp, mas pelo que vi, ele é instalado via composer nao é?

**Comment by robmachado** [comment]
Sim todos os nossos projetos tem a instalação via composer.

**Comment by alexsandro-xpt** [comment]
Um dockers ja poderia vim com todas dependência, o que acha?

**Comment by robmachado** [comment]
Isso pode ajudar em parte e em parte não, pois isso eliminaria todos os erros decorrentes do ambiente.
Particularmente eu acredito que um desenvolvedor deve obrigatoriamente dominar a instalação das dependências do seu ambiente, tanto de desenvolvimento como de produção. Dominar esse assunto é crucial para a manutenção de um sistema a longo prazo.

Nada tenho quanto a criar uma maquina virtual usando o Docker e deixar o ambiente totalmente preparado para rodar o PHP completo, pois como eu já disse eu uso o Vagrant regularmente. Mas não sei se realmente seria de grande ajuda, dos mais de 3000 membros do nosso grupo, apenas uns poucos (menos de 10) colaboram com algum desenvolvimento e isso ao longo de mais de 8 anos. Um Docker não seria útil para o sistema deles uma vez que teriam de instalar nesse ambiente também. Essas são minhas duvidas, vale a pena o tempo e esforço para isso ?  Se você acha que vale eu lhe dou todo o suporte que necessitar para levar isso adiante, pois acredito que não sou o dono da verdade e posso estar enganado e toda e qualquer interesse é sempre muito bem vindo.

**Comment by alexsandro-xpt** [comment]
Entendi, eu acompanho o nfephp a uns anos, mas nunca o usei, acredito para que eu possa usar, precisarei de um certificado A1 não é mesmo?

Vendo aqui a estrutura do projeto http://www.nfephp.org/pt/latest/estrutura/ ele não possui um emissor, correto?

Gostaria de entender melhor este projeto.

**Comment by robmachado** [comment]
Sim @alexsandro-xpt, um certificado A1, autorizxado e válido, é essencial  para poder usar mesmo apenas em ambiente de testes.
Não o NFePHP não é um emissor é um pequeno framework para fazer o backend entre o ERP e a SEFAZ. Ele monta o xml da NFe, assina, valida, transmite via SOAP, recebe o retorno, imprime a DANFE e envia o email ao destinatário.

**Comment by alexsandro-xpt** [comment]
Certo, mas aqui, se ele transmite via SOAP que é o protocolo usando no webservices da SEFAZ, então ele contem sim um emissor, certo?

Eu vou instalar o nfephp e vou dar umas estudada nele. Obrigado por enquanto.

**Comment by victorvilella** [comment]
@alexsandro-xpt O que o @robmachado quis dizer é que este projeto não oferece uma interface para um usuário leigo poder usar. Isso é trabalho dos desenvolvedores de prover esta interface para o uso da nfephp.

**Comment by lpj145** [comment]
@victorvilella apesar de ser, o projeto esta em constante mudanças, e por favor, não reclamem, temos mais de 1 mil usuários atualmente, e poucos são os que vem aqui fazer um pr decente, ou tentar pelo menos documentar.

**Comment by alexsandro-xpt** [comment]
O projeto é excelente e é uma pena que só existe em versão PHP, como eu gostaria que existisse um time e um projeto e um publico assim para uma versão em C#

**Comment by lpj145** [comment]
existir até existe, o problema é o brasileiro sempre esperar por alguém...

**Comment by alexsandro-xpt** [comment]
@lpj145 Existe? Qual? Por que eu comecei fazer a minha versão, porem vejo que é praticamente impossível chegar ao nível do nfephp.

**Comment by brunoconstantino** [comment]
@alexsandro-xpt  Para C# dê uma olhada aqui: https://github.com/adeniltonbs/Zeus.Net.NFe.NFCe

**Comment by alexsandro-xpt** [comment]
Muito bom @brunoconstantino vou dar uma estudada tambem... Valew!!

**Comment by robmachado** [comment]
Srs. Como esse assunto não é um ISSER estou encerrando caso queiram continuar as conversas sugiro o GITTER ou o nosso Grupo 
Abraço
