### ISSUE TITLE
Documentation is wrong

### ISSUE THREAD

**Issue by ramiromd** [nfephp-org/nfephp#898]
Hi all, my name is Ramiro and found this library searching data in Google about electronic invoice in Brazil.

Congratulations, the library seems very good ! Reading the documentation, i found an error in the below example:

`$tools = new NFePHP\Tools($config);`

The correct way:

`$tools = new NFePHP\NFe\ToolsNFe($config);`

**Comment by robmachado** [comment]
Yes, you're right. And I'm telling you, there are a lot more flaws in the documentation because we not had enough time or collaboration to correct these errors.

Be aware that the repository of this API is being changed to sped-nfe and in the next version 5.0 will be many large changes.

**Comment by ramiromd** [comment]
Hi !

> Be aware that the repository of this API is being changed to sped-nfe and in the next version 5.0 will be many large changes.

Oh ! I need finish the "Electronic invoice requirement" for my customer ASAP :worried: Do you recommend me use sped-nfe ? Or is not stable yet ? What are the differences ?

Thanks for you reply !!!

**Comment by lpj145** [comment]
@ramiromd you need know about SPED documents. is not a good idea try it without knwoledge.

**Comment by robmachado** [comment]
Yes sped-nfe repository is version 4.1.x is diferent form nfephp (4.0.x)
and new version 5.0.x still under develop and do not work yet.

To 5.0.x version have a large number of differences but not yet documented
becouse is under development

Roberto
