### ISSUE TITLE
O certificado não pode ser lido!! Senha errada ou arquivo corrompido ou formato inválido!!

### ISSUE THREAD

**Issue by ramiromd** [nfephp-org/nfephp#899]
I am testing the library in development environment with this json config:

```
"tpAmb": 2,
"pathCertsFiles": "certs/",
"certPfxName":"certificado_teste.pfx",
"certPassword":"JIO&$@2990_zx",
"certPhrase":"tajomstvo"
```

But, i catched the next exception:

> EXCEPTION CATCHED !!! 
> [0] O certificado não pode ser lido!! Senha errada ou arquivo corrompido ou formato inválido!!
> File: /var/www/gad.contrib.dev/public_html/nfe-br/vendor/nfephp-org/nfephp/libs/Common/Certificate/Pkcs12.php
> Line: 282

Any ideas ?

**Comment by lpj145** [comment]
@ramiromd you know about certificates on brazil ? you need certificates valid by ICP. is first requirements.

**Comment by lpj145** [comment]
Please... you certificate test is valid ?

**Comment by robmachado** [comment]
Ramiro;

The example certificate is expired will do not work, neither for tests. The
Pkcs12::class checks if is expired and dont load if is.

Atention the path to the certificates must be real and terminate with a
"DIERECTORY_SEPARATOR"

Roberto

**Comment by ramiromd** [comment]
Thanks for all replies. Is possible get a testing certificate ? My customer is already in production using other ERP (PAF) system.

**Comment by robmachado** [comment]
Unfortunately, to do the tests, it is compulsory to have a certificate belonging to a company authorized by SEFAZ (Secretary of the State Treasurer).
But if your customer is already an issuer there will be no problem in using his certificate.
Remembering that it is only possible to use PKCS#12 certificates (in pfx file), the PKCS#11 certificates (token or smartcard) can not be used with PHP.
