### ISSUE TITLE
tagICMSPart, tagICMSST e tagICMSSN

### ISSUE THREAD

**Issue by wfcreations** [nfephp-org/nfephp#907]
Olá, vi que no exemplo do MakeNFe tem as seguintes linhas

    //ICMSPart - ICMS em Operações Interestaduais - CST 10
    //$resp = $nfe->tagICMSPart($nItem, $orig, $cst, $modBC, $vBC, $pRedBC, $pICMS, $vICMS, $modBCST, $pMVAST, $pRedBCST, $vBCST, $pICMSST, $vICMSST, $pBCOp, $ufST);
    //ICMSST - Tributação ICMS por Substituição Tributária (ST) - CST 40, 41, 50 e 51
    //$resp = $nfe->tagICMSST($nItem, $orig, $cst, $vBCSTRet, $vICMSSTRet, $vBCSTDest, $vICMSSTDest);
    //ICMSSN - Tributação ICMS pelo Simples Nacional - CST 30
    //$resp = $nfe->tagICMSSN($nItem, $orig, $csosn, $modBC, $vBC, $pRedBC, $pICMS, $vICMS, $pCredSN, $vCredICMSSN, $modBCST, $pMVAST, $pRedBCST, $vBCST, $pICMSST, $vICMSST, $vBCSTRet, $vICMSSTRet);

A partilha não deveria ser para operações interestaduais, isso é, quando o UF do emitente é diferente do destinatário, ao invés do ICMS CST 10?

A substituição tributária na verdade não seria para os códigos: 10, 30, 70, 90, 201, 202, 203 e 900 ao invés do 40, 41, 50 e 51

E a tributação ICMSSN não é para o grupo de CRT (Código de regime tributário) quando igual a 1? ao invés do 30?

**Comment by robmachado** [comment]
Eu não sei, teve outras pessoas alterando o exemplo !!
Ademais, o exemplo não foi feito pensando em todas as regras corretas é apenas um exemplo de uso, e se estiver errado pode corrigir e fazer um pull request

**Comment by wfcreations** [comment]
Blz, vou fazer as correções, na verdade é apenas nos comentários de cada tag
