### ISSUE TITLE
Método 'addCancelamento' da classe ToolsNFe não aceita string xml como parâmetro

### ISSUE THREAD

**Issue by ianclever** [nfephp-org/nfephp#915]
Estive olhando o método addCancelamento e notei que as variáveis '$pathNFefile' e '$pathCancfile', só aceitam como parâmetro um path para arquivo XML, uma sugestão seria que ele aceite também string XML, igual outras funções da mesma classe.

O outro ponto é uma sugestão/dúvida, que eu observei no manual de orientação do contribuinte é que no caso do cancelamento de nota podem ser aceitas de 1 a 20 notas por lote, mas o nfephp aceita somente 1. No meu caso isso não me afeta em nada, mas não sei se em um contexto mais geral isso seria interessante.

**Comment by robmachado** [comment]
Todas as sugestões de melhorias devem ser direcionadas para [sped-nfe](https://github.com/nfephp-org/sped-nfe)
Este repositório somente aceitará correções de BUGs e será em breve DESCONTINUADO
