### ISSUE TITLE
Minas Gerais

### ISSUE THREAD

**Issue by ricardocaldeira** [nfephp-org/nfephp#916]
Bom dia, não sei se estou perguntando no local certo más....

Estou iniciando os processos para emissão de NFe utilizando este. Gostaria de saber, caso eu emita NFe em um cliente atuante no estado de MG, tenho que fazer algo diferente ou o nfephp já está preparado para isso?
Alguém poderia me indicar alguma leitura referente a homologação na SEFAZ MG e DF? Ou para NFe é desnecessário?

**Comment by fmertins** [comment]
Bom Ricardo, o nfephp já está preparado. O ideal para este tipo de dúvidas é o grupo de discussão no Google Groups, https://groups.google.com/d/forum/nfephp

**Comment by ricardocaldeira** [comment]
Opa, vlw....
Já vou assinar para receber as atualizações do Foogle Groups...
