### ISSUE TITLE
Symfony 2 + Form + Controller

### ISSUE THREAD

**Issue by raphox** [nfephp-org/nfephp#918]
Olá pessoal,

Quero compartilhar com todos minha implementação versão alpha (https://gist.github.com/raphox/a3d2634c6f90a7a1be2c2fa10c3ce264) da integração da nfephp com o Symfony 2. Deu bastante trabalho e acho que poder ajudar outros.

Eu uso meus próprios objetos de produtos, emitente e cliente. Mas acho que o controller e o form servirá de base para outras implementações.

Essa é minha primeira forma de agradecer aos criadores da nfephp. Eu pretendo propor alguma coisa para impressão em HTML do DANFE já que ainda não tem. Mas quando eu não tenho certeza :D

Abro essa issue para que outros possam sugerir modificações ou questionarem casos seja necessário.

Abraços.

**Comment by robmachado** [comment]
Grato Rafael;

Vamos dar uma olhada e postar no grupo !

**Comment by robmachado** [comment]
Postado no grupo !!
