### ISSUE TITLE
BUG nfe_ws3_mod65.xml url producao GO

### ISSUE THREAD

**Issue by kalenin** [nfephp-org/nfephp#919]
<NfeAutorizacao method="nfeAutorizacao" operation="NfeAutorizacao" version="3.10">https://homolog.sefaz.go.gov.br/nfe/services/v2/NfeAutorizacao</NfeAutorizacao>

A tag de producao esta com a url de homologacao -- linha 173

**Comment by robmachado** [comment]
Veja no repositório isso já foi corrigido !!

**Comment by kalenin** [comment]
O que esta arrumado no repositorio é o arquivo nfe_ws3_mod55.xml para NFe. 
Ainda está errado no nfe_ws3_mod65.xml para NFC-e.

**Comment by robmachado** [comment]
Meu engano .. li sem atenção desculpe, você está certíssimo !!

**Comment by robmachado** [comment]
Corrigido !!
