### ISSUE TITLE
Erro ao informar o CEST

### ISSUE THREAD

**Issue by JosemarOdia** [nfephp-org/nfephp#921]
Ao informar a tag CEST: 
$resp = $nfe->tagCEST($nItem, $codCEST);

Estou recebendo o seguinte erro:

Fatal error: Uncaught Error: Call to a member function getElementsByTagName() on null in /home/nfe/www/Desenv/vendor/nfephp-org/nfephp/libs/NFe/MakeNFe.php:4055 Stack trace: #0 /home/nfe/www/Desenv/vendor/nfephp-org/nfephp/libs/NFe/MakeNFe.php(132): NFePHP\NFe\MakeNFe->zTagdet()------------ {main} thrown in /home/nfe/www/Desenv/vendor/nfephp-org/nfephp/libs/NFe/MakeNFe.php on line 4055

Eu não estou informando para o produto em questão a propriedade "EXTIPI", que é utilizado nessa linha do erro "MakeNFe.php on line 4055". Porém, tentei passar um valor nessa propriedade para testes, e ainda assim o erro persistiu.

**Comment by robmachado** [comment]
Esse BUG não ocorre aqui, pode ser relativo a configuração do PHP. Mas o código pode ser melhorado alterando a linha para

$node = !empty($prod->getElementsByTagName("EXTIPI")->item(0)) ? $prod->getElementsByTagName("EXTIPI")->item(0) : '';

Com isso não deve haver esse "ERRO FATAL"

**Comment by JosemarOdia** [comment]
Desculpem-me!
Cometi um erro no meu desenvolvimento. Enviei o $nItem com um valor incrementado para a tag cest, e por isso causou o "ERRO FATAL". Não era relativo a API.
