### ISSUE TITLE
DANFE no smartphone

### ISSUE THREAD

**Issue by wfcreations** [nfephp-org/nfephp#922]
Tentei abrir o PDF da DANFE no smartphone e dá a mensagem "não é possível abrir o arquivo".

É possível que o arquivo de PDF tenha alguma incompatibilidade?

**Comment by robmachado** [comment]
Essa sua duvida, não foi colocada no local correto !! Isso não é um problema da API.
Refaça sua duvida no grupo e não aqui.
Podem haver muitos motivos diferentes para que não possa abrir um PDF no seu celular, a versão do arquivo PODE ser uma delas, mas não é o único motivo. Devido a essa explicação que estou fechando essa ISSUE. Lá no grupo existem muito mais colaboradores capazes de auxiliar e testar, pessoalmente não tenho nem como pois meu celular é dos antigos, só VOZ.
