### ISSUE TITLE
Erro ao tentar validar o xml

### ISSUE THREAD

**Issue by WiltonNunes** [nfephp-org/nfephp#924]
Tentei validar o xml crado atraves da classe MakeNFe ocorre o seguinte erro.

Eita !?! Tem bicho na linha ....
Elemento 'IE': Este elemento não é esperado. Esperado é ( enderEmit ).
Elemento 'CEST': Este elemento não é esperado. Esperado é um de ( NVE, EXTIPI, CFOP ).

**Comment by edigomes** [comment]
Acho que vc tem que atualizar sua versão, teve um pull request que entrou bugado e quebrou a API nessa função num dos releases anteriores!

**Comment by WiltonNunes** [comment]
Atualizei a versão e o problema continua.

**Comment by robmachado** [comment]
Você não está colocando todas as tags necessárias !! Está usando incorretamente a classe.

Para tirar duvidas sobre o uso não utilize as ISSUES, use o grupo do google.
As issues são para indicar BUGs e ou outros problemas e não sobre questões de uso das classes, propriamente. As issues podem tembés ser usadas para propor melhorias e coisas do tipo mas não se prestam a esse tipo de problema que decorre de uso incorreto.
