### ISSUE TITLE
Composer faltando dependência

### ISSUE THREAD

**Issue by Valkhan** [nfephp-org/nfephp#927]
Primeiramente quero agradecer a todos os colaboradores deste projeto pela excelente solução desenvolvida.

Quero deixar minha contribuição pois normalmente utilizo bibliotecas de e-mail externa mas hoje em outro projeto resolvi usar a biblioteca nativa, e para minha surprese uma classe Zend Service Manager não estava presente.

A solução que fiz foi simples:

Adicionei a dependência "zendframework/zend-servicemanager": "*", no arquivo composer.json e fiz o update, feito isso tudo funcionou.

Grato pela atenção, espero que auxilie outros desenvolvedores.

**Comment by robmachado** [comment]
Como já disse na outra ISSUE que você abriu, esta função foi movida (envio de emails) para [sped-mail](https://github.com/nfephp-org/sped-mail)
