### ISSUE TITLE
Problemas SEFAZ Goias

### ISSUE THREAD

**Issue by jorgeLauand** [nfephp-org/nfephp#932]
Prezado,

Não estamos conseguindo fazer o cancelamento da nota fiscal do SEFAZ de Goias. Pegamos o novo arquivo nfe_ws3_mod55.xml, imaginamos que estivéssemos desatualizados e poderia ser o link errado, mas infelizmente continuamos sem conseguir fazer a operação. 

Vale lembrar que trabalhamos com outros estados e a rotina está perfeita.

Poderia por favor passar uma orientação.

Desde já agradeço a sua atenção,

Jorge Lauand

**Comment by robmachado** [comment]
Sem saber qual é o erro fica difícil ajudar ?!?!?
E como você mesmo disse está normal para todos os outros estados ! Então não é um problema de código seu ou da API, deve ser outra coisa, e relacionada com o serviço da SEFAZ GO.
Como você menciona o modelo 55 acredito que refere-se apenas a NFe e não a NFCe.

**Comment by jorgeLauand** [comment]
Caro Roberto,

Infelizmente não dá nenhum erro durante o cancelamento( NFe  ), mas quando vamos verificar se foi cancelada a nota no site continua inalterada.

Somente para confirmar que como para os outros estados está cancelando corretamente podemos dizer que o nosso código e a API estão perfeitos.

Comparamos os links para o site do SEFAZ Goias, não notamos nada de errado.

Grato pela pronta resposta 

Jorge

**Comment by jorgeLauand** [comment]
Roberto,

Poderia ser algum problema em nosso certificado ?

Jorge

**Comment by robmachado** [comment]
Isso não é possível !! 
Algum erro ocorreu e você não está visualizando (a notificação de erros do PHP  está provavelmente desabilitada), tem que fazer o processo em sua maquina de desenvolvimento e acompanhar o processo com o xDebug. Outra coisa veja na pasta das temporárias a solicitação de cancelamento e a resposta (se houver). Se não houve erro na comunicação existirão arquivos xml na pasta para o cancelamento solicitado e a resposta.

**Comment by robmachado** [comment]
Quanto a problema de certificado ... se fosse isso qualquer operação com GO também teria erro

**Comment by robmachado** [comment]
Sugiro .. postar os problemas no grupo terá mais ajuda ... e aqui somente com dados mais concretos

**Comment by jorgeLauand** [comment]
Roberto, 
Vou fazer os testes conforme a sua orientação.
Grato
