### ISSUE TITLE
O projeto possui registro para emitir nota em produção?

### ISSUE THREAD

**Issue by Montanheiro** [nfephp-org/nfephp#933]
Estou começando a estudar a emissão de notas fiscais, e pelo que vi que para emitir as notas em produção é necessário que o software seja registrados nas secretárias da fazenda estaduais, o projeto é registrado ou quem tiver interesse de usar tem que correr atrás desse registro?

**Comment by ewertoncode** [comment]
Olá! O cliente que tem quer autorizado pela sefaz para emitir NFe. Geralmente o contador faz este pedido.

**Comment by robmachado** [comment]
Esse tipo de duvida você deve tirar no forum e não aqui ... as ISSUES do GITHUB devem ser usadas para tratar questões relativas ao CODIGO e não duvidas básicas.

Quanto a sua duvida, não é a API que deve ser homologada e sim o APLICATIVO e isso depende de legislações estaduais, cada estado tem a sua especifica. E normalmente referem-se a emissão de NFCe.
