### ISSUE TITLE
URL de homologação errada para RN

### ISSUE THREAD

**Issue by cicerogeorge** [nfephp-org/nfephp#934]
Depois de certa pesquisa verifiquei que a url nos arquivos config/nfe_ws3_mod55.xml e config/nfe_ws3_mod65.xml estão incorretas para o Rio Grande do Norte e possivelmente para outros estados.

Entrei em contato com a secretaria do estado (SET RN) e os links corretos estão neste endereço: http://nfce.encat.org/desenvolvedor/qrcode/

Já atualizei meu projeto e está funcionando (em homologação) perfeitamente.

**Comment by robmachado** [comment]
Grato pela ajuda mas caso possa faça um pull request com as correções

**Comment by cicerogeorge** [comment]
Pode deixar que eu dou um pull request. Abs!

**Comment by igorwanbarros** [comment]
Boa tarde a todos, acabei "caindo" no mesmo problema do amigo @cicerogeorge  só que no estado da PB.
Fiz a alteração (dos endereços) no arquivo nfe_ws3_mod65.xml e vou fazer o PR!

**Comment by robmachado** [comment]
Seu Pull Request já foi aceito e incluso em release
