### ISSUE TITLE
Erro na descrição do produto em ambiente de homologação

### ISSUE THREAD

**Issue by ianclever** [nfephp-org/nfephp#936]
No método 'tagprod' da classe 'MakeNFe.php', a tag xProd de todos os produtos está recebendo o valor 'NOTA FISCAL EMITIDA EM AMBIENTE DE HOMOLOGACAO - SEM VALOR FISCAL', quando na realidade deveria ser somente o primeiro, como diz a norma técnica 2015/002.

**Comment by jefferson-william** [comment]
Realmente na Norma Técnica explicita que apenas o primeiro é necessário ter
o nome do produto diferente do original da forma citada.

Em sex, 3 de fev de 2017 às 15:21, ianclever <notifications@github.com>
escreveu:

**Comment by robmachado** [comment]
Sim ....

Na linha 1277
```php
if ($this->tpAmb == '2' && $this->mod == '65') {
    $xProd = 'NOTA FISCAL EMITIDA EM AMBIENTE DE HOMOLOGACAO - SEM VALOR FISCAL';
    // quando for NFCe muda o nome do produto
}
```

Deveria ser:
```php
if ($this->tpAmb == '2' && $this->mod == '65' && $nItem == 1) {
    $xProd = 'NOTA FISCAL EMITIDA EM AMBIENTE DE HOMOLOGACAO - SEM VALOR FISCAL';
    // quando for NFCe muda o nome do produto
}
```
