### ISSUE TITLE
Ler arquivo txt nfe 3.10

### ISSUE THREAD

**Issue by rafahcardoso** [nfephp-org/nfephp#939]
Bom dia

Alguem tem um script para que eu leia o arquivo txt da receita ? vou pegar os dados e jogar numa variavel de sessao do meu programa pra gerar a nfe.

Grato e no aguardo.

**Comment by robmachado** [comment]
Existe a classe ConvertNFe que lê o txt e monta o XML

Roberto

**Comment by rafahcardoso** [comment]
Entao, mas depois como faço para percorrer o xml ? pq nos produtos as tags de impostos mudam.... tem varios csts de icms, e tal.....
eu preciso jogar esses dados para meu sistema

**Comment by robmachado** [comment]
Nesse caso você tem que estudar as classes do PHP

Caso tenha mais duvidas use o forum para perguntar aos outro participantes
