### ISSUE TITLE
Dúvida na correção de NFC-e e re-envio

### ISSUE THREAD

**Issue by cesar1983** [nfephp-org/nfephp#940]
Galera, tudo certo? Alguém que utiliza a biblioteca sabe me dizer qual o procedimento correto para corrigir notas rejeitas e re-enviar? Eu estou tentei apenas corrigir o dado com problema ( por exemplo a NCM ) , gerar e assinar novamente o XML, porém o retorno que tenho é de "Rejeição: Código de Hash no QR-Code difere do calculado" .

Daí pensei : Bom, vou alterar o número da nota, gerar de novo e assinar e boa, porém tenho o mesmo retorno.

Alguém pode me ajudar no procedimento correto para corrigir e re-enviar NFC-e rejeitada ?

**Comment by robmachado** [comment]
Voce deve tirar essas duvidas no forum
https://groups.google.com/forum/#!forum/nfephp

Não tenho ideia, de que forma você está procedendo a devida correção, mas o QRCode é gerado a cada nova  assinatura.

**Comment by cesar1983** [comment]
Opa, valeu!  abs
