### ISSUE TITLE
Valor vFrete

### ISSUE THREAD

**Issue by rafanake** [nfephp-org/nfephp#941]
'Elemento 'vFrete': [Erro 'Layout'] O valor '0.00' não é aceito para o padrão. '0\.[0-9]{1}[1-9]{1}|0\.[1-9]{1}[0-9]{1}|[1-9]{1}[0-9]{0,12}(\.[0-9]{2})?'.

Estou passando o valor '0.00' que é justamente o pedido, mas esta retornado erro de layout, esta com problema esta parte?

**Comment by LUCASNDIAS** [comment]
Pela expressão regular informada, só é possível valores acima de 0.00! O mínimo aceito eh 0.01

**Comment by rafanake** [comment]
Entendi Lucas, mas e no caso de Frete Grátis? Estou com XMLs protocoladas aqui onde o valor do vFrete esta como 0.00, será que a receita mudou o schema? Ninguém teve problema com frete grátis ainda?

**Comment by rafanake** [comment]
Achei o problema, quando o valor do frete do produto for 0, não se pode mais adicionar a tag vFrete no XML, então basta fazer uma validação antes de adicionar a tag:

Arquivo MakeNFe.php
Metodo tagprod()

      if (!empty($vFrete) && $vFrete > 0) {
         $this->dom->addChild(
                 $prod, "vFrete", $vFrete, false, $identificador . "[item $nItem] Valor Total do Frete"
         );
      }

**Comment by jefferson-william** [comment]
Fala Rafael, beleza?

Poderia nos ajudar informando onde descobriu que não se deve informar no
XML a tag vFreteq quando o valor for zero?

Em sex, 10 de fev de 2017 às 08:42, Rafael Leandro Fiori <
notifications@github.com> escreveu:

**Comment by robmachado** [comment]
Se o valor é ZERO não existe frete portanto esse campo deve ser deixado
como VAZIO

Roberto

**Comment by jefferson-william** [comment]
Faz sentido sim, mas é que olhando a Nota Técnica 2016.002 na página 29
mostra que a tag vFrete de ID W08 é 1-1, ou seja, obrigatória, ou será que
estou confundindo?

Em sex, 10 de fev de 2017 às 13:19, Roberto L. Machado <
notifications@github.com> escreveu:

**Comment by jefferson-william** [comment]
Ah sim, deixar o campo como vazio tudo bem, mais não informá-lo não é o
correto.

Falou bem Roberto, devemos informar a tag vFrete sem valor, ou seja, vazio
em vez de zero nestes casos.

Em sex, 10 de fev de 2017 às 13:25, Jefferson William <
jeffersonwilliammachado@gmail.com> escreveu:

**Comment by rafanake** [comment]
O Campo vazio não passa no teste do Schema
Se o Frete for 0, você só conseguirá gerar uma nota caso omita o campo vFrete...

Nenhum dos valores a seguir validaram o XML:  "", null, false, 0, 0.00
Gerei uma nota pelo TAGPLUS com o frete zerado para ver como passavam, e se fato eles também omitem o campo vFrete
