### ISSUE TITLE
Download da XML da NFe, via Chave de Acesso ?

### ISSUE THREAD

**Issue by ssjoaootavio** [nfephp-org/nfephp#944]

**Comment by olavocneto** [comment]
@ssjoaootavio acho que o grupo no Google Groups pode te ajudar https://groups.google.com/forum/#!searchin/nfephp/Download$20da$20XML$20da$20NFe$2C$20via$20Chave$20de$20Acesso$20$3F%7Csort:date Troca a pesquisa e tente outras palavras chaves e talvez melhore o resultado com o que você quer.
