### ISSUE TITLE
Atributo erros não existe na Classe MakeNFe

### ISSUE THREAD

**Issue by ianclever** [nfephp-org/nfephp#948]
Eu não tenho certeza se é um erro, mas eu pelo menos não consegui fazer isso funcionar.
Na classe MakeNFe.php existem diversos pontos onde é chamado o método addChild da classe NFePHP\Common\Dom.php, o fato é que se o parâmetro $content for vazio e $force for falso no objeto  Dom será adicionado informações de erro no atributo erros.

De volta a classe MakeNFe.php, lá no método montaNFe é verificado se um atributo 'erros' é vazio, e a partir disso retorna false. Mas a questão é que não existe esse atributo nem na MakeNFe.php nem na BaseMake.php, o que me leva a crer que esse atributo 'erros' que está sendo verificado seria o atributo 'erros' que vem da classe Dom.php.

Eu simulei uma situação que deveria inicializar esse tal atributo 'erros', mas o código funcionou como se nada tivesse acontecido.

**Comment by robmachado** [comment]
Ian;

Essas classes estão em "freezing" ou seja não mais serão atualizadas ou melhoradas. Todo o foco de desenvolvimento está na versão 5.0 em [sped-nfe](https://github.com/nfephp-org/sped-nfe/tree/v5.0)
