### ISSUE TITLE
Utilizar NFePHP no Mac OS X

### ISSUE THREAD

**Issue by MarioJunio** [nfephp-org/nfephp#949]
Estou com um probleminha ao carregar o certificado, utilizando o Mac OS Sierra versão 10.12.3, e o PHP na versão 7.0.11, e um certificado no formato 'certificado.pfx', que ao executar uma  rotina simples da API NFePHP como: `$retorno = $nfe->sefazStatus($siglaUF, $tpAmb, $aResposta);`, estou recebendo o seguinte erro:

**NFePHP\Common\Exception\RuntimeException: Não houve retorno do Curl. SSL: Can't load the certificate "/Library/WebServer/Documents/sygma-nfe/certs/16693779000108_certKEY.pem" and its private key: OSStatus -61 in /Library/WebServer/Documents/sygma-nfe/vendor/nfephp/libs/Common/Soap/CurlSoap.php on line 197**

Será que alguém poderia me ajudar a resolver esse problema ?

A propósito realizei a instalação no ambiente Windows 10, e funcionou perfeitamente.

**Comment by robmachado** [comment]
Mario; use o [forum](https://groups.google.com/forum/#!forum/nfephp) para tirar duvidas relativas a utilização e não as ISSUES do repositorio. Seu problema é provavelmente algum problema de acesso ao disco, faça um debug linha a linha usando o xDebug para localizar o erro
