### ISSUE TITLE
Instalação da API

### ISSUE THREAD

**Issue by laragallassi** [nfephp-org/nfephp#952]
Eu estou seguindo o manual para a instalação no windows, mas eu acabei empacando logo no Passo 1 - Baixando Arquivos, porque na parte que vocês dizem "clique com o direito do mouse em uma área limpa e no menu de opções clique em Use Composer Here", o composer retirou essa opção, como eu consigo fazer com que ele instale as dependências pelo prompt de comando?

Agradeço desde já.

**Comment by robmachado** [comment]
Lara; Use o forum para tirar essas e outras duvidas, e reserve os ISSUES para relatar problemas ou melhorias.
Para usar o composer pela linha de comando é muito fácil (composer install), mas isso deve ser feito na sua aplicação, com o SEU arquivo composer.json e não em coisas baixadas do repositório. Se você não conhece o composer eu sugiro fortemente que procure entender seu funcionamento antes de usar. O NFePHP (qualquer dos nossos projetos) deve ser instalado como uma dependência da sua aplicação, assim ao usar o autoload (gerado pelo composer na SUA aplicação) você terá acesso a qualquer dependência que será instalada pelo composer na pasta vendor.
O composer obedece ao PSR-4 então se você mapear suas classes em PSR-4 ficará muito mais fácil usa-lo.
