### ISSUE TITLE
Erro Enviar E-Mail

### ISSUE THREAD

**Issue by cacio** [nfephp-org/nfephp#956]
Estou me deparando com um erro não sei se é falta de dependências da classe, 
Class 'Zend\ServiceManager\AbstractPluginManager' not found in vendor\zendframework\zend-mail\src\Protocol\SmtpPluginManager.php, sempre que vou tentar enviar esta dando esse erro e estou com ultima atualização do nfephp alguém poderia me auxiliar no que pode ser

**Comment by joaoroyosilva** [comment]
No composer.json adiciona    "zendframework/zend-servicemanager": "^2.5" abaixo da linha    "zendframework/zend-mail": "^2.5". E dá um composer update novamente

**Comment by cacio** [comment]
@joaoroyosilva  Obrigado pela colaboração , agora funcionou  abraço.
