### ISSUE TITLE
Erro em Certificados da AC BOA VISTA RFB

### ISSUE THREAD

**Issue by c-alexandre2017** [nfephp-org/nfephp#960]
Estou na fase de testes em um sistema que estou desenvolvendo e tenho 3 certificados de clientes diferentes que estou testando, 2 são da AC BOA VISTA RFB e um da SERPRORFB e somente neste consigo realizar os procedimentos normais de assinatura e envio de notas nos outros 2 da a seguinte mensagem "Tokem expirado ou invalido" todos estão dentro da validade e funcionando em um outro sistema nosso para Desktop, então gostaria de uma ajuda pois não sei o que pode estar ocorrendo. Nota, os arquivos .pem são gerados normalmente na pasta ao configura-los no nfephp.
Agradeço qualquer ajuda!

**Comment by robmachado** [comment]
Como já respondi por email essa mensagem não é da API, ou seja é um retorno da SEFAZ e normalmente se refere ao CSC e ao idCSC e referem-se aos campos:
'tokenNFCe' => '',
'tokenNFCeId' => '',
Do arquivo config.json, tenha certeza de coloca-los corretamente com por exemplo:
'tokenNFCeId' => '000001';
'tokenNFCe' => 'e4ab1fa8-fe5b-42b8-909f-2d529ea60c13';

**Comment by c-alexandre2017** [comment]
Obrigado Roberto pela sua resposta, vou colocar aqui o problema pois consegui resolver e pode ser que alguem venha a se confundir como eu fiz!
O problema é que utulizo a função getIBPTProd qeu se utiliza de um Token que é gerado individualmente para cada empresa através de um cadastro no site DeOlhoNoImposto e eu estava utilizando um token que foi gerado para a nossa empresa e por isto não funcionava nos demais CNPJ de nossos cliente!! Falta de atenção!!
Talvez alguem passe por isto!
Obrigado novamente a você!

**Comment by robmachado** [comment]
Alexandre;
Tem um novo repositório para o IBPT é o sped-ibpt foi separado do NFePHP e está melhor estruturado 
[veja aqui](https://github.com/nfephp-org/sped-ibpt)
