### ISSUE TITLE
update composer

### ISSUE THREAD

**Issue by cacio** [nfephp-org/nfephp#961]
Boa tarde pessoal, preciso ver se é no phpunit do composer o problema ou no meu php, estou fazendo um update porque no composer estava faltando uma linha 
"zendframework/zend-servicemanager": "^2.5",
 e atualizar e conseguir enviar email, mas sempre que agora eu dou um composer update ta dando esse erro abaixo,

Warning: This development build of composer is over 60 days old. It is recommended to update it by running "C:\ProgramData\ComposerSetup\bin\composer.phar self-update" to get the latest version.
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - phpunit/phpunit 5.7.x-dev requires php ^5.6 || ^7.0 -> your PHP version (5.5.11) does not satisfy that requirement.
    - phpunit/phpunit 5.7.9 requires php ^5.6 || ^7.0 -> your PHP version (5.5.11) does not satisfy that requirement.
    - phpunit/phpunit 5.7.8 requires php ^5.6 || ^7.0 -> your PHP version (5.5.11) does not satisfy that requirement.
    - phpunit/phpunit 5.7.7 requires php ^5.6 || ^7.0 -> your PHP version (5.5.11) does not satisfy that requirement.
    - phpunit/phpunit 5.7.6 requires php ^5.6 || ^7.0 -> your PHP version (5.5.11) does not satisfy that requirement.
    - phpunit/phpunit 5.7.5 requires php ^5.6 || ^7.0 -> your PHP version (5.5.11) does not satisfy that requirement.
    - phpunit/phpunit 5.7.4 requires php ^5.6 || ^7.0 -> your PHP version (5.5.11) does not satisfy that requirement.
    - phpunit/phpunit 5.7.3 requires php ^5.6 || ^7.0 -> your PHP version (5.5.11) does not satisfy that requirement.
    - phpunit/phpunit 5.7.2 requires php ^5.6 || ^7.0 -> your PHP version (5.5.11) does not satisfy that requirement.
    - phpunit/phpunit 5.7.19 requires php ^5.6 || ^7.0 -> your PHP version (5.5.11) does not satisfy that requirement.
    - phpunit/phpunit 5.7.18 requires php ^5.6 || ^7.0 -> your PHP version (5.5.11) does not satisfy that requirement.
    - phpunit/phpunit 5.7.17 requires php ^5.6 || ^7.0 -> your PHP version (5.5.11) does not satisfy that requirement.
    - phpunit/phpunit 5.7.16 requires php ^5.6 || ^7.0 -> your PHP version (5.5.11) does not satisfy that requirement.
    - phpunit/phpunit 5.7.15 requires php ^5.6 || ^7.0 -> your PHP version (5.5.11) does not satisfy that requirement.
    - phpunit/phpunit 5.7.14 requires php ^5.6 || ^7.0 -> your PHP version (5.5.11) does not satisfy that requirement.
    - phpunit/phpunit 5.7.13 requires php ^5.6 || ^7.0 -> your PHP version (5.5.11) does not satisfy that requirement.
    - phpunit/phpunit 5.7.12 requires php ^5.6 || ^7.0 -> your PHP version (5.5.11) does not satisfy that requirement.
    - phpunit/phpunit 5.7.11 requires php ^5.6 || ^7.0 -> your PHP version (5.5.11) does not satisfy that requirement.
    - phpunit/phpunit 5.7.10 requires php ^5.6 || ^7.0 -> your PHP version (5.5.11) does not satisfy that requirement.
    - phpunit/phpunit 5.7.1 requires php ^5.6 || ^7.0 -> your PHP version (5.5.11) does not satisfy that requirement.
    - phpunit/phpunit 5.7.0 requires php ^5.6 || ^7.0 -> your PHP version (5.5.11) does not satisfy that requirement.
    - Installation request for phpunit/phpunit ^5.7 -> satisfiable by phpunit/phpunit[5.7.0, 5.7.1, 5.7.10, 5.7.11, 5.7.12, 5.7.13, 5.7.14, 5.7.15, 5.7.16, 5.7.17, 5.7.18, 5.7.19, 5.7.2, 5.7.3, 5.7.4, 5.7.5, 5.7.6, 5.7.7, 5.7.8, 5.7.9, 5.7.x-dev].

**Comment by olavocneto** [comment]
@cacio 

Primeiro atualize o seu composer, provavelmente não vai mudar o resultado mas é bom estar usando a última versão para otimização do autoload e class map.

```bash
sudo composer selfupdate
```

Acredito que o problema é a versão que está rodando o PHP na sua máquina dado a mensagem `- phpunit/phpunit 5.7.1 requires php ^5.6 || ^7.0 -> *your PHP version (5.5.11)* does not satisfy that requirement.`. Está codando no Windows né? Se for um linux, eu uso o https://github.com/phpbrew/phpbrew para instalar e trocar de versão PHP.

Abraço,

**Comment by robmachado** [comment]
É isso ai Olavo, :+1: 

Os pacotes do [NFePHP (todos eles)](https://github.com/nfephp-org) suportam apenas php > 5.6, preferencialmente >= 7.0 e em 2018, os pacotes sped-*, não mais irão manter compatibilidade com PHP 5.6 a sim apenas >= 7.0.

Quanto ao zend as novas versões [sped-nfe v5.0](https://github.com/nfephp-org/sped-nfe/tree/v5.0) e [sped-mail v1.0](https://github.com/nfephp-org/sped-mail) não usam mais nada da ZEND, pelo menos não diretamente.
