### ISSUE TITLE
NFCe: Nota Fiscal sem a informacao do QR-Code

### ISSUE THREAD

**Issue by ArleyOliveira** [nfephp-org/nfephp#962]
Olá, estou com esse problema na geração do QrCode na NFCe.
**Rejeicao: Nota Fiscal sem a informacao do QR-Code**

`$xmlSigned = $this->zPutQRTag($dom, $saveFile);`

Essa linha já foi descomentada, mas o erro persiste, o estado que estou tentando emitir é o RJ. 

Já testei em ambiente de produção e homologação, mas sem sucesso em ambas.

**Comment by robmachado** [comment]
Para que os QRCodes sejam inclusos é necessário que sejam indicados os código CSC e CSC_id no config.json, lá estão com os nomes antigos 'tokenNFCe' e 'tokenNFCeId'.

Além disso também é necessário que existam dados referentes ao QRCode no arquivo config/nfe_ws3_mod65.xml, na TAG referente ao RJ por exemplo não consta a URL para o QRCode e sem essa informação não tem como gerar o QRCode.

Se alguém que USA ou irá usar o NFCe para o RJ souber essa informação é só fazer um pull request para incluir esse dado.

Veja que eu não tenho como acompanhar informações de TODOS os estados, e nem sou usuário de NFCe portanto necessito da ajuda de vocês.

**Comment by ewertoncode** [comment]
Olá Amigos!

Seria esta a url?
http://www4.fazenda.rj.gov.br/consultaNFCe/QRCode?

Disponibilizada aqui:
http://nfce.encat.org/desenvolvedor/qrcode/

Obrigado!
