### ISSUE TITLE
SEFAZ GO - Cadeia completa certificado ao gerar .pem

### ISSUE THREAD

**Issue by gitonline** [nfephp-org/nfephp#963]
Em libs/Common/Certificate/Pkcs12.php foi acrescentado no final da função

 public function loadPfx(
      
as seguintes 2 linhas
Em libs/Common/Certificate/Pkcs12.php foi acrescentado no final da função

 public function loadPfx(
      
as seguintes 2 linhas

        $aCer = $x509certdata['extracerts'];  // wss
        $this->aadChain($aCer); // wss

        $aCer = $x509certdata['extracerts'];  // wss
        $this->aadChain($aCer); // wss

Desta maneira gerou os certificados para GO com cadeia completa de certificação.

Att,

Walber Sales

**Comment by robmachado** [comment]
Walber;
Nem sempre existem dados em "extracerts" nos certificados, além disso a versão do NFePHP no repositório "nfephp" está CONGELADO, não deverá receber melhorias de minha parte, posso apenas avaliar e autorizar algum PULL REQUEST não irei mais codificar, implementar melhorias ou refatorar nada nessa versão 4.0.x. Meu foco é a versão 5.0 em sped-nfe que já estou usando.
