### ISSUE TITLE
exemplos\sql\estados.sql

### ISSUE THREAD

**Issue by JamesFlavio** [nfephp-org/nfephp#964]
Estado com sigla errada, alterar de MS para MG:

Linha 39

Errado: 
INSERT INTO `estado` (id_estado, nome_estado, uf_estado, codigo_estado) VALUES (13, 'Minas Gerais', 'MS', '31');

Corrigida: INSERT INTO `estado` (id_estado, nome_estado, uf_estado, codigo_estado) VALUES (13, 'Minas Gerais', 'MG', '31');

**Comment by fmertins** [comment]
Bom dia, OK corrigido, obrigado.
