### ISSUE TITLE
Atualização para o Schema PL_009 (Versao 4.0.0)

### ISSUE THREAD

**Issue by ramirocavalcanti** [nfephp-org/nfephp#966]
Amigos,
tem alguma previsão para essa atualização?

Creio que ela seja importante para a NFe / NFCe, pois implementa a questão do troco na NFCe, que gera problema para muita gente.

**Comment by robmachado** [comment]
Atualização será no [sped-nfe](https://github.com/nfephp-org/sped-nfe/tree/v5.0) Este mês deve sair a primeira STABLE RELEASE v5.0.
O repositório do nfephp está  "FREEZE" CONGELADA e não rebeberá mais atualizações de minha parte.
A previsão da disponibilização dos ambientes para PL_009 etá no README.md do repositório indicado.

**Comment by ramirocavalcanti** [comment]
Vi depois que estava congelada, perdão. Boas notícias, aguardo a nova sped-nfe! um abraço.

**Comment by robmachado** [comment]
A v5.0 já está sendo utilizada e está funcional (para o layout 3.10), ainda não pode ser testada no novo layout 4.0 pois não existem  ainda os webservices. Portanto pode usa-la para ir ajustando seu aplicativo.
