### ISSUE TITLE
Validação de arquivo xml com outros esquemas

### ISSUE THREAD

**Issue by adrianoavelino** [nfephp-org/nfephp#970]
Gostaria de saber se com o projeto é possível validar outros tipos de arquivos xml, tipo algum módulo desse projeto para uma finalidade diferente.

**Comment by robmachado** [comment]
https://github.com/nfephp-org/sped-common/blob/master/docs/Validator.md

**Comment by adrianoavelino** [comment]
Valeu pelo retorno praticamente imediato. Era exatamente isso, mas tive que baixar somente a classe Validator, pois o package nfephp-org/sped-common tem dependência de PHP 5,5 que é diferente da versão que vou usar.
