### ISSUE TITLE
Mensagem NFe Gerado - Ambiente Teste Sem Certificado Digital

### ISSUE THREAD

**Issue by andrevanzato** [nfephp-org/nfephp#971]
Boa Tarde pessoal.
Ja faz alguns dias que estou mexendo com o NFEPHP e busquei em vários fóruns algumas informações, porém não obtive ajuda com meu problema.
Problema é o seguinte:
Ja consegui fazer o sistema gerar o XML. Já coloquei meu certificado na pasta /certs. Já configurei o arquivo config direcionando pro certificado( senha, diretório, etc). Já configurei para puxar as informações do meu banco de dados. POREM, não consigo fazer ele sair da bendita mensagem : NFe Gerado - Ambiente Teste Sem Certificado Digital.
Ele gera a NFE, porem SEM HOMOLOGAÇÃO ( sem valor fiscal).
Já consultei várias documentações, tutoriais.... sem sucesso!
Alguém poderia me ajudar a esclarecer o que pode estar ocorrendo?
Obrigado

**Comment by angraxs2** [comment]
Você precisa envá-la pra Sefaz, salvar o protocolo de envio.

Consultar esse mesmo protocolo que te retornará o protocolo de autorização da nota. Executar o addProtocolo (tem exemplo mortrando) na sua nota assinada previamente. 

Com esse protocolo adicionado, o danfe estará OK.

**Comment by cacio** [comment]
@andrevanzato na pasta certs ta os arquivos gerado .pem, mas quando tu gera o xml ele chega assina e envia pra sefaz ?

**Comment by robmachado** [comment]
Perguntas desse tipo devem ser direcionadas ao nosso forum. 
Mas adiantando:
Todas as NFe emitidas sem estarem protocoladas são SEM VALOR FISCAL e caso o tpAmb = 2 Ambiente de Homologação também. Para uma NFe ser válida deve ser emitida em ambiente de produção tpAmb = 1 (portanto com valor fiscal)  e conter o seu protocolo de autorização. Para saber mais estude a documentação da SEFAZ e os assuntos do forum.https://groups.google.com/forum/#!forum/nfephp
