### ISSUE TITLE
Arquivo vendor/autoload.php não existe

### ISSUE THREAD

**Issue by MrJackw** [nfephp-org/nfephp#972]
Estou tendo o erro: **failed to open stream: No such file or directory in (caminho)/bootstrap.php on line 3** O arquivo **vendor/autoload.php** não existe.

**Comment by juniorb2ss** [comment]
Este erro não se refere a biblioteca, e sim ao composer. Você executou os comandos de `composer install` ? Se sim, tente executar `composer dump-autoload`. Lembrando que ambiente UNIX é preciso dar permissões necessárias para os arquivos e pastas.

**Comment by robmachado** [comment]
Prezado colega, estude o composer para usar esses pacotes.
para usar é necessário que exista uma pasta "vendor" criada pelo composer

**Comment by MrJackw** [comment]
Ah sim! esqueci de execultar o **composer install**
