### ISSUE TITLE
Atualização na cadeia de certificados

### ISSUE THREAD

**Issue by dibmartins** [nfephp-org/nfephp#976]
Boa tarde!

Ao entrar no site www.nfe.fazenda.gov.br fui notificado que haverá uma mudança na cadeia de certificados no dia 27/07 para acessar esse site e o www.sefazvirtual.fazenda.gov.br. 

Isso influência em algo no funcionamento do nfephp?

Grato.

**Comment by robmachado** [comment]
Não 
Por favor esse tipo de duvida básica deve ser tratada no forum, este espaço é reservado para relato de problemas, bugs, contribuições técnicas e outros assuntos relativos ao código em si. No forum você encontrará mais colegas que poderão ajuda-lo e muita informação adicional.
