### ISSUE TITLE
Problema na geração da URL do qrCode quando NF não possui ICMS

### ISSUE THREAD

**Issue by ericalves** [nfephp-org/nfephp#978]
Boa tarde.

Queria uma ajuda dos senhores para ajustar esse problema e fazer um pull request.

Identifiquei o problema pois ao validar o XML no SEFAZ estava me acusando erro na URL do QrCode. Analisando a URL identifiquei que o parâmetro "vICMS" estava assim "..vICMS=&digV..". Fiz a seguinte alteração no arquivo ToolsNfe.php linha 634:

`        $qrcode = $this->zMakeQRCode(
            $chNFe,
            $url,
            $tpAmb,
            $dhEmi,
            $vNF,
            ($vICMS == null ? '0' : $vICMS),
            $digVal,
            $token,
            $cDest,
            $idToken,
            $versao
        );
`

Inclui a validação na variável "$vICMS".

Seria apenas nesse ponto ou valido em mais algum lugar? Ou faço direto na "zMakeQRCode"?

Obrigado.

**Comment by ericalves** [comment]
Apenas para complementar. Estou simulando emissão de NFC-e de um cliente simples, onde o produto não tem cobrança de ICMS.

**Comment by robmachado** [comment]
Eric;

Agradeço sua colaboração, apenas um detalhe essa versão que você esta
usando e comentando o BUG não está mais sendo mantida de forma ativa,
portanto quando puder foque na versão 5.0 em sped-nfe.

De qualquer forma sua informação é muito útil e será aproveitada !!

Obrigado
Roberto

**Comment by ericalves** [comment]
Bom dia.

Vou acompanhar esse novo projeto sim! Vou fazer um pull e tentar testar essa parte como está, qualquer coisa, voltamos a conversar!

Obrigado pelo retorno!
Abração.
