### ISSUE TITLE
NFe: Problema no envio - Tag infNFe

### ISSUE THREAD

**Issue by josefelipetto** [nfephp-org/nfephp#979]
Olá pessoal,

Estou com um problema no meu código e já tentei procurar em diversos sites, porém não achei nenhuma solução. Quando tento enviar meu XML para a Sefaz, o seguinte erro é retornado:
```json
{
        "bStat": true,
        "versao": "3.10",
        "tpAmb": "2",
        "verAplic": "PR-v3_8_5",
        "cStat": "225",
        "xMotivo": "Falha no Schema XML do lote de NFe. org.xml.sax.SAXParseException; lineNumber: 1; columnNumber: 2332; cvc-complex-type.2.4.b: The content of element 'infNFe' is not complete. One of '{\"http://www.portalfiscal.inf.br/nfe\":transp}' is expected.",
        "cUF": "41",
        "dhRecbto": "2017-08-15T16:29:08-03:00",
        "tMed": "",
        "nRec": "",
        "prot": [
            []
        ]
    }
```
A SEFAZ acusa algum problema na criação da tag infNFe, porém estou passando os campos exatamente como no exemplo 4.00testaMakeNFe.php:
```php
 $chave = $this->nfe->montaChave(

            $this->dadosNotaFiscal["cUF"],
            $this->dadosNotaFiscal["ano"],
            $this->dadosNotaFiscal["mes"],
            $this->dadosNotaFiscal["cnpj"],
            $this->dadosNotaFiscal["mod"],
            $this->dadosNotaFiscal["serie"],
            $this->dadosNotaFiscal["nNF"],
            $this->dadosNotaFiscal["tpEmis"],
            $this->dadosNotaFiscal["cNF"]

        );

        $this->dadosNotaFiscal["cDV"] = substr($chave, -1 );

        return $this->nfe->taginfNFe($chave, '3.10');
```

Alguém sabe o que pode estar acontecendo? 

Muito obrigado.

**Comment by robmachado** [comment]
Use o forum para obter ajuda de forma mais rápida

https://groups.google.com/forum/#!forum/nfephp

*A mensagem nada tem haver com "infNFe" *

*"The content of element 'infNFe' is not complete 'transp' is expected"*

*Em bom português.*

*A TAG infNFe está INCOMPLETA, falta a tag transp*

*A tag do transporte está faltando.*

Sem o XML não tem como lhe ajudar mais, detalhe nunca cole o xml na
mensagem sempre envie em anexo.

Roberto
