### ISSUE TITLE
Problem looking print logo

### ISSUE THREAD

**Issue by hecktorvn** [nfephp-org/nfephp#982]
Hello, I have a problem printing the company logo on **Danfe.php**.
the path of the image that comes in **phpnfe** is this below but not shown in the PDF.
**/home/www/orionweb/phpera/ext/nfephp/images/logo.jpg**

I already gave an is_file, returned **TRUE** I already opened the source but it seems everything is correct.
I wonder if you can help me with this problem.

**Comment by fmertins** [comment]
Hi there, sorry to ask, but where are you from?
Do you still have this problem?
