### ISSUE TITLE
Onde que se fornece o certificado

### ISSUE THREAD

**Issue by batata004** [nfephp-org/nfephp#984]
OLá,

Na documentacao dessa biblioteca tem um exemplo bem pratico em https://github.com/nfephp-org/nfephp/wiki/Assinando-um-XML-de-NFe

Porém nao encontrei como que eu forneco o meu certificado digital! Eu tenho um arquivo de certificado digital aqui comigo mas nesse codigo nao há nenhum parametro onde eu possa fornecer esse meu arquivo... Como que eu assino entao um XML?

**Comment by ewertoncode** [comment]
Olá!
Cara, esse é um longo caminho. Dá uma olhada nesse tutorial q esse cara fez primeiro, lá vai ter uns passo-a-passo:
https://www.youtube.com/watch?v=OOj7n57sjWw

Abs!
