### ISSUE TITLE
Consulta de NFe

### ISSUE THREAD

**Issue by ssjoaootavio** [nfephp-org/nfephp#985]
Temos uma necessidade de consulta os dados da nota fiscal, sem o carater fiscal. Pois trabalho em um empresa aonde intermediamos o frete para os nossos usuários, gostaria de desenvolver com a utilização desse projeto, para facilitar a inserção de dados para o nosso usuario, aonde ele informaria a chave da nota e buscariamos o restantes dos dados do XML.

Atualmente visualizei duas aplicações que realizam o procedimento DanfeOnline e FSist. 

Qualquer ajuda é válida!

**Comment by robmachado** [comment]
Esta API acessa e acessará apenas os webservices das SEFAZ autorizadoras.
Nesses serviços fornecidos pela SEFAZ, está a consulta das notas destinadas a um CNPJ, (notas dos fornecedores de uma empresa) para acessar esse documento é necessário um certificado valido DESSE CNPJ e realizar a manifestação de destinatário. 
O que eu acho que você procura NÃO É ISSO, então essa API não atende sua necessidade. Tanto o DanfeInLine como o FSist usam acessos a pagina de consulta de Notas das SEFAZ e da Receita e não o webservice.

**Comment by robmachado** [comment]
@ssjoaootavio 
Esses dois exemplos que você passou são CROWLERS que acessam a pagina de consulta das SEFAZ ou da Receita. Não existe o menor sentido fazer algo do tipo !! É melhor consultar diretamente essas paginas. Para evitar erros de digitação é melhor forma é fazer o SEU sistema LER diretamente o XML para fazer os lançamentos.
