### ISSUE TITLE
Certificado Transmissor sem CNPJ

### ISSUE THREAD

**Issue by elvispdosreis** [nfephp-org/nfephp#989]
Eu estou com problema para transmitir usando o soap de "Certificado Transmissor sem CNPJ" existe alguma machete para converter o pfx para pem

**Comment by robmachado** [comment]
Você deveria estar usando a biblioteca sped-nfe, esta está descontinuada !!

**Comment by elvispdosreis** [comment]
Existe alguma forma de usar ela nativamente dessa forma

$client = new \SoapClient('http://...server?wsdl',
        [
            'verifypeer' => FALSE,
            'verifyhost' => TRUE,
            'trace' => TRUE,
            'exceptions' => TRUE,
            'compression' => SOAP_COMPRESSION_ACCEPT | SOAP_COMPRESSION_GZIP,
            'soap_version' => SOAP_1_2,
            'connection_timeout' => 60,
            'local_cert' => 'D:/home/api/test/certificado.pem',
            'passphrase' => '123456',
            'authentication' => SOAP_AUTHENTICATION_DIGEST
        ]
    );

**Comment by robmachado** [comment]
O SOAP nativo não dá para usar nas comunicações com a SEFAZ devido a várias alterações exigidas pela SEFAZ , recomendo o uso do cURL.

**Comment by elvispdosreis** [comment]
Vou procurar alguma exemplo
