### ISSUE TITLE
The value '2019-07-13T20:11:17' is not accepted by the pattern

### ISSUE THREAD

**Issue by wellington-cunha** [nfephp-org/nfephp#990]
Pessoal estou fazendo teste aqui com nfephp e está apresentando o seguinte erro

<br />
<b>Fatal error</b>:  Uncaught NFePHP\Common\Exception\ValidatorException: This XML is not valid. Element '{http: //www.portalfiscal.inf.br/nfe}dhEmi': [facet 'pattern'] The value '2019-07-13T20:11:17' is not accepted by the pattern '(((20(([02468][048])|([13579][26]))-02-29))|(20[0-9][0-9])-((((0[1-9])|(1[0-2]))-((0[1-9])|(1\d)|(2[0-8])))|((((0[13578])|(1[02]))-31)|(((0[1,3-9])|(1[0-2]))-(29|30)))))T(20|21|22|23|[0-1]\d):[0-5]\d:[0-5]\d([\-,\+](0[0-9]|10|11):00|([\+](12):00))'.

Alguém sabe como resolvo isso?

**Comment by edigomes** [comment]
Falta o timezone na data

Em sáb, 13 de jul de 2019 17:19, Wellington Cunha <notifications@github.com>
escreveu:

**Comment by wellington-cunha** [comment]
Obrigado! Deu certo.
