### ISSUE TITLE
Imprimir Multiplas NF

### ISSUE THREAD

**Issue by marconwillian** [nfephp-org/nfephp#995]
Sou novo com este projeto, peguei aqui um sistema já pronto que utiliza este pacote, tenho uma demanda de criar uma impressão para todas as nf selecionadas, isto é possivel? Imprimir mais de uma pagina de NF?

Obrigado desde então.

**Comment by robmachado** [comment]
Willian;
Esse pacote esta descontinuado !!!
o pacote que realiza as impressões é o [SPED-DA](https://github.com/nfephp-org/sped-da)
